### PR TITLE
New Site Feature: RSS Feed for Release Notes

### PR DESCRIPTION
**Pull request by gfbollingerHakuna**
- Update PDS dependency 
- Adds RSS Feed for release notes at `/release-notes/rss.xml`
- Adds CTA for subscribing to RSS Feed at the top of `/release-notes`

### CODE REVIEW

**Review by rachelwhitton — DISMISSED** [review]
Local VRT test results indicate possibly unintended changes to the following: 
* Main navigation styling
* Search input styling 
* H3 styling 

glossary-diff

All 30 tests failed when comparing the preview environment from this PR to production 

@gfbollingerHakuna @mel-miller can you review and confirm whether these style changes are intentional?

**Comment by mel-miller** [comment]
@rachelwhitton — yeah those changes are fine. Since the DS is still under active development, we're going to see tiny style changes like that for a while. I was expecting the form and menu changes, and a slight font-weight change on the h3.

**Review by rachelwhitton — APPROVED** [review]

**Comment by rachelwhitton** [comment]
Thanks @mel-miller! Approved! 

Assigning to @stevector for final review and merge

**Comment by rachelwhitton** [comment]
Capturing some additional discussion from internal slack thread: 

* I recommend keeping the "Subscribe to RSS Feed" link at the top of the page, like how it is now in the preview environment. I have no preference on whether we need a second one added to the bottom of the page near the pagination feature, up to ya'll

* +1 for adding it to the top of all individual pages in this same PR 

* I think we should also publish a release note to announce but that doesn't have to block merging this PR

I defer to @mel-miller and @IngridKwok on all the above

**Comment by mel-miller** [comment]
Hi @gfbollingerHakuna — can you please add one more feature to this one? We would like to add the subscribe link to the bottom of each individual page to look something like this. Thanks. 

individual-page-release-notes

**Comment by stevector** [comment]
Re-assigning to @gfbollingerHakuna based on the last comment

**Pull request merged**
