### PR TITLE
DOCO-718 GrumPHP with Integrated Composer

### LINKED ISSUE #7861: Document safe usage of GrumPHP with Integrated Composer
Re: GrumPHP with Lando or other localdev commands breaks IC

Priority: Medium

## Issue Description

Documentation is needed on best practices for supporting GrumPHP on a site that uses a containerized local development environment AND Integrated Composer. I'm not sure where exactly this belongs but I offer the following content as a starting draft.

### How will this impact users?

Users will be able to use GrumPHP and their development environment of choice for Pantheon sites using Integrated Composer.

### Context

GrumPHP is a code quality tool that installs itself into git hooks via a Composer plugin. The hook runs whatever tasks the user specifies in their `grumphp.yml` (e.g. unit tests, code sniffing, etc.) and allows or prevents a commit as needed.

Developers using both GrumPHP and a containerized local dev environment (such as Lando or Docksal) may choose to run GrumPHP within that environment by changing the command triggered by GrumPHP on commit in thir `grumphp.yml`:

```yml
grumphp:
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: 'lando php'
```

The problem is GrumPHP runs in Integrated Composer, which in this case will cause the entire build to fail. Composer installs GrumPHP, then IC tries to make a commit, GrumPHP tries to run `lando php` and then fails because `lando` doesn't exist in Pantheon's build environment.

## Suggested Resolution
The solution is to set `EXEC_GRUMPHP_COMMAND` to run a script that tests for the needed dependencies and only runs the GrumPHP tasks if everything is all good.

```yml
grumphp:
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: '.scripts/grumphp.sh' # YOUR SCRIPT NAME HERE
```

In the case of Lando, something like this works:

```sh
#!/bin/sh
if command -v lando &> /dev/null
then
  lando php "$@"
fi
```

The test in the script could be whatever is needed in your particular case. Here's one that tests for the existence of the `PANTHEON_ENVIRONMENT` env var (credit @joestewart):

```sh
#!/bin/sh
if [ -z "$PANTHEON_ENVIRONMENT" ]  &> /dev/null
then
  php "$@"
fi
```

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #7861 

## Summary

**[Troubleshoot Integrated Composer](https://pantheon.io/docs/guides/integrated-composer/ic-troubleshooting)** - Added GrumPHP to the list of IC troubleshooting scenarios.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7888--pantheon-docs.my.pantheonfrontend.website/docs/guides/integrated-composer/ic-troubleshooting#grumphp-using-lando-or-other-localdev-commands-breaks-integrated-composer)

**Comment by whitneymeredith** [comment]
@jspellman814 Can you please review this when you get a moment?

**Comment by whitneymeredith** [comment]
Thanks @jspellman814 !

**Comment by wordsmither** [comment]
lgtm

**Pull request merged**
