### PR TITLE
Updating PANTHEON_STRIPPED doc

### PR DESCRIPTION
**Pull request by joshkoenig**
1. Don't tell people to use AJAX to pass utm_params to PHP. That will blow up scalability.
2. Adding proper explanation and proof for how our system actually works.

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Thanks @joshkoenig! Can you take a look at related issue #1355 - is that something we should work into this update?

**Comment by joshkoenig** [comment]
@rachelwhitton I think this is issue #1355... did you mean to link elsewhere?

**Comment by rachelwhitton** [comment]
Yep, sorry about that. It's #1322

**Comment by joshkoenig** [comment]
Thanks! Let's get David's input on it. The current docs are not correct, so my update is good. If we can get more in-depth or a diagram that's good, but we may not need to block on it.

**Comment by rachelwhitton** [comment]
:ship:

**Pull request merged**
