### PR TITLE
Expand availability of SAML to Partners and EDU+ orgs

### PR DESCRIPTION
**Pull request by bmackinney**
@slivermon @ari-gold please take a look. as indicated in #auth-roadmap, changing the link to "contact support" felt wrong.

### CODE REVIEW

**Comment by bmackinney** [comment]
@slivermon can you review?

**Comment by slivermon** [comment]
Is contact support the standard process for setting up SAML SSO? If yes, then the contact support copy is appropriate. If not, then it should very briefly describe the actual process "contact your account executive or open a support ticket."

**Comment by bmackinney** [comment]
@slivermon yes it is the process. Those tickets will be categorized as Product. 

The other change in the doc listed all of the organization service levels SAML is available for. Is it always free or does it cost to add to enterprise/EDU+ orgs?

**Comment by bmackinney** [comment]
Confirmed with sales it's included without charge in standard contracts.

**Comment by bmackinney** [comment]
Holding until internal docs, ticket rule, and training are in place.

**Comment by bmackinney** [comment]
Closed by #1305

**Pull request closed without merging**
