### PR TITLE
Switch CircleCI config from 1.0 to 2.0.

### PR DESCRIPTION
**Pull request by alexfornuto**
Replaces #3433

Description copied from @felicianotech's original PR:

Here's the start of a PR to convert this repo to use CircleCI 2.0. ([background](https://circleci.com/blog/sunsetting-1-0/)).

I'm here to answer any questions if needed, to help continue adding to this PR, or you all can take it from here. Either way.

## Remaining Work
- [x] Test HTML Proofer (break relative link)
- [x] Confirm Speedtest Artifacts (artifacts present but tests don't tripped)
- [x] Confirm A11y breaks when broken (Tests performed, but not tripped)
- [ ] Test Merge Conflict (leave merge conflict separators)

### CODE REVIEW

**Comment by alexfornuto** [comment]
Note the time, first passing build! :fireworks: @felicianotech

**Comment by felicianotech** [comment]
Anything else needed from me on this?

**Comment by alexfornuto** [comment]
@felicianotech I'd like to get some time with you to discuss what else we could/should do in terms of refactoring and/or converting to Docker. Not really a requirement for MVP, but worthwhile to do alongside this work, if we can.

**Comment by felicianotech** [comment]
That's fine but sounds like a separate PR to me.

**Comment by alexfornuto** [comment]
Thanks @felicianotech for all your help getting us here.

**Pull request merged**
