### PR TITLE
[BUGS-3512] Don't upload commit/upload modules/plugins or themes to IC sites

### PR DESCRIPTION
**Pull request by CdrMarks**
## Summary

**[Integrated Composer](https://pantheon.io/docs/integrated-composer)** - Adds an entry to the troubleshooting section letting users know to not upload commit/upload modules/plugins or themes to IC sites.

### Dependencies and Timing

**Release**:
- [X] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by CdrMarks** [comment]
I’ve reviewed the .gitignore files for https://github.com/pantheon-upstreams/drupal-project/blob/master/.gitignore  and https://github.com/pantheon-upstreams/wordpress-project/blob/master/.gitignore.   I'm looking for feedback on what other directories should be added here.

**Comment by namespacebrian** [comment]
Note the `drupal-project` upstream was superseded by the `drupal-recommended` project and `.gitignore` changes were part of the changes:
https://github.com/pantheon-upstreams/drupal-recommended/blob/master/.gitignore

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6992](https://pr-6992--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `61` | `60` | `-1` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6992` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/32815/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/32815/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6992--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by CdrMarks** [comment]
@namespacebrian I found the URL to the repository for Drupal 9 which I see listed at https://pantheon.io/docs/start-state.  
Drupal 9 - e96c6794-77fe-4931-9a20-48a2fe1a3789 -  https://github.com/pantheon-upstreams/drupal-project

Looks like I should have looked at htis one:
Drupal with Composer - 897fdf15-992e-4fa1-beab-89e2b5027e03 - https://github.com/pantheon-upstreams/drupal-recommended

That said...

I'm still  looking for feedback about the list of directories.

**Comment by greg-1-anderson** [comment]
There was a docs PR to change all of the drupal-project's to drupal-recommended; maybe that one was missed.

I think the current list is representative of the upstreams; maybe add some text pointing folks to the actual .gitignore file, and advise them to read it for the exact contents. Perhaps instruct in the use of "git check-ignore" as well? That's only for folks with a local working clone, so idk if it fits well here or not.

The docs team will probably want to split the actual diagram into a Drupal / WordPress tabbed display, but I think the current representation is good for this draft.

**Comment by greg-1-anderson** [comment]
Thinking about this some more, it might also be a good idea to explain the difference between contrib modules and custom modules. I don't know if WordPress has different naming conventions, but in Drupal, "contrib" is something that is published on drupal.org. It is also common for Drupal sites to have a custom module with code / hooks relevant only to the current site. In a composer-managed site, these custom modules are usually committed directly to the repository in a "custom" folder. The Pantheon upstreams therefore .gitignore `modules/contrib` (where Composer places files), but allows you to commit to other directories.

**Comment by greg-1-anderson** [comment]
It looks like WordPress explicitly defines "custom" as a location that can be used for committed plugins, and assumes that "contrib" plugins will be added directly to the plugins / themes directory.

**Comment by CdrMarks** [comment]
This page https://www.drupal.org/docs/understanding-drupal/directory-structure has some language we might lift:
> The directory into which all custom (created by you) and contributed (created by community) modules go.
Splitting this up into the sub-directories contrib and custom can make it easier to keep track of the modules. You can create subfolders for organization to match your development, storage, usage standards.

**Comment by CdrMarks** [comment]
The formatting of the list of files within a tab didn't show as I had hoped.  
https://pr-6992--pantheon-docs.my.pantheonfrontend.website/docs/integrated-composer#changes-lost-when-uploading-or-committing-moduleplugin-or-theme-files

Does anyone had any suggestions for how to get this to show correctly?

**Review by whitneymeredith — COMMENTED** [review]
LGTM

**Pull request merged**
