### PR TITLE
WordPress on Pantheon Quick Start Guide

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes # [DOC-84](https://getpantheon.atlassian.net/browse/DOC-84) and [DOC-306](https://getpantheon.atlassian.net/browse/DOC-306)

## Summary

**[WordPress on Pantheon Guide](https://pantheon.io/docs/guides/wordpress-pantheon/)** - A guide for getting started on Pantheon using a WordPress site as well as information on using WordPress with Composer.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7307](https://pr-7307--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `42` | `51` | `9` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7307` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/36709/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/36709/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7307--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7307--pantheon-docs.my.pantheonfrontend.website/docs/guides/wordpress-pantheon/)

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7307--pantheon-docs.my.pantheonfrontend.website/docs/guides/wordpress-pantheon/)

**Comment by whitneymeredith** [comment]
@EdwardAngert @joa-pan This PR will need two redirects after copy review. 

Launch Check - WordPress Performance and Configuration Analysis 
original: (/wordpress-launch-check)
new:(/guides/wordpress-pantheon/wordpress-launch-check

Pantheon Plugins
original: (/plugins)
new: (/guides/wordpress-pantheon/plugins)

**Review by EdwardAngert — APPROVED** [review]

**Pull request merged**
