### PR TITLE
Updated WP-CFM Command Example and Added CLI Command Example Resources

### LINKED ISSUE #6278: WordPress Configuration Management (WP-CFM) Doc Update
Re: [WordPress Configuration Management (WP-CFM)](https://pantheon.io/docs/wp-cfm)

Priority: Medium

## Issue Description:
User feedback received that some of the commands mentioned as being in the dashboard aren't there any longer. User was unable to deploy from dev to test.

## Suggested Resolution
Review and update doc.

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #6278 

## Summary

**[WordPress Configuration Management (WP-CFM)](https://pantheon.io/docs/wp-cfm)** - I updated the install command example and added links for command differences between different versions of Terminus and links to other command examples.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7039](https://pr-7039--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `51` | `50` | `-1` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-7039` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/33192/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/33192/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7039--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by kporras07** [comment]
Hi,

This doc is talking about a wordpress plugin, not a Terminus plugin so I don't think most of these changes will work unless I'm missing something.

**Comment by whitneymeredith** [comment]
@kporras07 The document states: "Each of the following steps can be done using the Pantheon and WordPress Dashboards or via the command line using Pantheon's CLI, [Terminus](https://pantheon.io/docs/terminus)." Are you saying that Terminus can no longer be used in this way?

**Comment by kporras07** [comment]
It should be able to use it this way. What I'm saying is that the Terminus 2 -> Terminus 3 update should not make any change to this doc. I'd expect it keeps working as usual. If not, then the reason may be a different one and (probably) not this change being proposed in this PR.

**Comment by whitneymeredith** [comment]
@kporras07 Are all the dashboard commands still current?

**Comment by CdrMarks** [comment]
@whitneymeredith if you can ask in 6278 which commands "in the dashboard aren't there any longer", I think it'll help narrow down what needs to be updated.

**Pull request closed without merging**
