### PR TITLE
Update services.yml doc with information about directory permissions

### PR DESCRIPTION
**Pull request by dutton242**
**Note:** Please fill out the PR Template to ensure proper processing.

Closes: #

## Summary

**[Creating a services.yml File for Drupal 8](https://pantheon.io/docs/services-yml)** - Update services.yml documentation with information about changing sites/default directory permissions

## Effect

The following changes are already commited:

- Add information about possibly needing to change directory permissions
- Add external link to site describing how to change directory permissions

## Remaining Work

The following changes still need to be completed:

- [ ] No remaining work

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
Ping @carolyn-shannon as our resident Drupal wizard.

**Comment by alexfornuto** [comment]
@greg-1-anderson Is there a case on Pantheon where a customer would need / want to do this? It seems counter-intuitive to our files vs code webops workflow, but I'd like your opinion please.

**Comment by stevector** [comment]
I'm not sure of the exact circumstances that trigger the need to change permissions. On my local clone of a Drupal 8 site I was able to create a new `services.yml` file because the `default` directory was already set to `755`.

**Comment by dutton242** [comment]
This can occur if you are doing on-server SFTP development and need to add a settings.php file, I've found that sometimes I can't create the file unless the `default` directory is set to world writable first. Then I have to switch it back. This could be Drupal 7 only? I can double check and reply back with my results.

**Comment by dutton242** [comment]
OK, verified that the default permissions for that folder are 755 for Drupal 8 and I also tested a Drupal 7 site and it was set that way too and in both instances I was able to create a file without changing directory permissions. I'm not sure why one of our developers had an issue with this, but I have seen it in the past. We can close this. Thanks!

**Comment by alexfornuto** [comment]
Thanks for the issue @dutton242, even if it ended up closed! I wonder if your developer having issues was trying to work over SFTP while in Git mode?

Reference: https://pantheon.io/docs/sftp#sftp-mode

**Pull request closed without merging**
