### PR TITLE
Add Domains and SSL Tool article

### PR DESCRIPTION
**Pull request by suzannealdrich**
Add Domains and SSL Tool article with overview of base domains, recommended DNS settings, and adding HTTPS for secure communications. Addresses Domains in #423

### CODE REVIEW

**Comment by bmackinney** [comment]
@timani @newtoid  please review.

**Comment by timani** [comment]
+1

**Comment by bmackinney** [comment]
@nataliejeremy ready for editing

**Comment by ari-gold** [comment]
After this gets published what do you think about linking to this doc from other docs that reference adding domains and setting up DNS (like Going Live)?

**Comment by suzannealdrich** [comment]
Yes, and the other articles it is linking to will also get some once-overs from me, at least.

**Pull request merged**
