### PR TITLE
Add detection for drush when redirecting

### LINKED ISSUE #1289: Redirect Incoming Requests Doc Update
Re: [Redirect Incoming Requests](https://pantheon.io/docs/articles/sites/code/redirect-incoming-requests)
## Issue Description:
The provided code snippets doesn't check if the request comes from the cli. In our case we've got the problem that the cron wasn't executed because we redirect every non-https visitor to a https version-

## Suggested Resolution 
Check if the request comes from CLI by wrapping the following condition around the code snippets:
```
if (!(!isset($_SERVER['SERVER_SOFTWARE']) && (php_sapi_name() == 'cli' ||
   (is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0)))) {
   // ...
}
```

The condition was taken from [drupal_is_cli()](https://api.drupal.org/api/drupal/includes!bootstrap.inc/function/drupal_is_cli/7)

### PR DESCRIPTION
**Pull request by slashzero**
closes #1289 Suggested by https://pantheon-systems.desk.com/agent/case/45595

### CODE REVIEW

**Comment by nataliejeremy** [comment]
Thanks @slashzero 
Can you +1 @newtoid

**Comment by nataliejeremy** [comment]
@greg-1-anderson Can you take a look and +1?

**Comment by greg-1-anderson** [comment]
Usually this is done via `if (php_sapi_name() != "cli") {`.  I think this is better to use the general-purpose test consistently in all examples, rather than depending on a Drupal-specific function for Drupal-specific examples.

Speaking of which, there are a lot of other examples in this same file of redirecting via `header` + `exit`.  All of these should be protected with a `php_sapi_name()` check.

**Comment by bmackinney** [comment]
@greg-1-anderson does the snippet at https://github.com/pantheon-systems/documentation/issues/1289 satisfy?

**Comment by greg-1-anderson** [comment]
I don't know that the `argc` check is necessary; seems redundant with the `php_sapi_name()` check. Maybe this is from older versions of PHP? Anyone know of a use-case where `php_sapi_name()` fails, but the `argc` check detects that the cli is being used?

**Comment by greg-1-anderson** [comment]
I added another commit that just calls `php_sapi_name()` directly. This is simplest, and correct. There were a bunch of other places in the docs that referenced different kinds of redirects that used `exit()`; I fixed all of these here as well.

**Pull request merged**
