### PR TITLE
BigPipe update

### PR DESCRIPTION
**Pull request by peter-pantheon**
PR includes the following changes:
- Added Big Pipe to the Unavailable Features section

@greg-1-anderson maybe BigPipe docs should be expanded and/or included under caching in the docs too. thoughts or suggestions?
@rachelwhitton please test
cc @nataliejeremy for copy edit
@ttrowell for review

### CODE REVIEW

**Comment by rachelwhitton** [comment]
@stevector thoughts? Curious because we closed a similar issue on cache tags #1410

**Comment by stevector** [comment]
I think this PR is valuable. We should add a link to https://www.drupal.org/documentation/modules/big_pipe

**Comment by wimleers** [comment]
Related: https://www.drupal.org/documentation/modules/big_pipe/environment

**Comment by stevector** [comment]
Thanks @wimleers! I think our edge layer is the last piece: https://github.com/pantheon-systems/drops-8/issues/146

**Pull request merged**
