### PR TITLE
Darken Image Border

### PR DESCRIPTION
**Pull request by alexfornuto**
Follows #3620 

## Effect
PR includes the following changes:
- Darkens the recently added image border from #dddddd to #b0b0b0

Example:
image

## Docs Team Work
- [ ] Technical Review
- [ ] Copy Review

## Post Launch
- [ ] Update Status Report
- [ ] Archive from **Done** in Waffle

### CODE REVIEW

**Comment by kimby77** [comment]
The border is less distracting when it is the lighter gray - but it's up to you both!

**Comment by rachelwhitton** [comment]
I agree with Kim, lighter border is less distracting. The darker border pulls my focus in the wrong way IMHO 

@allenfear can you decide for us? :)

**Comment by rachelwhitton** [comment]
Discussed with @allenfear, while he agrees with darker - we're deferring to Kim

**Comment by alexfornuto** [comment]
:cry:

**Pull request closed without merging**
