### PR TITLE
[UpdateTool - Terminus Information] Update commands and releases to version 3.0.9.

### PR DESCRIPTION
**Pull request by pantheon-upstream**
[UpdateTool - Terminus Information] Update commands and releases to the latest Terminus version.

### CODE REVIEW

**Comment by wordsmither** [comment]
Closing in favor of https://github.com/pantheon-systems/documentation/pull/7776

**Comment by scottbuscemi** [comment]
@wordsmither #7776 only handles the EOL table. This includes all the information about what is included in this release and changes the manual install version used to 3.0.9

**Comment by wordsmither** [comment]
[Preview](https://pr-7778--pantheon-docs.my.pantheonfrontend.website/docs/terminus)

**Comment by scottbuscemi** [comment]
@wordsmither What's the next step for this?

**Review by greg-1-anderson — APPROVED** [review]

**Comment by wordsmither** [comment]
@scottbuscemi, it's waiting on copy review, which will likely happen today.

**Comment by whitneymeredith** [comment]
LGTM

**Pull request merged**
