### PR TITLE
Sites may break with new composer requirements

### PR DESCRIPTION
**Pull request by jms-pantheon**
## Summary

**[Integrated Composer](https://pantheon.io/docs/guides/integrated-composer)** - New composer behavior on the platform caused sites to break due to required security changes to composer.json. This troubleshooting section attempts to address those issues. 

**Release**:
- [x] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7479](https://pr-7479--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `41` | `51` | `10` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7479` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/39190/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/39190/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7479--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by jms-pantheon** [comment]
One open question on this, should we include the date this went into effect? This began being enforced by Composer starting on July 1st, 2022.

**Comment by namespacebrian** [comment]
> One open question on this, should we include the date this went into effect? This began being enforced by Composer starting on July 1st, 2022.

I was inclined to say yes, but I'm seeing from slack thread that Jordan is wondering if including a date would make the content seem stale, down the road.. 

So someone from docs should probably respond to this question :)

**Review by namespacebrian — APPROVED** [review]
LGTM, with the caveat about maybe it would be nice to specify that composer started enforcing on July 1, 2022

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7479--pantheon-docs.my.pantheonfrontend.website/docs/guides/integrated-composer)

**Comment by jms-pantheon** [comment]
Thanks @whitneymeredith ! Did you have an opinion from the docs side about whether to include the date that this went into effect? Discussed in the comments above

**Comment by whitneymeredith** [comment]
@jms-pantheon I think noting when the new security measure was introduced is useful information for users to have. I'll add it to the content. Thanks!

**Comment by whitneymeredith** [comment]
LGTM

**Pull request merged**
