### PR TITLE
Generalize service error

### PR DESCRIPTION
**Pull request by rachelwhitton**
Related to #3255 

## Effect
PR includes the following changes:
- Make the new troubleshooting section more general, since it's not specific to Composer managed sites. 

cc @greg-1-anderson

### CODE REVIEW

**Comment by alexfornuto** [comment]
+1 for generalization and simplification, for which the ramification is better explanation.

**Comment by greg-1-anderson** [comment]
Yes, that is an improvement, but it should be "the redis module", not "a module".

**Comment by greg-1-anderson** [comment]
@rachelwhitton I was too slow by a minute 😛

**Comment by alexfornuto** [comment]
I think it can stand as is, since the scope of the rest of the guide makes "the module" implicitly refer to Redis for readers of the guide. We then have the benefit of pointing others to this anchor for non-redis instances of the error.

**Pull request merged**
