### PR TITLE
Update installing-redis-on-wordpress.md

### PR DESCRIPTION
**Pull request by mattking5000**
Terminus 0.10.0 update requires WP-CLI commands are in quotes

### CODE REVIEW

**Comment by nataliejeremy** [comment]
Thanks for making the update! @mattking5000

**Comment by nataliejeremy** [comment]
@TeslaDethray Can you confirm if quotes are needed? Thanks.

**Comment by timani** [comment]
Yes quotes are required:

https://github.com/pantheon-systems/cli/issues/773
https://github.com/pantheon-systems/cli/pull/780

**Comment by nataliejeremy** [comment]
Thanks @mattking5000  and @timani

**Pull request merged**
