### PR TITLE
build step update

### LINKED ISSUE #7190: Convert an Empty Upstream Drupal Site to a Composer Managed Site Doc Update
Re: [Convert an Empty Upstream Drupal Site to a Composer Managed Site](https://pantheon.io/docs//guides/composer-convert-from-empty)

Priority: Medium

## Issue Description:
The [Convert an Empty Upstream Drupal Site to a Composer Managed Site](https://pantheon.io/docs/guides/composer-convert-from-empty) doc states,

> “In the pantheon.yml file, the api_version: 1 and build_step: true values are required”. 

However, `api_version: 1` and `build_step: true` are already included in [pantheon.upstream.yml](https://github.com/pantheon-systems/drupal-recommended/blob/default/pantheon.upstream.yml)

Therefore, `api_version: 1` and `build_step: true` are not required in pantheon.yml:

```
api_version: 1
web_docroot: true
# See https://pantheon.io/docs/pantheon-yml/#enforce-https--hsts for valid values.
enforce_https: transitional
php_version: 7.4
database:
 version: 10.4
drush_version: 10
build_step: true
protected_web_paths:
 - /private/
 - /sites/default/files/private/
```

## Suggested Resolution
Removed these two sentences:
Then add build_step: true to pantheon.yml if it is not already included.

In the pantheon.yml file, the api_version: 1 and build_step: true values are required.

### PR DESCRIPTION
**Pull request by joa-pan**
Closes #7190

## Summary

**[Convert an Empty Upstream Drupal Site to a Composer Managed Site](https://pantheon.io/docs/guides/composer-convert-from-empty)** - Updated `build_step` in YAML

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Review by kporras07 — APPROVED** [review]
LGTM

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7240](https://pr-7240--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `43` | `48` | `5` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7240` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/35682/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/35682/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7240--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7240--pantheon-docs.my.pantheonfrontend.website/docs/guides/composer-convert-from-empty)

**Comment by whitneymeredith** [comment]
LGTM

**Pull request merged**
