### PR TITLE
remove unneeded configs

### PR DESCRIPTION
**Pull request by Schnitzel**
see: https://www.drupal.org/project/redis/issues/2904070

### CODE REVIEW

**Comment by alexfornuto** [comment]
Thanks for the contribution @Schnitzel! Can you clarify why this is unneeded?

**Comment by Schnitzel** [comment]
see: https://www.drupal.org/project/redis/issues/2904070#comment-12231700
there  used to be a bug in Drupal where setting `$settings['cache']['default'] = 'cache.backend.redis'` also overwrote the defaults for `$settings['cache']['bins']['bootstrap']`, but according to Berdir this has been fixed.

**Comment by sarahg** [comment]
+1, thanks @Schnitzel! Ready to merge @alexfornuto 🚀

**Comment by alexfornuto** [comment]
Thanks to you both!

**Pull request merged**
