### PR TITLE
Using -a would not commit newly added files

### PR DESCRIPTION
**Pull request by jms-pantheon**
## Summary

Guides for integrations used `git commit -am "message"` which would not commit the newly created files from the prior step in each guide. 

**[Integrate Jira on Pantheon with Quicksilver Hooks](https://pantheon.io/docs/guides/jira)** - Prepended with `git add .` to add untracked files
**[Integrate Pivotal Tracker Project Management Application with a site on Pantheon](https://pantheon.io/docs/guides/pivotal-tracker)** - Same
**[Integrate Trello on Pantheon with Quicksilver Hooks](https://pantheon.io/docs/guides/trello)** - Same

**Release**:
- [ ] When ready

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6766](https://pr-6766--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `53` | `50` | `-3` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6766` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/30529/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/30529/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6766--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by joa-pan** [comment]
'/accept-hack'

**Pull request merged**
