### PR TITLE
Footer Content Addition

### PR DESCRIPTION
**Pull request by barthballard**
Internal linking addition to Docs footer content. Added internal links for 3 primary keyword targets WordPress Hosting, Drupal Hosting, Website Management Platform

Here's what it looks like on my local:

newfooter

@bmackinney please review as this will affect all Docs pages
@informanddelight this is a slight UX change to footer
@rachelwhitton thanks again for your help!

Signed-off-by: barthballard <bballard@gmail.com>

### CODE REVIEW

**Comment by rachelwhitton** [comment]
+1 - Good addition, thanks @barthballard!

**Comment by nataliejeremy** [comment]
@barthballard are those three links? if they aren't links, let's change the color.

**Comment by rachelwhitton** [comment]
[WordPress Hosting](https://pantheon.io/features/wordpress-hosting) | [Drupal Hosting](https://pantheon.io/features/drupal-hosting) | [Website Management Platform](https://pantheon.io/platform/website-management-platform)


@nataliejeremy they are links ^^

**Comment by rachelwhitton** [comment]
For those curious about the inclusion of "hosting" 

@barthballard: [This PR] will be an easy way to propagate some internal links to the new pages. They need some seo love 😉 
@rachelwhitton: GREAT idea. I thought those pages looked new.. 
@barthballard: It's a departure from the "not a hosting company" statement to some degree but was necessary to compete organically

**Comment by informanddelight** [comment]
I would actually prefer the links to be before/on top of the company address. It's an information hierarchy thing, we have a footer that asks if they want to be use our platform/sign up for a free account, then we offer links that offer an navigation to areas of interest, and then we can close with company information/address and the license for the docs.

**Comment by rachelwhitton** [comment]
Updated Screenshot: 
screen shot 2015-07-01 at 11 40 18 am

**Comment by informanddelight** [comment]
Awesome. Looks good to me.
+1 'ing

**Comment by barthballard** [comment]
Looks great! Thanks for the quick feedback everyone.

**Pull request merged**
