### PR TITLE
DOCO-330 Local Development Guide

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes # [DOCO-330](https://getpantheon.atlassian.net/jira/software/c/projects/DOCO/boards/437?modal=detail&selectedIssue=DOCO-330)

## Summary

**[Local Development Guide](https://pantheon.io/docs/guides/local-development)** - Created a new and in-depth guide for Local Development  now that LocalDev is deprecated.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7926--pantheon-docs.my.pantheonfrontend.website/docs/guides/local-development)

**Comment by whitneymeredith** [comment]
Redirects needed:

`| Redirect from                 | to                                 |
|-------------------------------|-------------------------------------|
|` docs/local-development       `|`  docs/guides/local-development      `|
|`  docs/wordpress-phpstorm `|` docs/guides/local-development/wordpress-phpstorm    `|
|` docs/lando-wordpress      `|`docs/guides/local-development/lando-wordpress       `|
|`docs/drupal-phpstorm  `|` docs/guides/local-development/drupal-phpstorm      `|`

`|`docs/cygwin-windows `|` docs/guides/local-development/cygwin-windows      `|`

`|`docs/graphql-requests `|`  docs/guides/local-development/graphql-requests     `|`

`|`docs/continuous-integration `|` docs/guides/local-development/continuous-integration `|`

`|`docs/guides/jenkins  `|`docs/guides/local-development/jenkins       `|`

**Comment by wordsmither** [comment]
lgtm

**Comment by whitneymeredith** [comment]
@karenwithat @pantheon-systems/devreladmin Here's the PR. Thanks in advance for your feedback!

**Pull request merged**
