### PR TITLE
Suggested command to only get the highest tag

### PR DESCRIPTION
**Pull request by solipsist**

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Great addition, thank you @solipsist! Worked like a charm.
Screenshot: 
screen shot 2015-07-23 at 9 15 21 am
Can you update this PR with the following format for the code block? 
screen shot 2015-07-23 at 9 18 47 am

**Comment by solipsist** [comment]
Check now.

**Comment by rachelwhitton** [comment]
Looks great, thanks again for the contribution @solipsist! 

+1

**Comment by solipsist** [comment]
You can even combine step 1 and 2 into:

```
git tag | grep pantheon_live_ | sort -k1.15n | tail -1 | xargs git checkout
```

:)

**Pull request merged**
