### PR TITLE
Change Management: add roles to enterprise org

### LINKED ISSUE #979: Role-Based Permissions update
Re: [Role-Based Permissions 

- [x] Enterprise  needs developer and team member roles.

### PR DESCRIPTION
**Pull request by nataliejeremy**
Closes #979 
@bmackinney or @rachelwhitton  Please review and merge.

### CODE REVIEW

**Comment by bmackinney** [comment]
LGTM. @slivermon please review and +1

**Comment by slivermon** [comment]
We should be clear that all roles can create sites. The Developer role can only work in the Dev and Multidev environments at the site level. 

The Unprivileged role is a user who can be added to an org, but cannot access the org dashboard or any of the org's sites.

**Comment by nataliejeremy** [comment]
Thanks @slivermon I made the updates. 
@bmackinney is this ready to merge?

**Comment by bmackinney** [comment]
@slivermon will give the merge :+1: .
:+1:

**Comment by nataliejeremy** [comment]
@slivermon Can you review the latest and +1 or add comments? Thanks!

**Comment by slivermon** [comment]
+1

**Comment by nataliejeremy** [comment]
Thanks! @slivermon

**Pull request merged**
