### PR TITLE
Quicksilver Guide

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes # [DOC-711](https://getpantheon.atlassian.net/jira/software/projects/DOC/boards/186?selectedIssue=DOC-711)

## Summary

**[Quicksilver Guide](https://pantheon.io/docs/guides/quicksilver)** - Organized existing Quicksilver content into a multi-page guide.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7728--pantheon-docs.my.pantheonfrontend.website/docs/guides/quicksilver)

**Comment by whitneymeredith** [comment]
Redirects needed:

| from | to|
|:--|--:|
| docs/quicksilver | docs/guides/quicksilver|
| docs/guides/trello | docs/guides/quicksilver/trello|
|docs/guides/asana | docs/guides/quicksilver/asana|
|docs/guides/jira | docs/guides/quicksilver/jira|

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7739--pantheon-docs.my.pantheonfrontend.website/docs/logs)

**Comment by wordsmither** [comment]
lgtm

**Comment by EdwardAngert** [comment]
- removed enablement based on slack convo 
- `bash{promptUser: user}` where appropriate
- variety of md fixes

**Pull request merged**
