### PR TITLE
Add solution to divi issues

### PR DESCRIPTION
**Pull request by carl-alberto**
## Summary

**[WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/plugins-known-issues#divi-wordpress-theme--visual-page-builder)** - Documented a solution for the Divi plugin for WordPress slowing down the editor.

## Effect

The following changes are already committed:
- Improve solution in divi

## Post Launch
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5633 | Difference |
| --- | --- | --- | --- |
| Performance Score | `62` | `37` | `-25` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `96` | `-2` |

Lighthouse Audit Reports:

- [`pr-5633` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19826/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19826/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Thanks @carl-alberto! Before we process this, a couple of questions:

1) Is there any better method to fixing this than manually removing the cache over SFTP? Maybe we can offer a cron job script?
2) Is this a know issue to other Divi users, or only those on Pantheon? Have we made the maintainers aware, and/or can we track the reporting of this as a bug to them?

**Comment by alexfornuto** [comment]
Pinged for update.

**Comment by alexfornuto** [comment]
Reached out to @carl-alberto again over slack for answers, but I'll continue processing this as is for now.

**Review by EdwardAngert — APPROVED** [review]

**Pull request merged**
