### PR TITLE
Update text now that "Workflows" tab has been renamed "Database / Files"

### PR DESCRIPTION
**Pull request by bensheldon**
## Effect
PR includes the following changes:
- Renames a heading that implies that the "Workflows" tab is related to workflows

## Remaining Work
- [ ] Discover any other areas that reference the "Workflows" tab

@rachelwhitton please test
cc @nataliejeremy for copy edit

Connects to https://github.com/pantheon-systems/dashboard/pull/1188

### CODE REVIEW

**Comment by nataliejeremy** [comment]
Thanks @bensheldon When will the change take place in the dashboard?

**Comment by bensheldon** [comment]
@nataliejeremy probably won't change the tab name until the end of the week at earliest. I couldn't find any explicit links to the tab in the docs. But I'll dig through some more for language.

**Comment by nataliejeremy** [comment]
@bensheldon No worries, we'll take care of it. I'm sure there are some screenshots that need to be updated too...just want to make sure I sync the merge with your updates.

**Comment by bensheldon** [comment]
@nataliejeremy I'm pushing it through the engineering review process (it's a really simple change). It's basically ready-to-deploy whenever you are ready for it.

**Pull request merged**
