### PR TITLE
managing edu+ update

### LINKED ISSUE #3792: Managing Site Plan Changes and Chargeback for EDU+ Sites Doc Update
Re: [Managing Site Plan Changes and Chargeback for EDU+ Sites](https://pantheon.io/docs/managing-edu-plus/)

Priority: Medium

## Issue Description:
Outdated screenshots and possible stale content wrt to managing plans
## Suggested Resolution
Align with [site plan](https://pantheon.io/docs/site-plan/)

### PR DESCRIPTION
**Pull request by EdwardAngert**
**Note:** Please fill out the PR Template to ensure proper processing.

Closes #3792 

## Effect
PR includes the following changes:
- update Change the Service Level (Org Admin) section (remove screenshot)
- remove `chargebacks` because it's not mentioned in the doc
- you can't have a non-org edu+
- 

### Status Report
[Managing Site Plan Changes for EDU+ Sites](https://pantheon.io/docs/managing-edu-plus): Updated steps and screenshots to reflect current flow, tested sections, and removed Chargebacks from title because it's not in the doc. Removed Change the Service Level (Team Member) section and reopened BUGS-3056 because the billing information is currently not shown to Team Members. [PR 5574](https://github.com/pantheon-systems/documentation/pull/5574)

## Remaining Work
- [x] Confirm if it's possible to have a non-org EDU+ site
- [x] confirm take live instructions and effect
- [ ] Technical review
- [x] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5574 | Difference |
| --- | --- | --- | --- |
| Performance Score | `57.99999999999999` | `44` | `-14` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5574` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18998/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18998/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5574 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `56.00000000000001` | `0` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5574` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19002/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19002/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5574 | Difference |
| --- | --- | --- | --- |
| Performance Score | `60` | `52` | `-8` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5574` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19128/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19128/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5574 | Difference |
| --- | --- | --- | --- |
| Performance Score | `51` | `50` | `-1` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5574` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19132/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19132/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by EdwardAngert** [comment]
commit #0cfd5ed removes instructions for Team Members
and I'm reopening BUGS-2772 since the current Dashboard behavior is to show a "Contact Site Owner" banner which links to the Team modal

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5574 | Difference |
| --- | --- | --- | --- |
| Performance Score | `52` | `42` | `-10` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5574` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19165/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19165/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by EdwardAngert** [comment]
> +1. I did the sort of copy edit that warrants another look from the OP

Thanks, @alexfornuto ! I think a screenshot fits in here, but should fit the EDU+ narrative. Looking at the other, I see it should probably be refreshed as well. I'll grab those and push another commit.

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5574 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.99999999999999` | `43` | `-14` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `96` | `-2` |

Lighthouse Audit Reports:

- [`pr-5574` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19234/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19234/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5574 | Difference |
| --- | --- | --- | --- |
| Performance Score | `48` | `41` | `-7` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `96` | `-2` |

Lighthouse Audit Reports:

- [`pr-5574` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19239/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19239/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Pull request merged**
