### PR TITLE
New doc: Extracting Sites from a Drupal Multisite

### LINKED ISSUE #1036: New Doc Proposal - Unwind a Multisite
## Title
How to Unwind a Multisite

## Description
Would like a document that provides a high level overview for taking a multisite and making them individual sites or unwinding multisite.

## Outline
Don't have an outline, but Kit has some docs he used to unwind a multisite from Aegir

## Expected Audience
Enterprise prospects and partners

## Path
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

### PR DESCRIPTION
**Pull request by nataliejeremy**
Closes #1036 

@timani @hengkit and CSE: Please review and make suggestions to this draft. Thanks!

### CODE REVIEW

**Comment by hengkit** [comment]
```+5. Replace any significant changes in the repo with code from the archive.
```

This was me handwaving... I should probably be more explicit

**Comment by timani** [comment]
@hengkit is the right person for this one. Looks good but I will defer to him.

**Comment by hengkit** [comment]
for step 5 in the single site migration, might be helpful to link to the @ttrowell  blog post https://pantheon.io/blog/expand-use-drush-pantheon-more-commands

**Comment by nataliejeremy** [comment]
@hengkit Can you add some details to this one: 
+5. Replace any significant changes in the repo with code from the archive.
This was me handwaving... I should probably be more explicit

**Comment by nataliejeremy** [comment]
@bmackinney Please review and +1, then I'll merge this one.

**Comment by bmackinney** [comment]
:+1:

**Pull request merged**
