### PR TITLE
ap-auth-pages

### PR DESCRIPTION
**Pull request by carolyn-shannon**
## Summary

**[Autopilot Guide](https://pantheon.io/docs/guides/autopilot)** -  Adds FAQ item regarding testing anonymous vs authenticated page versions.

## Remaining Work

The following changes still need to be completed:

- [ ] Copy review

--------------------------------------------------
## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6616](https://pr-6616--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `65` | `9` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6616` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/29488/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/29488/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6616--pantheon-docs.my.pantheonfrontend.website/docs)

**Review by greg-1-anderson — APPROVED** [review]
LGTM. Should probably also get a +1 from one of @dornamehrkish, @kelly-mcgonnigle or @tylerdigital to make sure it's okay to say "planned for a future release" here.

**Comment by kelly-mcgonnigle** [comment]
Good here! Just one change for grammar -- "Support for authenticated...IS planned" not "are planned"

**Review by joa-pan — APPROVED** [review]
LGTM

**Pull request merged**
