### PR TITLE
Add Media Bulk Upload to Incompatible Modules

### PR DESCRIPTION
**Pull request by dficker**
Added Media Browser Plus, a Drupal 8/9/10 module that is probably incompatible with the platform.

Closes #

## Summary

**[Drupal Modules with Known Issues](https://docs.pantheon.io/modules-known-issues)** - Add Media Bulk Upload to modules with known issues. And add verbage to encourage customers to not even try to work around it, because it doesn't really work.

## Effect

The following changes are already committed:

* There are many tickets in ZenDesk about customers having issues with Media Bulk Upload module, so it likely uses tmp folders in an unsupported way. Though it seems like it may only break on test/live.
* Add it to the list of incompatible modules.

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] Maybe do some testing to verify that it doesn't work?

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by rachelwhitton** [comment]
@ryanshoover do you have anyone on your team that could help provide technical review on this PR?

**Comment by rachelwhitton** [comment]
@lcatlett can you do a technical review on this PR?

**Comment by yuriybabenko** [comment]
I just installed this module on a fresh D10 site and see that the module's configuration allows specifying the filepath ("upload location") to which files will be stored during the upload process. It seems like this can be used to easily get around Pantheon's `/tmp` challenge. 

I'd suggest re-phrasing the wording in the Known Issues list to emphasize _potential_ challenges with out-of-the-box configuration (ie. user doesn't specify an "upload path"), and highlight that a configured "upload path" may be required.

Screenshot 2024-04-18 at 3 59 34 PM

**Comment by rachelwhitton** [comment]
@yuriybabenko what upload location should we recommend for this module?

**Comment by stevector** [comment]
> The description in the module's form suggests this would only be a temporary location in any case, and the module would move the files to the 'proper' location right after upload.

Does that work @yuriybabenko ? Are any customers using either of these modules successfully?

**Comment by yuriybabenko** [comment]
@stevector - I looked at this again and tried it out. The module's configuration page isn't very detailed in terms of what's expected, but the following configuration path for "Upload location" does work on Pantheon: `public://sites/default/files/private`.  Note that the `public://` protocol part is a must - module does not work without it.

**Comment by rachelwhitton** [comment]
@yuriybabenko thanks for passing along these details! I just updated the PR, can you review one last time before I merge?

**Review by yuriybabenko — APPROVED** [review]
Looks great!

**Pull request merged**
