### PR TITLE
Optimize Responsive Menus

### LINKED ISSUE #1665: Optimize Responsive Layout
## Issue Description
Search is not accessible from the toggle menu at mobile widths:
screen shot 2016-06-14 at 9 45 26 am
## Suggested Resolution
Tweak media queries

### PR DESCRIPTION
**Pull request by rachelwhitton**
Closes #1665 

## Effect
PR includes the following changes:
- Responsive menu now provides doc subnav and features; so users can search and navigate to other areas of the docs site.
  **Current**: 
 current-toggle-mobile_320x480
 
  **Suggested**: 
 suggested-toggle-mobile_320x480
 
- Align fonts with pantheon.io 
- Fix 404s for Guides when clicking "Edit this Page" 
- Correct twig logic for contributor lists and optimize taxonomy layouts:
 **Current**: 
 current-taxon-layout
 
 Suggested: 
 suggested-taxon-layout

ping @informanddelight @nataliejeremy @kimby77 @allenfear thoughts? Any concerns or objections? Feedback welcomed, thanks in advance! You can review the changes here: https://docs32-static-docs.pantheonsite.io/docs

### CODE REVIEW

**Comment by kimby77** [comment]
This is much improved! I suggest having an active state on the menu items. So if I am on "guides", and I open the responsive menu, the "guides" list item should be highlighted in some way to show that that's where I currently am.

**Comment by allenfear** [comment]
Agreed, much improved. Thanks Rachel!

**Comment by rachelwhitton** [comment]
Thanks for reviewing @allenfear and @kimby77 ! Updated to show active trail based on current URL: 
screen shot 2016-06-14 at 4 31 11 pm
Preview here: https://docs32-static-docs.pantheonsite.io/docs/

**Comment by nataliejeremy** [comment]
+1 looks great!

**Comment by kimby77** [comment]
What would you think about the yellow as a background color on the menu item?  The border line is still ok for the desktop size, but when it's on the vertical menu here it's almost exactly in between the top and bottom items - so it looks more like a divider and it's a little unclear which item it's associated with.

Like this?
screen shot 2016-06-14 at 2 48 53 pm

**Comment by rachelwhitton** [comment]
@kimby77 Agreed! [Preview](https://docs32-static-docs.pantheonsite.io/docs/). Thoughts?
### Example Doc
screen shot 2016-06-14 at 5 55 34 pm
### Example Guide
screen shot 2016-06-14 at 5 51 00 pm

cc @informanddelight

**Comment by informanddelight** [comment]
That looks good enough. Honestly most people won't be able to :hover
because it's mobile any way...

On Tue, Jun 14, 2016 at 3:57 PM, Rachel <notifications@github.com> wrote:

> @kimby77 <https://github.com/kimby77> Agreed! Preview
> <https://docs32-static-docs.pantheonsite.io/docs/>. Thoughts?
> Example Doc
>
> [image: screen shot 2016-06-14 at 5 55 34 pm]
> <https://cloud.githubusercontent.com/assets/10119525/16062531/441bd656-3259-11e6-9f19-26197fe4868b.png>
> Example Guide
>
> [image: screen shot 2016-06-14 at 5 51 00 pm]
> <https://cloud.githubusercontent.com/assets/10119525/16062530/4418ccfe-3259-11e6-9712-08d85f00c398.png>
>
> cc @informanddelight <https://github.com/informanddelight>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pantheon-systems/documentation/pull/1667#issuecomment-226040989>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA0zh6bj1T1kbL3VkZOqxwGqCKdulL9gks5qLzHigaJpZM4I1dys>
> .
>



-- 
Nathan Lee
User Experience Designer @ Pantheon

**Comment by kimby77** [comment]
Looks great!  The preview link didn't work, btw.  @informanddelight this is for a selected state, not a hover ;)  Though no big deal to keep it on the hover, as you said as it won't be noticeable... though sometimes you do get like a weird hover flickering if you try to select something on mobile menus and it doesn't trigger right away...

**Pull request merged**
