### PR TITLE
Update public docs that discuss Varnish with GCDN

### PR DESCRIPTION
**Pull request by michellecolon-pantheon**
Closes #DOC-464

## Summary

**[Drupal 8 Performance and Global CDN Caching Settings](https://pantheon.io/docs/drupal-8-cache)** - Update verbiage to Global CDN
**[Bypassing Cache with HTTP Headers](https://pantheon.io/docs/cache-control)** - Add support ticket link

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] DOC-483, if any

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6887](https://pr-6887--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `49` | `56.99999999999999` | `8` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6887` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31695/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31695/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6887--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by michellecolon-pantheon** [comment]
@ari-gold Moving this to Copy Review

**Review by joa-pan — APPROVED** [review]
LGTM

**Review by ari-gold — COMMENTED** [review]
Changes here LGTM.

**Pull request merged**
