### PR TITLE
Docs 404 page.

### PR DESCRIPTION
**Pull request by alexfornuto**
## Effect
PR includes the following changes:
- Creates a 404 page for `/docs/`
- MVP Search feature for bad URL

## Remaining Work
- [ ] **Important** - Marketing must create rule to allow `/docs` to provide our own 404 page.
- [ ] Technical review
- [ ] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
Current preview:
image

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5485 | Difference |
| --- | --- | --- | --- |
| Performance Score | `70` | `73` | `3` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5485` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18126/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18126/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5485 | Difference |
| --- | --- | --- | --- |
| Performance Score | `81` | `67` | `-14` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `96` | `-2` |

Lighthouse Audit Reports:

- [`pr-5485` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18133/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18133/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
replaced by #5500

**Pull request closed without merging**
