### PR TITLE
Update external libraries page.

### PR DESCRIPTION
**Pull request by aczietlow**
Closes #

## Summary

**[External Libraries on Pantheon](https://pantheon.io/docs/external-libraries)** - Adding version of external library used on pantheon, to the external library page.

## Effect

To assist in building features to support wkhtmltopdf library, I've added in the exact version of the library Pantheon has installed. Additionally I added a link to more information regarding the qt patch.

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by joa-pan** [comment]
Thank you for your contribution @aczietlow 🥇

**Comment by joa-pan** [comment]
@kporras07 Can you please confirm this is correct?

**Comment by whitneymeredith** [comment]
LGTM

**Comment by aczietlow** [comment]
Thanks folks. Appreciate it. 🎉

**Comment by whitneymeredith** [comment]
Thanks so much for your help, Chris!

**Pull request merged**
