### PR TITLE
Delete add-cloudflare-free-ssl-to-wordpress-sites.md

### PR DESCRIPTION
**Pull request by timani**
We already have this other WP Cloudflare doc, do we still need this one?

https://pantheon.io/docs/guides/ssl-with-cloudflare/

### CODE REVIEW

**Comment by nataliejeremy** [comment]
@bmackinney What do you think?

**Comment by nataliejeremy** [comment]
@bmackinney I agree with Timani. The guide has Drupal and WP info and the WP specific doc isn't really needed.

**Comment by atjuch** [comment]
So sad to see my one of my first docs going to a better place *sniff. Oh
well, more to write! :D

**Comment by ari-gold** [comment]
@rachelwhitton Redirect needed?

**Comment by nataliejeremy** [comment]
@ari-gold I added the redirect.

**Pull request merged**
