### PR TITLE
Sync active tab on fragment identifier

### PR DESCRIPTION
**Pull request by marfillaster**
**Note:** Please fill out the PR Template to ensure proper processing.

Closes: #

## Summary

Set active tab based on fragment identifier

## Example

On **Migrate Existing Sites** [section](https://pr-5883--pantheon-docs.my.pantheonfrontend.website/docs/migrate), default tab is Wordpress.

Navigating by fragment identifiers of Drupal tab using either tab title [`#tab-2-id-id`](https://pr-5883--pantheon-docs.my.pantheonfrontend.website/docs/migrate#tab-2-id-id)  or tab content [`#tab-2-id-tab`](https://pr-5883--pantheon-docs.my.pantheonfrontend.website/docs/migrate#tab-2-id-tab) will set Drupal tab content active.
## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-5883](https://pr-5883--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `64` | `55.00000000000001` | `-9` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `100` | `98` | `-2` |

Lighthouse Audit Reports:

- [`pr-5883` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/22673/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/22673/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-5883--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by carolyn-shannon** [comment]
Great idea! We are actually working on a broader application [CMS selector](https://github.com/pantheon-systems/documentation/pull/5680) that will do this and more. Thanks for the request.

**Comment by marfillaster** [comment]
Hi @carolyn-shannon. PR is actually for any tab and not specific to CMS selection, A better example is the /docs/wordpress-broken-links page tabs: Plugins | Terminus | Quicksilver

**Comment by alexfornuto** [comment]
I think what @marfillaster is doing here is enabling anchor links directly to a specific tab, is that right?

**Comment by carolyn-shannon** [comment]
AH, thanks for the clarification. Yes, that makes sense. We could possibly incorporate this feature request into the header-level anchors PR.

**Comment by carolyn-shannon** [comment]
Feature request for future site enhancement. Closing until we have bandwidth to do it.

**Pull request closed without merging**
