### PR TITLE
DOC-653 Migrate from Competitors

### PR DESCRIPTION
**Pull request by wordsmither**
Closes #DOC-653
 
## Summary

**[Migrate Sites to Pantheon From Other Platforms](https://pantheon.io/docs/migrate-competitors)** - New page listing competitors and what migration doc to use.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7437](https://pr-7437--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `39` | `54` | `15` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7437` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/38541/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/38541/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7437--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by wordsmither** [comment]
[Preview](https://pr-7437--pantheon-docs.my.pantheonfrontend.website/docs/get-started)

**Comment by wordsmither** [comment]
Much of this content is duplicated via partials.  My approach for copy review would be to review [the kinsta guide](https://pr-7437--pantheon-docs.my.pantheonfrontend.website/docs/guides/migrate/kinsta/), as that guide contains both Wordpress and Drupal content.  Then, review the following, as they contain competitor specific content: [Acquia](https://pr-7437--pantheon-docs.my.pantheonfrontend.website/docs/guides/migrate/acquia/prepare) and [WP Engine](https://pr-7437--pantheon-docs.my.pantheonfrontend.website/docs/guides/migrate/wpengine/troubleshooting)

**Comment by whitneymeredith** [comment]
LGTM

**Pull request merged**
