### PR TITLE
LDAP Debug level in testing

### LINKED ISSUE #4630: LDAP test script update
Re: [LDAP and LDAPS](https://pantheon.io/docs/ldap-and-ldaps/)

Priority: Medium

## Issue Description:
Ticket: 132537

To check if there are SSL errors or other issues with the LDAP connection, we can add the debug level here:

`ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);`

Quoting from a customer:

> The problem boiled down to different implementations of SSL. I was using OpenSSL but your environment uses MozNSS. I was using a pem formatted cert containing both private key and the client certificate. For openSSL it was smart enough to figure out it already had the key and cert, but for moznss on pantheon i needed to explicitly specify:

`putenv("LDAPTLS_KEY=$tls_cert");`

## Suggested Resolution

Include the higher debugging level in the test script, and include the putenv functions to include the TLS certs explicitly

### PR DESCRIPTION
**Pull request by alexfornuto**
Closes #4630

## Effect
PR includes the following changes:
- Add debug level to test script.

## Remaining Work
- [ ] Technical review
- [ ] Copy Review

## Post Launch
To be completed by the docs team upon merge: 
- [ ] Update Status Report
- [ ] Archive from **Done** in Waffle

### CODE REVIEW

**Comment by alexfornuto** [comment]
Thanks @eabquina - now we need someone with an LDAP setup to perform a technical review.

**Comment by alexfornuto** [comment]
So I went ahead and set up an LDAP server, and a user to connect to. I tested that my user can connect over the net using `ldapwhoami` locally. Then I added this test script, filled out my credentials, and ran it using `wp eval-file`. The results:

```bash
$ terminus wp $SITE.dev -- eval-file ldap-test.php --skip-wordpress
LDAPTLS_CERT=
LDAPTLS_CACERT=
LDAPTLS_CACERTDIR=
LDAPTLS_REQCERT=

Attempting to connect to ldaps://ldap.$DOMAIN.com:389/ on port 389. 
Connected.
Attempting to bind with rdn cn=wpuser,cn=users,ou=groups,dc=$DOMAIN,dc=com and password XxXxXxX.

Warning: ldap_bind(): Unable to bind to server: Can't contact LDAP server in /srv/bindings/$BINDING/code/ldap-test.php on line 62
Unable to bind - Can't contact LDAP server
```
I've obviously redacted some host-specific information.

**Comment by ttrowell** [comment]
Let's review the $settings array.  `Failure to bind` is usually an issue with the construct of the data in there.

**Comment by alexfornuto** [comment]
I've been unable to configure my own test configuration enough that I can accurately review this change, so I'm going to trust the source and merge. Thanks @eabquina, and thanks @ttrowell for helping me try to test it.

**Pull request merged**
