### PR TITLE
Revise Timeouts article

### PR DESCRIPTION
**Pull request by ari-gold**
* Use Drush for Migrate
* Cleanup

### CODE REVIEW

**Comment by rachelwhitton** [comment]
This is great, thanks @ari-gold!

+1

**Comment by ari-gold** [comment]
Anyone have a suggestion for a more informative description than "PHP won't run forever" for the Nginx fastcgi_read_timeout?

**Comment by newtoid** [comment]
removing false hope +1!

**Comment by ari-gold** [comment]
@nataliejeremy or @rachelwhitton Can you merge?

**Pull request merged**
