### PR TITLE
Update GoAccess documentation

### PR DESCRIPTION
**Pull request by sarahg**
Updates https://pantheon.io/docs/nginx-access-log

## Effect
PR includes the following changes:
Refreshes the GoAccess doc. The existing doc doesn't seem to work with the latest release of GoAccess (seems like a log format issue), and we could provide clearer directions about how to actually run and utilize these reports.

## Remaining Work
- [x] Review/update the automation script
- [x] Technical review (also testing on Windows if possible — no idea if the suggestion to use Cygwin works)
- [x] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5412 | Difference |
| --- | --- | --- | --- |
| Performance Score | `51` | `50` | `-1` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5412` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17287/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17287/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
@sarahg while I hate to be pedantic about this.... I'm lying and I love being pedantic about this!

As [discussed here](https://news.netcraft.com/archives/2018/02/20/nginx-nginx-nginx-or-nginx.html), The server software is usually capitalized as `ningx`, while the enterprise service company uses `NGINX`. I'm inclined to use `nginx`, and/or `Nginx`, since this straddles a line between proper use of language and creative expression and I don't know which side I fall on.

**Comment by sarahg** [comment]
@alexfornuto Good call! Let's go with just nginx then, that seems a little more readable to me, I think. Still a lot of technical content to update here but I'll update the those on my next pass.

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5412 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.99999999999999` | `64` | `7` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5412` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17376/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17376/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5412 | Difference |
| --- | --- | --- | --- |
| Performance Score | `64` | `62` | `-2` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5412` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17379/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17379/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5412 | Difference |
| --- | --- | --- | --- |
| Performance Score | `67` | `54` | `-13` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5412` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17384/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17384/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5412 | Difference |
| --- | --- | --- | --- |
| Performance Score | `62` | `57.99999999999999` | `-4` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5412` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17437/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17437/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5412 | Difference |
| --- | --- | --- | --- |
| Performance Score | `67` | `60` | `-7` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5412` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17452/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17452/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5412 | Difference |
| --- | --- | --- | --- |
| Performance Score | `57.99999999999999` | `52` | `-6` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5412` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17471/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17471/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
> Added troubleshooting section/workaround for Homebrew/MacOS goaccess.conf file not found issue from GetFeedback. Otherwise, looks good except for remaining Windows test w/Cygwin.

I tested in a Windows VM and updated the instructions to suggest the Windows Subsystem for Linux.

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5412 | Difference |
| --- | --- | --- | --- |
| Performance Score | `62` | `56.99999999999999` | `-5` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5412` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17475/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17475/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Thanks @sarahg!

**Pull request merged**
