### PR TITLE
Terminus Drush Install Command Update

### LINKED ISSUE #7580: Using Terminus to Create and Update Drupal Sites on Pantheon Doc Update
Re: [Using Terminus to Create and Update Drupal Sites on Pantheon](https://pantheon.io/docs//guides/terminus-drupal-site-management)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
The terminus site:create command is failing. The site is "created" in that it is listed in the web Dashboard, but site can't be installed (via Drush), or accessed (via Dashboard link).

Drush command fails w/ "Could not resolve hostname appserver.dev.<site-id>.drush.in: Temporary failure in name resolution". Problem has persisted for over an hour, so "temporary" not likely.

## Suggested Resolution
Make the terminus site:create command work.

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #7580 

## Summary

**[Using Terminus to Create and Update Drupal Sites on Pantheon](https://pantheon.io/docs/guides/terminus-drupal-site-management#update-the-code)** - Updated the Terminus Drush steps.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7585](https://pr-7585--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `45` | `48` | `3` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7585` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/40512/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/40512/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7585--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7585--pantheon-docs.my.pantheonfrontend.website/docs/guides/terminus-drupal-site-management#update-the-code)

**Comment by whitneymeredith** [comment]
Matthew Boman's review comments: looks good

**Comment by wordsmither** [comment]
lgtm

**Pull request merged**
