### PR TITLE
Mass Doc Review and Update

### PR DESCRIPTION
**Pull request by alexfornuto**
**Note:** Please fill out the PR Template to ensure proper processing.

Closes DOC-61

## Effect
PR includes the following changes:
- Reviews and Updates docs.

## Remaining Work
- [x] More docs to review and update
- [x] Technical review
- [x] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5509 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.99999999999999` | `51` | `-6` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5509` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18371/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18371/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by EdwardAngert** [comment]
moving this back to tech review to test something out

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5509 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `48` | `-8` |
| Best Practice Score | `86` | `79` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `95` | `-1` |

Lighthouse Audit Reports:

- [`pr-5509` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18533/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18533/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5509 | Difference |
| --- | --- | --- | --- |
| Performance Score | `55.00000000000001` | `57.99999999999999` | `3` |
| Best Practice Score | `86` | `79` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `95` | `-1` |

Lighthouse Audit Reports:

- [`pr-5509` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18534/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18534/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5509 | Difference |
| --- | --- | --- | --- |
| Performance Score | `61` | `47` | `-14` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5509` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18538/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18538/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5509 | Difference |
| --- | --- | --- | --- |
| Performance Score | `50` | `0` | `-50` |
| Best Practice Score | `86` | `0` | `-86` |
| SEO Score | `96` | `0` | `-96` |
| Accessibility Score | `96` | `0` | `-96` |

Lighthouse Audit Reports:

- [`pr-5509` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18571/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18571/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Pull request merged**
