### PR TITLE
[Doc-565] New Object Cache Content and Troubleshooting Scenarios

### LINKED ISSUE #7090: [Doc-565] New Object Cache (Redis) Content and Troubleshooting Steps
Re: [Object Cache (formerly Redis)](https://pantheon.io/docs/object-cache#benefits-of-object-cache)

Priority: High 
## Issue Description
New content on how Object Cache works and benefits needs to be added as well as additional troubleshooting scenarios. See [Doc-565](https://getpantheon.atlassian.net/jira/software/projects/DOC/boards/186?selectedIssue=DOC-565) for more details.
* 

### How will this impact users?

*

### Context

* 

## Suggested Resolution

* 

## Additional Information

*

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #7090 

## Summary

**[Object Cache (formerly Redis)](https://pantheon.io/docs/object-cache#benefits-of-object-cache)** - Added new content to expand information on Object Cache and added new troubleshooting scenarios.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7091](https://pr-7091--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `55.00000000000001` | `60` | `5` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-7091` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/33673/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/33673/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7091--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by jms-pantheon** [comment]
Hi @whitneymeredith I see a lot more good general information was added here, nice! 

I wanted to validate what I was going to say about the ttl, and it turns out that whole section of code is outdated and hasn't applied to the Redis module for at least a year, possibly since Drupal 8? 

I found this issue which led me down a bit of rabbit hole, but it states that the existing readme in the Redis module is inaccurate. 

https://www.drupal.org/project/redis/issues/3209491

**Comment by whitneymeredith** [comment]
@jms-pantheon What changes (if any) do you suggest we make with this in mind?

**Comment by whitneymeredith** [comment]
@jms-pantheon I removed references to TTL. I also updated the No Keys Found section to address [7100](https://github.com/pantheon-systems/documentation/issues/7100)

**Comment by jms-pantheon** [comment]
Thanks @whitneymeredith I've been trying to set aside some time to better address how caching expiration works in the current version, but haven't had a chance to really dig into it. This definitely works for now.

**Comment by whitneymeredith** [comment]
@jms-pantheon Can you review the new Clear Cache with WP Redis section?

**Comment by jms-pantheon** [comment]
I simplified the WP Redis cache clearing section, to my mind the information on grouping caches etc isn't relevant to clearing the cache. I see that information is included as an (optional) section in the installation guide for the WP Redis plugin: https://wordpress.org/plugins/wp-redis/#installation

I did a bit of testing and found the Redis cache is cleared in a few situations, there isn't a way to clear it specifically for just Redis but that makes sense, if someone wanted to do that they could use the above `redis-cli` commands

**Comment by whitneymeredith** [comment]
@jms-pantheon Thanks so much for your work on this!

**Review by jms-pantheon — APPROVED** [review]

**Pull request merged**
