### PR TITLE
Getting Started Training Footer CTA

### PR DESCRIPTION
**Pull request by rachelwhitton**
## Effect
PR includes the following changes:
- Adds a new CTA to the footer to refer traffic to the new getting started training offering

## Remaining Work
- [x] Work with @dgorton to finalize copy
- [x] Get some design input on using the blue and stacking CTAs like this (@kimby77 if you have some bandwidth to weigh in?)
     - Should change the font color to increase contrast for accessibility

### CODE REVIEW

**Comment by kimby77** [comment]
The two footers are confusing because they have equal visual weight, so my attention is not being drawn to one or the other.  Which one is the main one I (as a user) should be paying attention to?  Or can this be redesigned to offer both options in a single footer?

You can use this to check color contrast: http://leaverou.github.io/contrast-ratio/

**Comment by dgorton** [comment]
Fair enough. How about reworking the single block to cover both options?

Something like: 
Personalized Help
Got questions? We have answers!
Our Developer Relations team holds office hours every Wednesday and regular Getting Started with Pantheon sessions. Join us!

And then link Office Hours and Getting Started. Pull the 'More' button.

Better?

**Comment by rachelwhitton** [comment]
+1 @dgorton @kimby77 

But now I'm not sure anchors work best on the background.. suggestions? 

screencapture-docs-local-8000-docs-1516921437757 1

**Comment by dgorton** [comment]
Ugh. Pretty sure blue on yellow is a serious legibility issue. How about just black text with underlines ?
(Taking into account that IANADesigner)
Also - minor nit - let's say "Office Hours" in Title Case (and - yes - I know I'm the culprit as that's what I wrote above)

**Pull request merged**
