### PR TITLE
Temporary Directory Deprecated Configuration Warning

### PR DESCRIPTION
**Pull request by ari-gold**
Add note that you can safely ignore this warning

**Note:** Please fill out the PR Template to ensure proper processing.

Closes #

## Effect
PR includes the following changes:
-
-

## Remaining Work
- [ ] List any outstanding work here
- [ ] Technical review
- [ ] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5376 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `85` | `1` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5376` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16875/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16875/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5376 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `86` | `2` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5376` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16875/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16875/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5376 | Difference |
| --- | --- | --- | --- |
| Performance Score | `83` | `83` | `0` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5376` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16875/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16875/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5376 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `88` | `4` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5376` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16878/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16878/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5376 | Difference |
| --- | --- | --- | --- |
| Performance Score | `78` | `84` | `6` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5376` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16878/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16878/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5376 | Difference |
| --- | --- | --- | --- |
| Performance Score | `85` | `90` | `5` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5376` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16878/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16878/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by carolyn-shannon** [comment]
@ari-gold is this now handled by @greg-1-anderson's latest [pr286](https://github.com/pantheon-systems/drops-8/pull/286#issuecomment-561915708)?

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5376 | Difference |
| --- | --- | --- | --- |
| Performance Score | `83` | `85` | `2` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5376` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16893/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16893/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5376 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `89` | `5` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5376` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16893/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16893/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5376 | Difference |
| --- | --- | --- | --- |
| Performance Score | `83` | `78` | `-5` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5376` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16893/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16893/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by greg-1-anderson** [comment]
> is this now handled by @greg-1-anderson's latest pr286?

Yes, but that won't go out until 8.8.1 in ~ two weeks.

**Pull request merged**
