### PR TITLE
Clarifications on terminus backup:restore

### PR DESCRIPTION
**Pull request by alexfornuto**
Closes: #6137 

## Summary

**[Terminus Command Reference: terminus backup:restore](https://pantheon.io/docs/terminus/commands/backup-restore)** - Added a partial file clarifying that `terminus backup:restore` uses backup files on the platform, not local backup archive files.

## Remaining Work

- [x] Input from @mcohen-impact and/or @umandalroald would be welcome.

## Post Launch

- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by mcohen-impact** [comment]
Hopefully the directions on how to specify WHICH backup you want to restore from will be included on the site

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6162](https://pr-6162--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `60` | `59` | `-1` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `88` | `88` | `0` |

Lighthouse Audit Reports:

- [`pr-6162` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/25219/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/25219/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6162--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by alexfornuto** [comment]
> Hopefully the directions on how to specify WHICH backup you want to restore from will be included on the site

I've changed the partial file to demonstrate the usage with an example. Once the current build process completes, you can see it previewed [here](https://pr-6162--pantheon-docs.my.pantheonfrontend.website/docs/terminus/commands/backup-restore#example)

**Comment by mcohen-impact** [comment]
Great – thanks!




Matt Cohen
Webmaster
MCohen@impactnetworking.com
714-698-4294 Desk


Impact Networking, LLC
2400 East Katella Avenue
Suite 1050
Anaheim, CA 92806

How does your business measure up? Take the Impact Biz Quiz <https://www.impactmybiz.com/bizquiz/?utm_source=direct&utm_medium=email_signature&utm_campaign=all_employees> to help kickstart the process of evaluating the health and efficiency of your business.

<https://www.impactmybiz.com/?utm_source=email&utm_medium=signature&utm_campaign=tagline&utm_content=graphic><https://www.impactmybiz.com/?utm_source=direct&utm_medium=email_signature&utm_campaign=logo&utm_content=all_employees><https://es99.agency/?utm_source=direct&utm_medium=email_signature&utm_campaign=logo&utm_content=all_employees>[cid:impact-ES99_signature_2020_5f81d4f0-4e35-402b-8068-8edc4cbca3bb.gif]<https://www.impactmybiz.com/?utm_source=direct&utm_medium=email_signature&utm_campaign=graphic&utm_content=all_employees>

| Impact<https://www.impactmybiz.com/?utm_source=direct&utm_medium=email_signature&utm_campaign=link&utm_content=all_employees> | ES99<https://es99.agency/?utm_source=direct&utm_medium=email_signature&utm_campaign=link&utm_content=all_employees> |LinkedIn<https://www.linkedin.com/company/impact-networking> | Facebook<https://www.facebook.com/impactmybiz> | Twitter<https://twitter.com/impactmybiz> | Instagram<https://www.instagram.com/impactmybiz/> |

How am I doing? If you would like to provide feedback, please email my manager, Erick Olea at eolea@impactnetworking.com. Your comments are appreciated.

Note: The information contained in this message (and any attachment hereto) is privileged and confidential and protected from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer. Thank you.

**Review by carolyn-shannon — APPROVED** [review]
Good example; clarifies acceptable backups to use and location, and offers copy-able sample code. Nice work. Thanks to @mcohen-impact for suggesting this helpful clarification.

**Pull request merged**
