### PR TITLE
Multi page cache control

### PR DESCRIPTION
**Pull request by jfussion**
## Effect
PR includes the following changes:
- Use an array for patterns to accommodate multiple pages that need to be excluded from being cached.

WP test site: http://dev-joseph-wp-ms.pantheonsite.io/about/
http://dev-joseph-wp-ms.pantheonsite.io/news/

Drupal Test site: http://dev-jts.pantheonsite.io/news/
http://dev-jts.pantheonsite.io/about/

### CODE REVIEW

**Comment by alexfornuto** [comment]
@jfussion who would you suggest for technical review of this?

**Comment by jfussion** [comment]
@alexfornuto requested @twooten and/or @albertcausing for review.

**Comment by twooten** [comment]
@jfussion / @alexfornuto I tested both WordPress and Drupal site URLs provided and it looks good to me.

**Comment by alexfornuto** [comment]
Thanks @twooten!

**Pull request merged**
