### PR TITLE
Override Google CSS for search results; full width

### LINKED ISSUE #1674: Search Result Font Size
Re: [Search Results](https://pantheon.io/docs/search/?term=updates)
## Issue Description
Reported in slack by @ccorpus : 
>It looks smaller and more difficult to read.

Other pages seem fine, issue pertains to search results styling only. 
## Suggested Resolution
Up the font size and override Google stylesheet for result titles (`.gs-result .gs-title, .gs-result .gs-title *`)

### PR DESCRIPTION
**Pull request by rachelwhitton**
Closes #1674 

## Effect
PR includes the following changes:
- Override Google's CSS for font size and family
- Titles are 20px and body text is 16px for consistency 
- Full width search results

## Existing
screen shot 2016-06-23 at 11 01 50 am

## Updated
screen shot 2016-06-23 at 11 07 32 am

ping @kimby77 @informanddelight @nataliejeremy @ccorpus for review
[Preview](https://1674result-static-docs.pantheonsite.io/docs//search/?term=rsync)

### CODE REVIEW

**Comment by informanddelight** [comment]
@rachelwhitton nice job! kinda nitpicky, but can we actually just do `.col-md-8` ? Text expanding across a whole page is actually kinda hard to read. Generally it's good to have no more than 75 characters in a line.

**Comment by kimby77** [comment]
Looks great!!  My comment was said already by @informanddelight :)  +1

**Comment by rachelwhitton** [comment]
Done! [Preview](http://1674result-static-docs.pantheonsite.io/docs/search/?term=rsync)

Thanks for the quick review @informanddelight @kimby77! Should we center results or adjust the left margin?

**Comment by kimby77** [comment]
Yeah, I would add more left margin there so that the results aren't butting up against the edge. Try 50px.  Thanks!

**Comment by rachelwhitton** [comment]
@informanddelight @kimby77 I updated the preview to reflect 50px on the [results](http://1674result-static-docs.pantheonsite.io/docs/search/?term=rsync) as well as other pages (e.g. [doc pages](https://1674result-static-docs.pantheonsite.io/docs/migrate/), [guide pages](https://1674result-static-docs.pantheonsite.io/docs/guides/wordpress-automated-testing/), [changelog](https://1674result-static-docs.pantheonsite.io/docs/changelog/2016/04/), [taxonomy index pages](https://1674result-static-docs.pantheonsite.io/docs/categories/managing/)). Thoughts?

**Comment by kimby77** [comment]
It looks like those links have the results back at full width?

**Comment by rachelwhitton** [comment]
@kimby77 I reverted my changes to add 50px margins to the other pages; it seemed to have a negative impact on the table of contents rendering. Probably best if I scope that work out in a different issue. 

Search results are back to col-md-8 now with suggested margin. Thanks for the review! cc @informanddelight

**Comment by kimby77** [comment]
Cool. Nathan & I were talking about approaches we could take with unifying the docs system, so that we have less small fixes like this in the future (or a clearer path to how they *should* be if something does come up). But I think that would be a separate effort and this is a good immediate improvement! cc @informanddelight

**Pull request merged**
