### PR TITLE
Add 2 awesome graphics

### LINKED ISSUE #760: Add image to Using the Pantheon Workflow to show code moves up, content moves down
Looks like such an image is in a slide deck that was part of the Agency Summit, so just need to track that down https://pbs.twimg.com/media/CKsVL7GUcAAue17.jpg

### PR DESCRIPTION
**Pull request by rachelwhitton**
Closes #760 

@ari-gold @joshkoenig thanks for gathering the images for us - can you review? 
screen shot 2015-07-31 at 12 09 03 pm
screen shot 2015-07-31 at 12 09 26 pm

### CODE REVIEW

**Comment by ari-gold** [comment]
I think this is awesome, just wondering if we should maybe scale the images down a tad? Maybe @informanddelight can weigh in?

**Comment by rachelwhitton** [comment]
Agreed, how about this @ari-gold:

screen shot 2015-07-31 at 12 51 47 pm
screen shot 2015-07-31 at 12 51 57 pm

**Comment by ari-gold** [comment]
LGTM +1

**Comment by informanddelight** [comment]
Looks good! Nice proportions. +1

**Comment by rachelwhitton** [comment]
@ari-gold images resized and inline styling for width removed, good suggestion! thanks!

thanks for the review @informanddelight!

**Comment by joshkoenig** [comment]
Nice work, team! 

:100: :star2:

**Pull request merged**
