### PR TITLE
Update migrate-manual.md

### LINKED ISSUE #2332: Migrate Sites to Pantheon: Manual Method Doc Update
Re: [Migrate Sites to Pantheon: Manual Method](https://pantheon.io/docs/migrate-manual/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Point 8 on step 1, `Click Migrate Manually and select Yes in the confirmation box.`, is confusing. There's no `Migrate Manually` button but a `manually migrated` link. 

## Suggested Resolution 
Change it to `Click the link **manually migrated** and select Yes in the confirm box.

### PR DESCRIPTION
**Pull request by jfussion**
Closes #2332 

## Effect
PR includes the following changes:
- Fixing content of migrate-manual.md

### CODE REVIEW

**Comment by jfussion** [comment]
Wrong numbering.

**Comment by jfussion** [comment]
False alarm. Looks good on preview

**Comment by alexfornuto** [comment]
It looks like this link may not be the same depending on the CMS you choose to migrate:

WordPress: screen shot 2017-04-12 at 6 43 11 pm

D7/8: screen shot 2017-04-12 at 6 44 59 pm

I'll make a PR shortly that includes your commits, and clarifies the discrepancy.

**Comment by alexfornuto** [comment]
Thanks for contributing @jfussion!

**Pull request merged**
