### PR TITLE
Add IPv6 example

### LINKED ISSUE #6743: Advanced Redirects and Restrictions Doc Update
Re: [Advanced Redirects and Restrictions](https://pantheon.io/docs/advanced-redirects)

Priority: Medium

## Issue Description:

The examples for IP blocking on this page include this address as an IP to block:

2001:DB8:1C93

It looks kinda like an IPv6 address, but I don't think it's a valid IPv6 address.

## Suggested Resolution

Find a sample IPv6 address we can put in here that is actually valid and put that in these examples.

### PR DESCRIPTION
**Pull request by joa-pan**
Closes #6743

## Summary

**[Advanced Redirects and Restrictions](https://pantheon.io/docs/advanced-redirects)** - Added an en example IPv6 to doc
## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by joa-pan** [comment]
@dficker can you please review?

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6850](https://pr-6850--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.99999999999999` | `61` | `4` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6850` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31294/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31294/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6850--pantheon-docs.my.pantheonfrontend.website/docs)

**Review by dficker — APPROVED** [review]
It is a valid IPv6 address and looks good to me.

**Comment by joa-pan** [comment]
Thank you @dficker ! You are truly an amazing human! Really appreciate it :)

**Pull request merged**
