### PR TITLE
new crisis response upstream doc

### PR DESCRIPTION
**Pull request by carolyn-shannon**
Closes: #5614 

## Summary

**[Crisis Response Upstream](https://pantheon.io/docs/crisis-response-upstream)** - Creates overview document of the Pantheon Crisis Response WordPress upstream.

## Remaining Work
- [x] Copy Review
- [ ] Sales Engineering Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5615 | Difference |
| --- | --- | --- | --- |
| Performance Score | `57.99999999999999` | `48` | `-10` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5615` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19548/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19548/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5615 | Difference |
| --- | --- | --- | --- |
| Performance Score | `59` | `56.00000000000001` | `-3` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5615` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19549/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19549/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5615 | Difference |
| --- | --- | --- | --- |
| Performance Score | `59` | `49` | `-10` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5615` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19559/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19559/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5615 | Difference |
| --- | --- | --- | --- |
| Performance Score | `57.99999999999999` | `27` | `-31` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5615` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19562/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19562/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5615 | Difference |
| --- | --- | --- | --- |
| Performance Score | `62` | `43` | `-19` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `96` | `-2` |

Lighthouse Audit Reports:

- [`pr-5615` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19566/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19566/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
We're looking into a question about default environment conditions for Test and Live.

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5615 | Difference |
| --- | --- | --- | --- |
| Performance Score | `62` | `51` | `-11` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `96` | `-2` |

Lighthouse Audit Reports:

- [`pr-5615` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19570/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19570/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5615 | Difference |
| --- | --- | --- | --- |
| Performance Score | `55.00000000000001` | `48` | `-7` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5615` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19576/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19576/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Pull request merged**
