### PR TITLE
Update reading-pantheon-environment-configuration.md

### PR DESCRIPTION
**Pull request by ttrowell**
I keep needing to compare these values against what applications are using.  I am proposing that we expose it to clients.  Please review.  @bmackinney @nataliejeremy 
Thanks!

### CODE REVIEW

**Comment by bmackinney** [comment]
I like it. @joshkoenig is this :+1:  to share?

**Comment by joshkoenig** [comment]
In general I support this. However:

1. Let's encourage people to use `$_ENV` rather than `$_SERVER` as that will be around on the CLI too.
2. We should tell people to be cautious about this like they would leaving a stay `phpinfo()` file out there. This contains sensitive data!

**Comment by ttrowell** [comment]
Clarifications and warnings added to the document for review @nataliejeremy .  Thanks!

**Comment by nataliejeremy** [comment]
@joshkoenig Can you take one last look? It's been updated. Thanks!

**Comment by joshkoenig** [comment]
This still uses `$_SERVER`. Change to `$_ENV` and it should be good to go!

**Comment by rachelwhitton** [comment]
Thanks @joshkoenig - can you review c14119d? I replaced `$_SERVER` with `$_ENV` in @ttrowell's contribution as well as throughout the doc.

**Comment by joshkoenig** [comment]
Yup looks good!

**Pull request merged**
