### PR TITLE
Warn not to add redis to personal plan

### PR DESCRIPTION
**Pull request by kevinhowbrook**
Closes #

## Effect
PR includes the following changes:
-
-
-

## Remaining Work
- [ ] List any outstanding todos
- [ ] If needed

RE support ticket/72106 A bold ask, but it can bring your site to a halt

### CODE REVIEW

**Comment by nataliejeremy** [comment]
Thanks for the update! @kevinhowbrook

**Comment by ari-gold** [comment]
Related: https://getpantheon.atlassian.net/browse/BUGS-379

**Comment by kevinhowbrook** [comment]
As I said not a huge issue but I couldn't see why the site was failing. I've noticed now there is a warning on the redis button that says redis is not available if you are on a personal plan... so... this may be moot now anyway.

**Comment by kevinhowbrook** [comment]
Cheers

**Pull request merged**
