### PR TITLE
Make new drupal-8-to-drupal-9-upgrade-guide.

### PR DESCRIPTION
**Pull request by kporras07**
Closes CMS-312

## Summary

**[Upgrade from Drupal 8 with Integrated Composer to Drupal 9](https://pantheon.io/docs/guides/upgrade-drupal-8-ic-to-drupal-9)** - Create new documentation page

**Release**:
- [X] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7123](https://pr-7123--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `56.99999999999999` | `1` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-7123` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/34094/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/34094/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7123--pantheon-docs.my.pantheonfrontend.website/docs)

**Review by whitneymeredith — APPROVED** [review]
LGTM

**Comment by whitneymeredith** [comment]
@pantheon-systems/cms-ecosystem The copy review from the docs perspective is good on this issue. Can you please review the technical steps?

**Review by namespacebrian — APPROVED** [review]
LGTM

**Comment by stovak** [comment]
From a drupal developer perspective, I think the thing I most want to see on these tutorials is a "YOU SHOULD USE THIS TUTORIAL IF YOU MEET THE FOLLOWING CRITERION". Can't tell you how many of these i've gotten halfway through and realized it doesn't apply to me.

**Comment by whitneymeredith** [comment]
@stovak I like that idea a lot. What criteria should be listed for this tutorial? Adding @kporras07 in case he has ideas.

**Comment by namespacebrian** [comment]
Does the "[Will This Guide Work for Your Site?](https://pr-7123--pantheon-docs.my.pantheonfrontend.website/docs/guides/upgrade-drupal-8-ic-to-drupal-9#will-this-guide-work-for-your-site)" section address that?

**Comment by kporras07** [comment]
The only requirement for this guide is being in d8+IC so I think it’s addressed in the section Brian mentioned

**Comment by whitneymeredith** [comment]
@namespacebrian @kporras07  I think the section outlines  what is needed well. I think we could add a sentence to "[Will This Guide Work for Your Site?](https://pr-7123--pantheon-docs.my.pantheonfrontend.website/docs/guides/upgrade-drupal-8-ic-to-drupal-9#will-this-guide-work-for-your-site)" that explicitly says (at the beginning of the doc) that the only requirements are Drupal 8 and Integrated Composer. This would help prevent people getting halfway through, as @stovak mentioned, before they realized that the steps don't apply to them (for example, they're not currently using Integrated Composer).

**Comment by namespacebrian** [comment]
The following pieces of that section ensure their site is using Integrated Composer:
image

The only way for the requirements in the screenshot to be true and the site not use integrated composer is if the customer has done extensive work to remove integrated composer after starting with it.

**Comment by namespacebrian** [comment]
Other mentions of Integrated Composer at the beginning of the guide:

image

**Comment by whitneymeredith** [comment]
@namespacebrian I slightly reworded the Will this guide work for you? paragraph to further clarify the intended audience.

**Comment by namespacebrian** [comment]
@whitneymeredith Looks good.. re-approved 😉 👍

**Comment by whitneymeredith** [comment]
@namespacebrian Thanks! And many thanks to everyone else who took the time to look this over and comment as well!

**Pull request merged**
