### PR TITLE
Pantheon 4 trainers

### PR DESCRIPTION
**Pull request by mcdwayne**
Closes #

## Effect
PR includes the following changes:

This introduces a new guide called 'Using Pantheon As A Training Platform for WordPress and Drupal'
file name is trainers.md 

## Remaining Work
- [x] Finalize writing
- [ ] Copy review

### CODE REVIEW

**Comment by mcdwayne** [comment]
My bad Alex,  There was a bit of miscommunication with the team, so we are not quite ready to publish.  
Steve is taking over the final touches before we re-open this

**Comment by mcdwayne** [comment]
fixed this over google hangout with @stevector should be in a good spot now, still concerned with HTML formatting with the 'example email' section, will be happy to fix again as needed.

**Comment by stevector** [comment]
After talking with @davidneedham this morning, I did a few more copy edits to shorten the doc. Most notably I trimmed the intro paragraphs and put the sample email within a collapsible heading.

He as the tech lead and/or @tessak22 as the product owner of this offering should do one more review of the doc before we pass to Alex.

I'm still a little concerned about the sample email because it mentions topics like Terminus/SFTP/SSH keys not covered elsewhere in the doc. I think we either need to address those topics earlier or not have them in the sample email. @davidneedham, what did you send out before global training day?

**Comment by davidneedham** [comment]
@stevector this is what we sent out to people who signed up for Getting Started with Drupal: https://docs.google.com/document/d/1xB6DYBHOiGxAoaNC8LfmzAjh4n14yfW9Stk7DsOXwYw/edit#bookmark=id.rj5vgk1l7ypl

**Comment by davidneedham** [comment]
Let's nix the sample email and merge that section with the last section. It's better to suggest links that trainers may share with their students, but let's keep that as short as possible. Let's keep in mind that if they signed up for a Pantheon account they're already going to be getting the standard onboarding emails.

**Comment by stevector** [comment]
I've removed that section @davidneedham https://github.com/pantheon-systems/documentation/pull/3503/commits/fcd5b156f9f33d94d55dce748c27dde69eaaec92

**Comment by stevector** [comment]
@tessak22 just commented in Asana that she thinks this is good to go. I'm assigning back over to @alexfornuto

**Pull request merged**
