### PR TITLE
Add categories to landing pages

### PR DESCRIPTION
**Pull request by rachelwhitton**
## Before:
screen shot 2015-05-06 at 4 44 41 pm

## After:
screen shot 2015-05-06 at 4 44 58 pm

@nataliejeremy can you review and merge?

### CODE REVIEW

**Comment by bmackinney** [comment]
Thoughts on removing the word "Tool" from Directory Page titles all or from those that are not tools? (settings)

**Comment by bmackinney** [comment]
@rachelwhitton @nataliejeremy what do you two think about getting rid of the categories? stats in slack.

**Comment by rachelwhitton** [comment]
@bmackinney: +1 for getting rid of categories and +1 for removing the word "Tool" from landing pages.

**Comment by nataliejeremy** [comment]
+1 to both also

**Pull request closed without merging**
