### PR TITLE
Added the --all-tables flag to include the subsites to be search replaced in a WP mu

### PR DESCRIPTION
**Pull request by carl-alberto**
## Effect
PR includes the following changes:
Added the --all-tables flag to include the subsites to be search replaced

## Remaining Work
- [x] Technical review
- [x] Copy Review

## Post Launch
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
@carl-alberto from the [WP-CLI docs](https://developer.wordpress.org/cli/commands/search-replace/):

>[--all-tables]
>Enable replacement on ALL tables in the database, regardless of the prefix, and even if not registered on $wpdb. **Overrides –network** and –all-tables-with-prefix.

I'm thinking that we should remove `--network` if adding `--all-tables`. Do you agree?

**Comment by alexfornuto** [comment]
Reassigned to @carl-alberto who's following up with some tests.

**Comment by carl-alberto** [comment]
@alexfornuto 

> I'm thinking that we should remove --network if adding --all-tables. Do you agree?

Yes! Applicable only for newly migrate WP multisites since the db tables are not yet fully associated with the multisite when imported

**Comment by alexfornuto** [comment]
>Applicable only for newly migrate WP multisites since the db tables are not yet fully associated with the multisite when imported

@carl-alberto I'm not sure I understand this. Should we make a note saying that once the migration is complete, use `--network`, or just `rm` `--network` from this command and call it a day?

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5322 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `81` | `-3` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `97` | `88` | `-9` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5322` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16750/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16750/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by carl-alberto** [comment]
@alexfornuto maybe a note saying that once the migration is complete, they can use the usual `--network` flag to replace `--all-tables` flag

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5322 | Difference |
| --- | --- | --- | --- |
| Performance Score | `83` | `0` | `-83` |
| Best Practice Score | `93` | `0` | `-93` |
| SEO Score | `96` | `0` | `-96` |
| Accessibility Score | `96` | `0` | `-96` |

Lighthouse Audit Reports:

- [`pr-5322` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16853/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16853/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Pull request merged**
