### PR TITLE
1403 Base Domains Product Change

### LINKED ISSUE #1403: Unified Sandbox Domains
Re: Base Domain Product Change - New Doc
## Title
Base Domains
## Issue Description
Document the addition of the `pantheonsite.io` domain to all Pantheon environments
## Suggested Resolution
- [x] Draft new doc within `sites/domains` to document the base domain provided for new sites
 - [x] Cover existing sites using legacy base domains (pantheon.io and gotpantheon.com)
- [x] Identify/Update existing content and code snippets where the `-pantheon.io` base domain is referenced, such as:
 - [Customizing Your Base Domain](https://pantheon.io/docs/articles/organizations/base-domains/)
 - [Enable HTTPS for Sites Using Customized Base Domains](https://pantheon.io/docs/articles/organizations/https-for-sites-using-customized-base-domains/)
 - [Load and Performance Testing](https://pantheon.io/docs/articles/load-and-performance-testing/#verify-varnish-is-working)

### PR DESCRIPTION
**Pull request by rachelwhitton**
Closes #1403 

PR includes the following changes:
- New Doc: [Default Base Domain](http://1403develo-static-docs.pantheon.io/docs/articles/sites/domains/default-base-domain/)
- Replace `pantheon.io` with `pantheonsite.io` within content and code snippets throughout

@bmackinney @slivermon  
cc @nataliejeremy for copy edit

### CODE REVIEW

**Comment by nataliejeremy** [comment]
+1 @rachelwhitton

**Comment by slivermon** [comment]
Language in the product is pretty similar, but slightly different. No mention of the word "base." Do you recommend the product add "base?" https://getpantheon.slack.com/files/jonathanporta/F0PPLJ388/domains-overview.png

**Comment by rachelwhitton** [comment]
@slivermon I think "development domains" would be a better term to use in products and docs. Base domain refers to the root domain - `pantheon.io`, `pantheonsite.io`, `gotpantheon.com` etc. Development domain seems like a better fit to describe the entire environment URL(s). Let me know which way product goes and I'll align the docs in this PR, thanks!

**Comment by rachelwhitton** [comment]
Requires 2 redirects: 

- [Enable HTTPS for Sites Using Customized Base Domains](https://pantheon.io/docs/articles/organizations/https-for-sites-using-customized-base-domains/) to [Enable HTTPS for Sites Using a Custom Vanity Domain](https://pantheon.io/docs/articles/organizations/https-for-sites-using-a-custom-vanity-domain/)

- [Customizing Your Base Domain](https://pantheon.io/docs/articles/organizations/base-domains/) to [Vanity Domains](https://pantheon.io/docs/articles/organizations/vanity-domains)

**Comment by slivermon** [comment]
+1

**Pull request merged**
