### PR TITLE
[CMS-707] Add notes for previous WordPress releases to start-states/wordpress.md

### PR DESCRIPTION
**Pull request by jspellman814**
## Summary

Backfills the new WordPress upstream release notes page with notes from non-core related commits in 2022.

**Release**:
- [x] When ready

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by jspellman814** [comment]
[Preview](https://pr-7335--pantheon-docs.my.pantheonfrontend.website/docs/start-states/wordpress)

**Comment by EdwardAngert** [comment]
nice find on the anchor linking @jspellman814 !

I hadn't seen that one

would we be able to nest those under dated headings as well? that would help break up what might be a very long list. so,

```md
### 20220426

#### <a name="20220426-3"></a>Re-enable WP-Cron for site networks

Pantheon Cron does not support WordPress Site Network installations, also known as...

#### <a name="20220426-2"></a>Add documentation to readme outlining branches

Adds documentation to `README.md` which provides context...
```

I don't know for sure that the table of contents shows H4s, but we might be able to tweak that (or that might be ok?)

otherwise, this is awesome - let me know if/when you want me to merge it into the `upstream-releases` branch

**Comment by jspellman814** [comment]
> nice find on the anchor linking @jspellman814 !
> 
> I hadn't seen that one
> 
> would we be able to nest those under dated headings as well? that would help break up what might be a very long list. so,
> 
> ```lisp
> ### 20220426
> 
> #### <a name="20220426-3"></a>Re-enable WP-Cron for site networks
> 
> Pantheon Cron does not support WordPress Site Network installations, also known as...
> 
> #### <a name="20220426-2"></a>Add documentation to readme outlining branches
> 
> Adds documentation to `README.md` which provides context...
> ```
> 
> I don't know for sure that the table of contents shows H4s, but we might be able to tweak that (or that might be ok?)
> 
> otherwise, this is awesome - let me know if/when you want me to merge it into the `upstream-releases` branch

@EdwardAngert I made this change in the latest commit, [56c37a8](https://github.com/pantheon-systems/documentation/pull/7335/commits/56c37a8aaf85b84f1c69006674ed4180bc1b802d), to see how it'd look. H4s aren't shown in the table of contents, but we can still link directly to each anchor (e.g. https://pr-7335--pantheon-docs.my.pantheonfrontend.website/docs/start-states/wordpress#20220426-1) which seems alright to me.

In regards to adding the dated headings: @namespacebrian and I discussed using a string of numbers for each link in hopes that it'd be less likely to be read as an absolute release date (so they don't look too committal), but I agree with adding a heading for more context (which is helpful if someone ends up on this page _not_ via a direct link from their dashboard). @namespacebrian curious your thoughts on this.

Additionally, if we do decide to use the dated headings, we should consider matching the format of dates elsewhere on the docs site (I'm aware of [release/EOL date table for Terminus](https://pantheon.io/docs/terminus/updates#eol-timeline)).

**Comment by namespacebrian** [comment]
I was advocating specifically for the anchor link URL to be in a `YYYYMMDD` format and my thinking had been that the actual anchor link text could be anything, like so in HTML:
```
<a href="20220426-3">April 26, 2022 - Re-enable WP-Cron for site neworks</a>
```
But maybe that's problematic for how the HTML is constructed from the markdown?

The important thing is that we are able to know what the anchor link URL path is when we make the git commit with the change.. we can't know the commit hash at that time because the commit hash depends on the commit message (chicken/egg), and we can't confidently know the date that the update will appear on dashboards when we make the commit for multiple reasons.  A `YYYYMMDD` string for the date the commit was made seemed like the most straight-forward option.  I'm open to other ideas... we just need to know what it will be when we make the git commit with the change (which is before it's approved).

**Comment by jspellman814** [comment]
@namespacebrian Using a date string for the anchor link makes sense to me. I'm more curious about grouping updates under some sort of heading. In Edward's comment, he demonstrated this using the same date string as the anchor (`### 20220426`), but I feel in this case it'd make more sense to have an actual date (e.g. 04-26-2022) vs the string.

Sticking with date-based anchors is worth moving forward with, IMO. For the headlines, I'd suggest making them the date which the code is released. For example, if a commit is made the day before the PR is merged, the doc would look like this:

### 04-26-2022 Release

#### <a name="20220425-1"></a>Re-enable WP-Cron for site networks

It shouldn't matter if the headline date differs from the anchor date - as long as the anchor matches the commit, it'll link directly to it. And if we want them to match, we have the ability to update the commit message prior to merging the approved PR.

**Comment by jspellman814** [comment]
@EdwardAngert we (cms-ecosystem) discussed this in [Slack yesterday](https://pantheon.slack.com/archives/C024NA0Q1TJ/p1653340816752969), and those who responded are on board with the page structure. Can we get this reviewed by docs and merged into your branch?

**Comment by michellecolon-pantheon** [comment]
> @EdwardAngert we (cms-ecosystem) discussed this in [Slack yesterday](https://pantheon.slack.com/archives/C024NA0Q1TJ/p1653340816752969), and those who responded are on board with the page structure. Can we get this reviewed by docs and merged into your branch?

@jspellman814 Hey! Happy to take a look- are you still thinking of pushing a change that has the date with the dashes?

**Comment by jspellman814** [comment]
@michellecolon-pantheon Yep! I updated in commit [73b7dee](https://github.com/pantheon-systems/documentation/pull/7335/commits/73b7deecbbde8bddaf31ca5490b2ddb5c2f956d0), and you should be able to see the changes [here](https://pr-7335--pantheon-docs.my.pantheonfrontend.website/docs/start-states/wordpress).

**Review by michellecolon-pantheon — COMMENTED** [review]
LGTM

**Pull request merged**
