### PR TITLE
Update the `search_api_pantheon` modules

### LINKED ISSUE #6961: Apache Solr for Drupal: search_api_pantheon version
Re: [Apache Solr for Drupal](https://pantheon.io/docs//guides/solr-drupal/solr-drupal-9)

Priority: Medium

## Issue Description:
Minimum stability error reports when using  `composer require pantheon-systems/search_api_pantheon ^8 --prefer-dist` and drupal/devel:^2.0 in `composer.json`, as Composer will install incompatible `search_api_pantheon` version.

## Suggested Resolution
Per [BUGS-4422](https://getpantheon.atlassian.net/browse/BUGS-4422), modify `search_api_pantheon` to `composer require pantheon-systems/search_api_pantheon:^8@beta`. 

Verify any switches required (ie `--prefer-dist` or `--with-all-dependencies`).

### PR DESCRIPTION
**Pull request by joa-pan**
Closes #6961 

## Summary

**[Apache Solr for Drupal](https://pantheon.io/docs//guides/solr-drupal/solr-drupal-9)** - modify `search_api_pantheon` to `composer require pantheon-systems/search_api_pantheon:^8@beta`. 

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6964](https://pr-6964--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `59` | `60` | `1` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6964` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/32564/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/32564/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6964--pantheon-docs.my.pantheonfrontend.website/docs)

**Review by stovak — APPROVED** [review]
Good work. Thank you for this.

**Comment by whitneymeredith** [comment]
LGTM.

**Review by whitneymeredith — APPROVED** [review]
LGTM

**Pull request merged**
