### PR TITLE
Clarify creating and calling settings.local.php

### PR DESCRIPTION
**Pull request by thomas-thackery**
## Effect
PR includes the following changes:
- Further clarify the file that needs to be created and then included

### CODE REVIEW

**Comment by alexfornuto** [comment]
@thomas-thackery is it not true that there's nothing requiring this file to be called `settings.local.php`? Couldn't a user call it whatever they want, so long as that's reflected in the code snippet?

**Comment by alexfornuto** [comment]
Edited based on discussion with @thomas-thackery, will merge if he's happy with the edits.

**Comment by thomas-thackery** [comment]
+1 and yes the file could be named anything

**Comment by alexfornuto** [comment]
Thanks @thomas-thackery!

**Pull request merged**
