### PR TITLE
Update bots-and-indexing.md

### PR DESCRIPTION
**Pull request by RobHamilton23**
Updates the robots.txt file to include two new user agents added for EDRT-3064

Closes #

## Summary

**[Doc Page Title](https://docs.pantheon.io/doc-title)** - <Enter a one sentence summation of the pertinent changes (including not-yet-completed work) provided by this PR.>

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Thanks for this docs PR @RobHamilton23! 

@conorbauer23 @IngridKwok @stevector should this platform change require a release note?

**Comment by rachelwhitton** [comment]
Following slack discussion, assigning to @conorbauer23 for a release note draft

**Review by rachelwhitton — CHANGES_REQUESTED** [review]
Release note needed

**Review by rachelwhitton — APPROVED** [review]

**Comment by rachelwhitton** [comment]
@IngridKwok new release note has been added to this PR and is ready for final review

**Comment by IngridKwok** [comment]
@rachelwhitton @stevector @conorbauer23  Made a minor change to the text link to improve readability. Good to go.

**Comment by rachelwhitton** [comment]
Reassigning to myself to update date and merge

**Pull request merged**
