### PR TITLE
Dynamic Resources Component

### LINKED ISSUE #5541: New EDT Guide Resources Doc
Re: New EDT Guide Resources doc

Priority: Low

## Issue Description
Create a page for EDT Resource links (pantheon.io/docs/guides/edt/resources). 
Page includes three dynamically-populated elements that change based on ?module=x variable appended to URL:

- GetFeedback link that changes based on module ID (different GetFeedback form for each module)

- Next module signup link that changes based on module ID (different module signup for each module)

- Turn EDT resource links on each page into partials, to be included on page based on module ID in URL string.

### PR DESCRIPTION
**Pull request by alexfornuto**
Closes #5541

## Effect
PR includes the following changes:
- Creates a new component that loads additional resources from Partial files based on URI parameters.
- #5604 Piggy-backed for testing.

## Remaining Work
- [ ] ~Define more resources for expected parameters like GetFeedback ID, EDT course name, etc.~ I think we can contain this all with a single parameter.
- [x] Define content for each module.
- [x] Create a new EDT landing page specifically for dynamic resources.
- [x] Technical review
- [x] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `61` | `54` | `-7` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18959/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18959/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `63` | `39` | `-24` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `96` | `-2` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18963/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18963/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `59` | `0` | `-59` |
| Best Practice Score | `86` | `0` | `-86` |
| SEO Score | `96` | `0` | `-96` |
| Accessibility Score | `96` | `0` | `-96` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18994/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18994/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `49` | `36` | `-13` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19393/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19393/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `49` | `0` | `-49` |
| Best Practice Score | `86` | `0` | `-86` |
| SEO Score | `96` | `0` | `-96` |
| Accessibility Score | `96` | `0` | `-96` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19431/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19431/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `48` | `0` | `-48` |
| Best Practice Score | `86` | `0` | `-86` |
| SEO Score | `96` | `0` | `-96` |
| Accessibility Score | `96` | `0` | `-96` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19435/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19435/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `55.00000000000001` | `56.00000000000001` | `1` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19448/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19448/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `59` | `55.00000000000001` | `-4` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19456/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19456/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `57.99999999999999` | `46` | `-12` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19457/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19457/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `50` | `0` | `-50` |
| Best Practice Score | `86` | `0` | `-86` |
| SEO Score | `96` | `0` | `-96` |
| Accessibility Score | `96` | `0` | `-96` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19468/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19468/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `59` | `61` | `2` |
| Best Practice Score | `86` | `79` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `95` | `-1` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19469/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19469/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `51` | `51` | `0` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19473/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19473/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `54` | `46` | `-8` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19477/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19477/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `60` | `56.00000000000001` | `-4` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19481/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19481/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5571 | Difference |
| --- | --- | --- | --- |
| Performance Score | `59` | `50` | `-9` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5571` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19515/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19515/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
LGTM!

**Comment by davidneedham** [comment]
Hi @alexfornuto ! Where are things at with this? How can I help?

**Pull request merged**
