### PR TITLE
Update redis.md

### PR DESCRIPTION
**Pull request by ccjjmartin**
Closes NA

## Effect
PR includes the following changes:
Redis as of 3.13 supports compressing the cache using the `Redis_CacheCompressed` class.  This saves a whopping 80% of memory on Redis for a small tradeoff on CPU useage.  For large sites this is huge, especially when trying to fight high Redis turnover rates.  I implemented this on one of our large sites on Pantheon and noticed an actual 75% memory reduction.  I hope to increase awareness of this great feature.

Redis Docs: https://www.drupal.org/project/redis/releases/7.x-3.13

## Remaining Work
- [ ] Technical Review
- [ ] Copy Review (if Technical Edits make any copy changes, else ignore)

## Post Launch
To be completed by the docs team upon merge: 
- [ ] Update Status Report
- [ ] Archive from **Done** in Waffle

### CODE REVIEW

**Comment by alexfornuto** [comment]
@ccjjmartin thanks for the contribution! To clarify, were you running the Redis provided by Pantheon, or using an externally hosted Redis?

**Comment by alexfornuto** [comment]
Related: `UNIPAN-18`

**Comment by ccjjmartin** [comment]
@alexfornuto I was running the Redis that is Pantheon hosted.

**Comment by alexfornuto** [comment]
Thanks @ccjjmartin. Is looks like the version `3.13` you're referring to is the version of the Drupal module, not the Redis server itself. That clears up some confusion on my end.

**Comment by ccjjmartin** [comment]
@sarahg Let me know if you think we should include a note somewhere here explaining which Redis class to use based on Redis module version.

I was also thinking that this PR may open up some technical review on the backend / advertising to other Pantheon clients since this great feature would reduce the load on the Redis servers a lot.

**Comment by sarahg** [comment]
This is very cool, thanks for the suggestion @ccjjmartin! I'm a +1 for recommending this setting for D7. The [D8 version](https://www.drupal.org/project/redis/issues/2991121) is still in-progress. 

I think we should note that you need the Redis module version 7.x-3.13 or newer for it work, yes, and maybe add a "Troubleshooting" note for the "class not found" errors you'd see if using this with an older version.

We may also want to recommend setting `cache_compression_size_threshold` when using this, though, since we've seen some cases where using this for all objects can be a performance hit.

Let's also try to get a review from someone in engineering before merging this one. @davidstrauss maybe?

**Comment by alexfornuto** [comment]
Thanks @ccjjmartin, and thanks @sarahg for reviewing!

**Pull request merged**
