### PR TITLE
TypeScript version of pds-toolkit-react

### PR DESCRIPTION
**Pull request by rachelwhitton**
Replaces #9113 

This PR: 
* resets history to ff1c2997efa671b5ea5242a3ed4b2c6b55de0c97 
* sync main
---

## Summary

We have recently updated the PDS toolkit to be compatible with TypeScript. This PR updates to the lastest version and tests that the bundle is working correctly — which it is!

### New tag colors
This update also introduces a few new changes to the Tag component including truncation for long tag names, an [expanded palette of colors (20 total now)](https://live-pds-toolkit-react.appa.pantheon.site/?path=/docs/components-tag--docs#tag-group), and the tags each now have a title attribute included.

**Left**: proposed tag colors [(preview link)](https://pr-9177-documentation.appa.pantheon.site/release-notes/?category=account-management&category=action-required&category=billing&category=deprecated&category=drupal&category=front-end-sites&category=general&category=infrastructure&category=modules&category=new-feature&category=documentation&category=performance&category=plugins&category=policy&category=security&category=tools-apis&category=user-interface&category=wordpress&page=1)  ------- **Right**: current tag colors [(live link)](https://docs.pantheon.io/release-notes/?category=account-management&category=action-required&category=billing&category=deprecated&category=drupal&category=front-end-sites&category=general&category=infrastructure&category=modules&category=new-feature&category=documentation&category=performance&category=plugins&category=policy&category=security&category=tools-apis&category=user-interface&category=wordpress&page=1)

353899018-55cc3a47-df40-465f-a4c8-8d1fc7d89fbd

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Outstanding disucssion blocking merge: 

From @IngridKwok 
> The reddish hues for "Action required" and "Security" are effective and appropriate.
I have concerns regarding the color contrast for the "Deprecated", "User interface" and "WordPress" tags. The dark background combined with the current text color results in insufficient contrast, which may affect readability and accessibility. Defer to Mel for additional comments.

From @mel-miller 
> @IngridKwok -- all of the color combinations are technically accessible (they pass contrast minimums), but if you feel like it doesn't look contrasty enough maybe pick a different color?

**Comment by rachelwhitton** [comment]
Blocked: New error after selecting a category filter, introduced by syncing the main branch. The error is not observed on the [preview environment](https://pr-9177-documentation.appa.pantheon.site/release-notes/1/), it is only observed locally 
Screenshot 2024-08-14 at 3 19 34 PM

Mel has a likely fix and will review with Gus tomorrow

**Comment by rachelwhitton** [comment]
that seems to have fixed the error, but now when i click to filter by category, the popup disappears before i can interact with it. if i click it again, it stays open

https://github.com/user-attachments/assets/30f43954-8b30-4dd7-bf99-58a9dabee8db




reassigning to @gfbollingerHakuna per slack discussion with mel

**Comment by gfbollingerHakuna** [comment]
Hi @rachelwhitton, I couldn't fully reproduce the issue, but I assume the problem occurs when you open the Popover before the data is fully loaded. This might cause the parent to re-render and close the Popover. I added a small snippet to disable the Popover button in the meantime. Let me know what you think and if it works for you. Thanks!

**Comment by rachelwhitton** [comment]
I'm still see the same issue locally, @jazzsequence are you able to reproduce [what I'm seeing? ](https://github.com/pantheon-systems/documentation/pull/9177#issuecomment-2294350574)

**Comment by rachelwhitton** [comment]
I noticed if I interact with the cookie banner before the filter things work fine. But if I do not interact with the cookie banner first, that's when I see the issue

https://github.com/user-attachments/assets/55e7f7c6-4b96-4edb-9f33-2ba86b24aae0

**Comment by jazzsequence** [comment]
I can reproduce the same behavior that @rachelwhitton notes. Specifically:

1. I load the release notes page
2. I click on the filter by category dropdown
3. The cookies banner disappears (without interaction)
4. The filter by category dropdown disappears before I can interact with it

After this, subsequent attempts to use the filter by category dropdown work fine. 

Alternately:

1. I load the release notes page
2. I click accept cookies (or close the banner, or go into cookie settings)
3. The cookies banner disappears
4. The filter by category dropdown works as expected.

This seems like a layer/z-index thing maybe? It seems to only happen when the cookies banner exists (because it's on top). If you interact with the dropdown while the cookies banner is visible, the dropdown cancels the cookies banner out while closing both simultaneously.

**Comment by rachelwhitton** [comment]
@gfbollingerHakuna can you take a look at the recent comments and let us know? cc @mel-miller

**Comment by gfbollingerHakuna** [comment]
Hi @rachelwhitton. First of all, I apologize for the delayed response. I wasn’t receiving GitHub notifications due to a trusted domain issue (I didn't have my pantheon.io email linked with my github account), so I completely missed your comments.

Are you still experiencing the issue? I ran a couple of checks in my local environment and on the staging link provided via GitHub, but I can’t reproduce it now, even though I was able to earlier. Here’s my Loom: https://www.loom.com/share/fd9b15c7af9c4094a7d49c17d1ada29b.

I noticed that the cookies banner is coming from an external script provided by OneTrust. I’m thinking the issue might have been on their end regarding z-index styles, and maybe they’ve fixed it? Let me know your thoughts and if you’re still encountering the bug. I’ll keep an eye on it. Thanks!

**Comment by rachelwhitton** [comment]
@gfbollingerHakuna yes I'm still experiencing this issue when running the docs site locally

**Comment by jazzsequence** [comment]
I am still able to reproduce the issue on `main` described in https://github.com/pantheon-systems/documentation/pull/9177#issuecomment-2316012525

**Comment by jazzsequence** [comment]
I will note as an addendum to ☝️ that I had to actually delete the stored cookies I had in order to reproduce. If you've saved the cookies, the banner doesn't appear, which is the whole issue.

**Pull request merged**
