### PR TITLE
Update modules-plugins-known-issues.md

### PR DESCRIPTION
**Pull request by jahzlariosa**
WPML String Translation - Unable to Generate MO Files

## Effect
PR includes the following changes:
- Lists WPML String Translation error and solutions (Redefine the languages directory or create symlink)

## Remaining Work
- [x] Technical review
- [x] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5372 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `76` | `-8` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `97` | `88` | `-9` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5372` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16799/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16799/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5372 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `87` | `3` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `97` | `88` | `-9` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5372` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16804/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16804/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5372 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `85` | `1` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `97` | `88` | `-9` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5372` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16804/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16804/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5372 | Difference |
| --- | --- | --- | --- |
| Performance Score | `86` | `82` | `-4` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5372` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16849/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16849/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5372 | Difference |
| --- | --- | --- | --- |
| Performance Score | `83` | `79` | `-4` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5372` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16858/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16858/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
@jahzlariosa Thanks! Have either/both of these solutions been used successfully by customers?

**Comment by jahzlariosa** [comment]
> @jahzlariosa Thanks! Have either/both of these solutions been used successfully by customers?

Yes Alex 👍 

Both solutions have been used by customers and confirmed to work.

I also created a test site. "7bc5d4f4-164b-4389-abfc-616d680b3c26"

**Pull request merged**
