### PR TITLE
Wordfence instruction

### PR DESCRIPTION
**Pull request by alexfornuto**
Closes: #5591 

## Summary

**[WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/plugins-known-issues/#wordfence)** - Updated the section on Wordfence with instructions to enable the Wordfence WAF on Pantheon.

Also introduces an SFTP prompt for code blocks.

## Post Launch

- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-5840](https://pr-5840--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `55.00000000000001` | `56.99999999999999` | `2` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-5840` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/22293/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/22293/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-5840--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by carolyn-shannon** [comment]
Wondering if it makes sense to have a separate Wordfence doc; this is rather long and it's a very popular plugin.

**Comment by carolyn-shannon** [comment]
requested TR from @jrastaban

**Comment by jrastaban** [comment]
I noticed the issue about WF's Live Traffic mode creating cookies that break cacheing is no longer listed. Is that no longer an issue?

**Comment by jrastaban** [comment]
https://pr-5840--pantheon-docs.my.pantheonfrontend.website/docs/plugins-known-issues#define-fs_method
WordFence should probably be added to this plugin list.

**Comment by jrastaban** [comment]
step 8's example sftp connection has real user/server information. Obviously doc users don't have the password to this example account but it might create confusion. should it be changed to:
sftp -o Port=2222 Your_Username@Your_Host?

I was surprised that I could SFTP those files while the site was still in git mode. I realized that it was because I was  just making changes in the files folder that is writable. It probably isn't an issue but I felt it seemed odd to have just made SFTP changes and then to be asked to put my site in SFTP mode. Is it worth mentioning why this works or maybe having them enable SFTP before doing any SFTP actions since they will need to anyway? 🤷‍♀️

**Comment by jrastaban** [comment]
This documentation was really easy to follow and well written. I'm excited that we're able to make the firewall work now.
I should probably be ashamed to admit it, but I never used SFTP via cmd line before. I feel like such a power user now.

I enabled their plugin's auto updates to see what it does. Do we need a note about that? I assume if the site was in SFTP mode dev could auto update but test and live wont work since they are read only.

**Comment by alexfornuto** [comment]
>https://pr-5840--pantheon-docs.my.pantheonfrontend.website/docs/plugins-known-issues#define-fs_method
WordFence should probably be added to this plugin list.

Interesting, not sure why tho... I didn't have to define the `fs_method` to get the Wordfence firewall to work.

**Comment by jrastaban** [comment]
> > https://pr-5840--pantheon-docs.my.pantheonfrontend.website/docs/plugins-known-issues#define-fs_method
> > WordFence should probably be added to this plugin list.
> 
> Interesting, not sure why tho... I didn't have to define the `fs_method` to get the Wordfence firewall to work.

I didn't test without it, but step 5 of the Wordfence guide says "Set the FS_METHOD to direct in wp-config.php" and links to that section.

**Comment by alexfornuto** [comment]
Deeeeeeeerp, I missed my own writing.

**Pull request merged**
