### PR TITLE
[DOC-682] Add support for subtitles to landing pages

### PR DESCRIPTION
**Pull request by wordsmither**
Closes #DOC 682

## Summary

**Add support for subtitles to landing pages** - added a new subtitle field for the landings.yaml file.  No subtitles are currently in use, but needed to add blank fields to landings.yaml.  

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7494](https://pr-7494--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `46` | `49` | `3` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7494` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/39450/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/39450/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7494--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by wordsmither** [comment]
[Preview](https://pr-7494--pantheon-docs.my.pantheonfrontend.website/docs/overview)

**Comment by wordsmither** [comment]
these are a few of our landing pages to test and make sure they haven't broken:
https://pr-7494--pantheon-docs.my.pantheonfrontend.website/docs/get-started
https://pr-7494--pantheon-docs.my.pantheonfrontend.website/docs/develop
https://pr-7494--pantheon-docs.my.pantheonfrontend.website/docs/platform

**Comment by whitneymeredith** [comment]
LGTM

**Pull request merged**
