### PR TITLE
Add custom metadata for managed site indexing

### PR DESCRIPTION
**Pull request by kyletaylored**
## Summary

**Add custom meta tags for indexing the site for a datastore**

## Effect

Most of the data contained in the markdown files is structured, but is not exposed in a way easily accessible by crawlers (or exposed at all). This PR adds custom meta tags to the site to expose this data that can then be crawled and extracted in a very clean way. It does not affect any existing tags, nor does it use any standard OpenGraph or other standards that may interfere or be picked up by other crawlers (SEO, search indexers, etc).

image

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by rachelwhitton** [comment]
@kyletaylored this looks great! Do you still have work planned or is this PR ready to merge?

**Comment by kyletaylored** [comment]
I think the only thing I was going to add was a consistent class or ID around only the body content of a doc or guide page (excluding the title header section). Thoughts on that? There doesn't seem to be a consistent implementation, but I could make one.

**Comment by stevector** [comment]
@kyletaylored can you point your config to read the environment for this PR to verify that you're getting the behavior you want? https://pr-8859-documentation.appa.pantheon.site/

**Review by stevector — CHANGES_REQUESTED** [review]
@kyletaylored can you point your config to read the environment for this PR to verify that you're getting the behavior you want? https://pr-8859-documentation.appa.pantheon.site/

**Comment by kyletaylored** [comment]
@stevector The current service is an auto-indexer that makes its own assumptions about the content being indexed (and to repoint we would have to go through the Google search console approval process again). This PR is meant to be used with a custom crawler that has not been written yet, and there is no current plan to do so. 

If we think it's valuable, we can merge as-is. If not or we find it unnecessary until a future date, we can just close this.

**Pull request closed without merging**
