### PR TITLE
Add "Front" Drupal module to known issues list

### LINKED ISSUE #3061: Front Module breaking Cache
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/unsupported-modules-plugins/)

Priority (Low):

## Issue Description:
Caching is not working because of https://www.drupal.org/project/front module

## Suggested Resolution 
Consider if there is some settings required or this is just really conflicting with our Varnish settings

### PR DESCRIPTION
**Pull request by sarahg**
Closes #3061 

## Effect
PR includes the following changes:
- Adds "Front" module to Drupal modules with known issues list.
- Suggests a patch as a possible workaround.

## Remaining Work
- [x] Confirm suggested patch works
- [x] Copy review

### CODE REVIEW

**Comment by alexfornuto** [comment]
@sarahg @eabquina I installed the module to a new site, enabled it and set the permissions for all users, and I'm unable to replicate the problem. Requests over `curl` show that the front page is being cached. Am I missing a step to replicate this problem?

**Comment by sarahg** [comment]
@alexfornuto Try marking the "Front Page Override" box on admin/config/front/settings and setting a special page for anonymous users. 

You can mess with it on the d7front site I spun up yesterday if you'd like: http://dev-d7front.pantheonsite.io

I suppose the text on the doc page should mention that it's only an issue when used for anonymous users, I can edit later today or tomorrow.

**Comment by alexfornuto** [comment]
Understood. I was able to succesfully replicate the issue where anonymous requests where not cached. Unfortunately, the patch did not seem to resolve it for me.

**Comment by alexfornuto** [comment]
👍 Thanks @sarahg!

**Pull request merged**
