### PR TITLE
Guide for Composer in PhpStorm

### PR DESCRIPTION
**Pull request by LukasRos**
This article explains how to use Composer to install extensions for a Drupal 8 site on Pantheon using the Composer integration in JetBrains PhpStorm.

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Thanks @LukasRos! I think we should revise this to work with the existing [GitHub workflow described in another guide](https://pantheon.io/docs/guides/github-pull-requests/) - seems best to standardize our composer workflow for single sites. I'd also like to increase the scope to cover Drupal 7 and WordPress composer workflows 

I should have bandwidth next week to do some revisions 

cc @sukottokun @greg-1-anderson

**Comment by LukasRos** [comment]
Thanks @rachelwhitton, just to clarify, is there any changes you want me to incorporate right now or should I wait for further feedback and revisions from your end?

**Comment by rachelwhitton** [comment]
@LukasRos sorry for the delayed response. This is blocked on our side. I'd like to do a Composer audit first to clean up some stale content #2835, then circle back to this and align for consistency. No action needed on your side at the moment

**Comment by rachelwhitton** [comment]
Dang, I merged this from the command line (13fadc0973fecd84231f5961ab294d0d8ad8b583) but it didn't seem to close the PR as I expected. Your commit is in master, but the PR will show closed instead of merged 😢 

Thanks for the PR! I refactored the page based on revisions to our [existing Composer guide](https://pantheon.io/docs/guides/build-tools/)

**Comment by rachelwhitton** [comment]
FYI @LukasRos @sukottokun New guide is live at https://pantheon.io/docs/guides/phpstorm-composer/

**Pull request closed without merging**
