### PR TITLE
Update unsupported-modules-plugins.md

### PR DESCRIPTION
**Pull request by ttrowell**
This PR adds a possible solution to using Views Data Export.
@timani Please review for @rachelwhitton 
Thanks!

### CODE REVIEW

**Comment by timani** [comment]
I think if we add the note Sheldon put in about using the DB streamwrapper for edge cases with a disclaimer it may/may not impact performance and I think that should do it. 

As is this will take care of 95% of all users but there are about 5% who may need the DB streamwrapper (it is a sandbox project but a report of success)

**Comment by bmackinney** [comment]
@timani do you have the link?

**Comment by timani** [comment]
https://www.drupal.org/sandbox/jim/2352733

**Comment by ari-gold** [comment]
I like adding a Solution section. Should the link to the patch be moved to the solution section? Do we need multiple solutions?

**Comment by bmackinney** [comment]
@timani good enough?

**Comment by timani** [comment]
LGTM

**Pull request merged**
