### PR TITLE
[DOC-4] TOC-cutoff

### PR DESCRIPTION
**Pull request by digitalhydra**
## Effect
PR includes the following changes:
- Fix TOC missing links

### CODE REVIEW

**Comment by alexfornuto** [comment]
@digitalhydra I tested this locally, and no matter how many `0`s I add to `max-height`, it still cuts off the ToC on `modules-plugins-known-issues`.

**Comment by jmolivas** [comment]
@digitalhydra can you attach an image of how this looks in your local machine?

**Comment by digitalhydra** [comment]
Will close this pr to add a new fix

**Comment by alexfornuto** [comment]
Replaced with #5099

**Pull request closed without merging**
