### PR TITLE
Solr Power 0.4.0 - Auto Submission of schema.xml

### PR DESCRIPTION
**Pull request by rachelwhitton**
Align docs with Solr Power 0.4.0

@ataylorme can you review?

### CODE REVIEW

**Comment by pantheon-circleci** [comment]
@rachelwhitton, thanks for your PR! By analyzing the blame information on this pull request, we identified @nataliejeremy to be a potential reviewer

**Comment by ataylorme** [comment]
@rachelwhitton - with this update there is no mention of `schema.xml` at all. I think perhaps we should add a section on it and explain that users can stick with the default or upload a custom file. Maybe even make a note that once they set it up on dev Pantheon will auto-deploy the schema file to other environments.

**Comment by rachelwhitton** [comment]
@ataylorme I added a [new section re: schema.xml](https://solr040-static-docs.pantheonsite.io/docs/wordpress-solr/#schema.xml). Can you review? Thanks again for the help!

**Comment by ataylorme** [comment]
@rachelwhitton Looks good! Thanks for adding that. I think heavy Solr users will want to know how we handle that file.

**Pull request merged**
