### PR TITLE
[SimpleSAML] Change default log handler to errorlog

### LINKED ISSUE #5337: Using SimpleSAMLphp with Shibboleth SSO Doc Update
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso)

Priority: Medium

## Issue Description:

The current documented logging configuration is not recommended on the platform. 

```
$config = array (
     // ...
     'loggingdir' => $_ENV['HOME'] . '/files/private/log/',
     // ... default log handler
     'logging.handler' => 'file',
);
```

While this allows a more persistent and centralised logging, concurrent and high frequency writes anywhere inside the shared high latency `files` directory  is highly discouraged.

There are sites experiencing significant performance issue due to this configuration.

## Suggested Resolution

Use `errorlog` by default as `logging.handler`.

```
$config = array (
     // ...
     'logging.handler' => 'errorlog',
     // ...
);
```

To allow centralised logging, a custom [`SimpleSAML/Logger/LoggingHandlerInterface`](SimpleSAML/Logger/LoggingHandlerInterface) with Database or Redis backing must be implemented by the user.

### PR DESCRIPTION
**Pull request by marfillaster**
Closes #5337 

## Effect
PR includes the following changes:
- Change default configuration of SimpleSAML log handler to errorlog 

## Remaining Work
- [x] Technical review
- [ ] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [x] Update Status Report
- [x] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
@newtoid pinging for technical review.

**Comment by alexfornuto** [comment]
Reached out to @pantheon-systems/professional-services for SME input.

**Comment by alexfornuto** [comment]
From @hengkit:

>pretty sure that if you did that then you’d never see that log again on platform, we don’t give access to system logs (e

@marfillaster have you tested this change and accessed the logs?

**Comment by marfillaster** [comment]
@alexfornuto The change has been applied and tested on an elite site. This PR prevents entire site performance degradation on rare occasions of high write rate on simplesaml log channel. The logs are written in `logs/php-error.log` instead which the customer has access to. 

The tradeoff is the loss of out of the box centralised logging. It also simplifies debugging since the customer only has to inspect one log file for errors.

The customer still has the option to configure and use previous logging strategy.

**Comment by alexfornuto** [comment]
Thanks for the info @marfillaster! Moving on to copy review.

**Comment by alexfornuto** [comment]
Thanks @marfillaster!

**Comment by alexfornuto** [comment]
Resolved in #5367

**Pull request closed without merging**
