### PR TITLE
CMS-407: Update docs

### PR DESCRIPTION
**Pull request by kporras07**
## Summary

Updates drupal-project references to drupal-recommended.

## Effect

- Contextual search and replace drupal9 to drupal-recommended when referring to upstream.
- Contextual search and replace drupal-project to drupal-recommended when referring to upstream.

### Dependencies and Timing

- [x] Merge and deploy PRs in CMS-407

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6878](https://pr-6878--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.99999999999999` | `66` | `9` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6878` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31623/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31623/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6878--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by greg-1-anderson** [comment]
LGTM; this is blocked until the dashboard is updated to create new Drupal 9 sites with drupal-recommended.

**Comment by greg-1-anderson** [comment]
Removed out-of-date script instructions as requested.

**Comment by greg-1-anderson** [comment]
Deployment in progress

**Comment by greg-1-anderson** [comment]
Screenshot from production:

Screen Shot 2021-11-29 at 4 50 35 PM

**Review by joa-pan — APPROVED** [review]
LGTM

**Pull request merged**
