### PR TITLE
Added WordPress themes section with Jupiter theme

### LINKED ISSUE #3435: Add Jupiter theme for unsupported modules
@pantheon-systems/cse
Priority (Low‚ Medium‚ High): Low

## Issue Description:

Jupiter theme displays FTP credentials popup on all environments. Can be hidden vias CSS, but is annoying.

## Suggested Resolution 

As per ticket 100289, add the following to wp-config.php:

```
define('FS_METHOD', 'direct');
define('FS_CHMOD_DIR', ( 0755 & ~ umask() ) );
define('FS_CHMOD_FILE', ( 0755 & ~ umask() ) );
define('FTP_BASE', DIR);
define('FTP_CONTENT_DIR', DIR .'/wp-content/');
define('FTP_PLUGIN_DIR', DIR .'/wp-content/plugins/');
```

### PR DESCRIPTION
**Pull request by slashzero**
Add details of how to disable FTP credentials form when using Jupiter theme.

Closes #3435 

## Effect
PR includes the following changes:
- Add WordPress Themes section
- Add Jupiter FTP credentials issue and resolution

### CODE REVIEW

**Comment by slashzero** [comment]
Wording needs changing - remove 'it's' from 'update it's components'.

**Comment by alexfornuto** [comment]
@slashzero because this is a paid theme I'm unable to test this fix. Can you confirm that it works as instructed?

**Comment by slashzero** [comment]
Confirmed with the client that this fixed the issue.

**Comment by alexfornuto** [comment]
Thanks @slashzero!

**Pull request merged**
