### PR TITLE
[CMS-879] Add 8.2 to php versions table.

### PR DESCRIPTION
**Pull request by kporras07**
## Summary

**[Introduction - PHP](https://pantheon.io/docs/guides/php)** - Add 8.2 to the supported php versions table.

## Effect

The following changes are already committed:

* Link now points to an existing multidev 

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] PHP 8.2 should be released as a stable version (expected December 8th)
- [ ] PHP 8.2 should be globally available in Pantheon (see jira ticket CMS-949)

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by scottbuscemi** [comment]
Please do not merge this yet - PHP 8.2 is not available until CMS-949 is completed.

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7984--pantheon-docs.my.pantheonfrontend.website/docs/guides/php#supported-php-versions)

**Comment by whitneymeredith** [comment]
LGTM @scottbuscemi Please let me know when this can be merged.

**Comment by scottbuscemi** [comment]
We are planning for 12/8 availability

**Pull request merged**
