### PR TITLE
AMP for WP - Mobile Redirection breaks cache

### PR DESCRIPTION
**Pull request by rachelwhitton**
**Note:** Please fill out the PR Template to ensure proper processing.

Closes #

## Effect
PR includes the following changes:
- Add AMP for WP to the list of known problematic plugins, specifically when "Mobile Redirection" is enabled 

## Remaining Work
- [ ] List any outstanding work here
- [ ] Technical review
- [x] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `85` | `1` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16916/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16916/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `83` | `83` | `0` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16916/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16916/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `88` | `4` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16916/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16916/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by rachelwhitton** [comment]
Going to add a code block for handling mobile redirection via wp-config.php - assigning back to me for now. Will commit additional work today

**Comment by rachelwhitton** [comment]
Awaiting feedback on attribution from the contributor, please hold release for now - I'll check in again on Monday

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `74` | `84` | `10` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16967/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16967/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `87` | `3` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16967/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16967/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `86` | `2` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16967/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16967/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `83` | `86` | `3` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16984/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16984/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `86` | `2` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16984/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16984/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `86` | `85` | `-1` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16984/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16984/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by rachelwhitton** [comment]
@alexfornuto no more work planned, unassigning myself - ready for docs processing :)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `70` | `84` | `14` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17046/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17046/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `62` | `80` | `18` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17046/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17046/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5383 | Difference |
| --- | --- | --- | --- |
| Performance Score | `69` | `85` | `16` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5383` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17046/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17046/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Pull request merged**
