### PR TITLE
Replace Google Analytics with GTM

### PR DESCRIPTION
**Pull request by alexfornuto**
Closes DOC-49

## Effect
PR includes the following changes:
- Removes Google Analytics plugin and config
- Adds Google Tag Manager plugin and config

## Remaining Work
- [X] Update CircleCI and Gatsby environment variables with GTM ID
- [x] Determine if GTM tracking should be included in development (currently set to `true` for testing).
- [ ] Technical review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5336 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `43` | `-41` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `87` | `96` | `9` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5336` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16532/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16532/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5336 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `61` | `-23` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `87` | `96` | `9` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5336` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16548/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16548/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5336 | Difference |
| --- | --- | --- | --- |
| Performance Score | `83` | `65` | `-18` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `87` | `96` | `9` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5336` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16555/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16555/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5336 | Difference |
| --- | --- | --- | --- |
| Performance Score | `85` | `48` | `-37` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `87` | `96` | `9` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5336` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16578/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16578/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5336 | Difference |
| --- | --- | --- | --- |
| Performance Score | `75` | `56.00000000000001` | `-19` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `88` | `88` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5336` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16646/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16646/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5336 | Difference |
| --- | --- | --- | --- |
| Performance Score | `84` | `54` | `-30` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5336` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16845/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/16845/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Merging despite performance hit performance hit, which is outside of our control.

**Pull request merged**
