### PR TITLE
Site Networks: Clarify subdirectories vs. subdomains section

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by alexfornuto** [comment]
@danielbachhuber  In the context of this guide, can we consider `slugs` to be a known term for all readers?

**Comment by danielbachhuber** [comment]
@alexfornuto Good question. I don't know for certain but I can't think of another word to use. @rachelwhitton Any suggestions?

**Comment by rachelwhitton** [comment]
I like the term.. but yeah. We need some context around it since it's feels jargon-y

I can add a tooltip. Thoughts?
screen shot 2017-12-08 at 12 46 14 pm

**Comment by rachelwhitton** [comment]
+1

**Pull request merged**
