### PR TITLE
Adding redirection as not counted in the metrics

### PR DESCRIPTION
**Pull request by carl-alberto**
Closes #

## Effect
PR includes the following changes:
- Adding redirection as not counted in the metrics

## Remaining Work
- [ ] List any outstanding work here
- [x] Technical review
- [x] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
Thanks @carl-alberto! Was this determined by testing, or confirmed by someone?

**Comment by carl-alberto** [comment]
@alexfornuto was confirmed by @jfussion from Slack https://pantheon.slack.com/archives/C0ACN422E/p1574470132071200

**Comment by alexfornuto** [comment]
CC @joshkoenig to weigh in before merging.

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5349 | Difference |
| --- | --- | --- | --- |
| Performance Score | `77` | `68` | `-9` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `93` | `-3` |

Lighthouse Audit Reports:

- [`pr-5349` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17547/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17547/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5349 | Difference |
| --- | --- | --- | --- |
| Performance Score | `77` | `82` | `5` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `93` | `-3` |

Lighthouse Audit Reports:

- [`pr-5349` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17548/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17548/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5349 | Difference |
| --- | --- | --- | --- |
| Performance Score | `77` | `79` | `2` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `93` | `-3` |

Lighthouse Audit Reports:

- [`pr-5349` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17549/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17549/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5349 | Difference |
| --- | --- | --- | --- |
| Performance Score | `80` | `77` | `-3` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `93` | `-3` |

Lighthouse Audit Reports:

- [`pr-5349` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17732/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17732/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Pull request merged**
