### PR TITLE
Add google site search v2

### LINKED ISSUE #463: Integrated docs search
https://github.com/andrewshell/blog.andrewshell.org/search?utf8=%E2%9C%93&q=search  is a possible model solution, using Lunr.js. 
Ben mentioned lunr is what github uses.
Pantheon SOLR is also an option, however:
I lack the technical expertise to setup that or a solr index of this site using pantheon.io's solr instance. Therefore, I'm going to re-add Google Site Search (paid) unless I'm convinced something else will be better and completed faster.

### PR DESCRIPTION
**Pull request by bmackinney**
Closes #463 
### Open Questions
1. This is Set up to search `/docs` and `/blog`. Should we search the whole .io site too?
2. I picked the two-page layout. Anyone have a preference for something else? 
image

This needs work, styling-wise, and for testing. @informanddelight, I added you to the team at google CSE, for your styling expertise. 

To complete: 

1. [ ] @informanddelight pick and customize [a theme](https://cse.google.com/cse/lookandfeel/themes?cx=017416971424255486898%3Amoj1j4obfwm) 

1. [x] Fix the css: - it's currently outputting this: 
image

which is remediated by disabling the css in the inspector at default.css (google hosted)

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Updated Screenshot: 
screen shot 2015-04-24 at 3 35 48 pm

It's not perfect, but a good start. We don't have to host the CSS file in place of google, we just need to modify `main.css` and append `!important` at the end of line to ensure it is used over the google CSS style sheet.

**Comment by rachelwhitton** [comment]
I moved the search bar to the right on the nav bar for articles. I can revert this if needed. 

Updated screenshot: 
screen shot 2015-04-24 at 4 40 30 pm

**Comment by nataliejeremy** [comment]
@informanddelight Can you please review and make changes as needed? Thanks!

**Comment by bmackinney** [comment]
@rachelwhitton I think search should remain where it was. It's more prominent there, and our users look for it up there.

**Comment by rachelwhitton** [comment]
Cool - I can easily move it. Thanks for the guidance @bmackinney!

**Comment by rachelwhitton** [comment]
The `gcse` CDE on the panther dashboard contains working custom search engine results, which can be seen on the development URL [http://gsce-panther.pantheon.io/docs/](http://gsce-panther.pantheon.io/docs/)

Try it out @bmackinney 

The problem was our GCSE was sending results to a page that hasn't been created yet, so we couldn't test. Right now, the results are sent to http://gsce-panther.pantheon.io/docs/search - which we would have to change when we launch. 

Obvious CSS help needed. I can work on that tomorrow if needed, @informanddelight any tips would be appreciated!

**Comment by rachelwhitton** [comment]
The `gsce` is currently up to date with this PR - and we should keep it so for easy merge/deploy to production when the time comes. Any commits pushed to `gsce` should also be pushed to this branch.

**Comment by rachelwhitton** [comment]
This PR: 

- Adds Google Custom Search Engine to the docs landing page and navigation bar
- Additional styling has been added to the search results page that outline each result and change based on which result is hovered on with cursor. 
- The search bar in the navigation bar (not shown on docs home page) is now responsive.
- When results are selected, they open in the current window and not a blank target. 
- Font sizes for the search results are customized so they are not blocked
- Container for the results page is set to 12 due to the way adds render on 9 @bmackinney this is the only suggestion that was not incorporated.
- Image results removed 

## Home Page
screen shot 2015-04-28 at 2 38 37 pm

## Navbar on docs
screen shot 2015-04-28 at 2 37 27 pm

## Search Results
screen shot 2015-04-28 at 2 38 03 pm


This is ready for final review

**Comment by rachelwhitton** [comment]
+1

@bmackinney when we deploy, we need to update the URL for the Search results page to https://pantheon.io/docs/search/ in the Custom Search control panel (Set up >> Get Code >> Search Results Details button) Are we ready to :ship:?

## Updated Screenshots:
screen shot 2015-04-28 at 4 49 01 pm
screen shot 2015-04-28 at 4 49 35 pm
screen shot 2015-04-28 at 4 50 01 pm

**Comment by ari-gold** [comment]
Why is the same page listed multiple times in search results (e.g. I see "Mysql Slow Log" listed twice)?

**Comment by rachelwhitton** [comment]
It's three total images @ari-gold so there's some overlap from my screenshots. I'll update the comment, sorry for the confusion!

**Pull request merged**
