### PR TITLE
Role-Based Permissions doc: change role title

### LINKED ISSUE #1400: Role-Based Permissions
Re: [Role-Based Permissions 

The following section is a little confusing: https://pantheon.io/docs/articles/organizations/change-management/#site-level-roles/permissions. 

At the site level, there is no "administrator" or "owner" role as available options to select when adding team members. Screen shot: https://www.evernote.com/l/ANFjTDstgAxG4bKjL6csx9BMC9k4xCJx1S4.

### PR DESCRIPTION
**Pull request by nataliejeremy**
Closes #1400 

## Effect
PR includes the following changes:
Change Site Owner to User In Charge 

@slivermon please review and +1 if you agree with the change.
@rachelwhitton please review/merge after

### CODE REVIEW

**Comment by rachelwhitton** [comment]
+1 LGTM

**Comment by slivermon** [comment]
Can you confirm the language "user in charge" appears in the UI?

**Comment by ari-gold** [comment]
@natalie @ccorpus Talked with Shawn about this issue and we created https://sprint.ly/product/27143/item/1228 to deal with it in the product, so we don't need the doc change.

**Comment by rachelwhitton** [comment]
Thanks @ari-gold!

**Pull request closed without merging**
