### PR TITLE
partials for webops certification iframe embed

### PR DESCRIPTION
**Pull request by pantheonsteve**
Closes #

## Summary

**[Doc Page Title](https://docs.pantheon.io/doc-title)** - <Enter a one sentence summation of the pertinent changes (including not-yet-completed work) provided by this PR.>

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)

### CODE REVIEW

**Comment by stevector** [comment]
I'm going to close https://github.com/pantheon-systems/documentation/pull/8962 and bring over the code changes from that PR necessary to make these functional

**Comment by stevector** [comment]
@pantheonsteve please try embedding these in the LMS and report back if it works well:
* https://pr-8972-documentation.appa.pantheon.site/iframeembeds/certification/what-is-webops
* https://pr-8972-documentation.appa.pantheon.site/iframeembeds/certification/pressure-on-developers
* https://pr-8972-documentation.appa.pantheon.site/iframeembeds/certification/pressure-on-it
* https://pr-8972-documentation.appa.pantheon.site/iframeembeds/certification/what-problems-does-webops-solve
Other than stripping out the header/sidebar/footer, I've done nothing to customize the display on these pages.

**Comment by pantheonsteve** [comment]
@stevector these appear to be working great.

**Comment by stevector** [comment]
@pantheonsteve woo! @rachelwhitton can you review/merge tomorrow?

**Review by rachelwhitton — APPROVED** [review]

**Pull request merged**
