### PR TITLE
Upgrade Build Tools site to Drupal 9 with Integrated Composer

### PR DESCRIPTION
**Pull request by stovak**

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6419](https://pr-6419--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `60` | `56.99999999999999` | `-3` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6419` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/27481/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/27481/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6419--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by stovak** [comment]
Would like @greg-1-anderson to comment before I go much farther filling in details.

**Comment by EdwardAngert** [comment]
working on rebasing this to clean it up

**Comment by wordsmither** [comment]
This has been superseded by [7239](https://github.com/pantheon-systems/documentation/pull/7239)

**Pull request closed without merging**
