### PR TITLE
Create doc: Site Configurations by Plan

### LINKED ISSUE #1030: configurations by plan
Explains
- [ ] how much ram, vars, and other config that would make developers know what they are working with at each plan, with descriptions of what each "thing" is.
- [ ] how developers can get this info from the application.
- [ ] why backups and db don't factor into the ram being used.
- [ ] The difference between Dev/Test and Live, starting at the Business service level.

### PR DESCRIPTION
**Pull request by nataliejeremy**
Closes #1030 
@sukottokun Please review--thx!

### CODE REVIEW

**Comment by nataliejeremy** [comment]
screen shot 2015-11-09 at 10 06 27 am

**Comment by nataliejeremy** [comment]
@sukottokun @timani I updated all the values with what I could find in the .py file. Can you review and add/comment on what else is needed?

**Comment by timani** [comment]
I can speak for the info, if this is from the .py file the settings should be correct. I will leave format to those with more style than me

**Comment by sukottokun** [comment]
Ok, @nataliejeremy thanks for your patience. @timani let me know if you disagree:
1. Take out CPU shares for all, as it isn't really useful.
2. @timani has anyone ever asked about block i/o? Not that I recall. If not, take it out. Same with apc shim.
3. We should add labels: Redis max memory, Memory Limit, etc. And covert to MB where applicable to is isn't "52428800"
4. What about a line for each about what these are?

5. Maybe a sentence or two at the bottom: all components are on isolated containers, not a single shared instance. And see the other pricing page for other config.

**Comment by timani** [comment]
- For #2 I don't think this has come up before so we can omit.
- For #4 having the deets on each config would be useful

**Comment by nataliejeremy** [comment]
#1 and #2: done. @timani Can you please add the descriptions of each or direct me to where I can find that info? Thanks!
screen shot 2015-11-18 at 12 07 10 pm

**Comment by bmackinney** [comment]
Those max memory numbers are huge, are they not? 
If all values are in MB, we should indicate as much. 
I agree with @sukottokun suggestion 4 above

**Comment by nataliejeremy** [comment]
@timani Can you add or send me a description of each?

**Comment by bmackinney** [comment]
Getting close. Redis Max Memories are still extra huge.

**Comment by nataliejeremy** [comment]
@bmackinney @sukottokun @timani @ari-gold 
I added a glossary and FAQ section, and changed redis max memory to MB. There are a few things that I still need help with to get this finished: 
1. What's the difference between Redis Memory Limit and Redis Max Memory?
2. How do developers find this information on the platform?
3. I added two FAQs based on the questions @sukottokun added to this issue. Please comment with the answers. Thanks!

**Comment by ari-gold** [comment]
2. Connect to redis with redis-cli and issue CONFIG GET 
e.g.

```
 $ redis-cli -h 104.130.220.10 -p 11384 -a e7eec646983b4019aa93d89ce52
104.130.220.10:11384> CONFIG GET
(error) ERR Wrong number of arguments for CONFIG GET
104.130.220.10:11384> config get *memory*
1) "maxmemory"
2) "241172480"
3) "maxmemory-samples"
4) "3"
5) "maxmemory-policy"
6) "allkeys-lru"
```

**Comment by nataliejeremy** [comment]
@ari-gold Re: that redis cli command, should most of the command be in brackets since it will be different for each user?

**Comment by ari-gold** [comment]
@nataliejeremy Sure. Maybe also specify how to find the Redis connection string (Site Dashboard >> Env (e.g. Dev) >> Connection info)

**Comment by nataliejeremy** [comment]
@bmackinney @ari-gold @sukottokun @timani 
Just added the section "View Your Site's Specific Configurations".
Please help fill in the blanks so we can deploy this: 
- What is the definition of Redis Memory Limit? Is it different that Redis Max Memory?
- # of Worker Processes for Business and Enterprise. Not found in the .py file.
- The answer for the two FAQs, if needed. Otherwise I can remove them and we can iterate later.

**Comment by nataliejeremy** [comment]
@ari-gold @bmackinney @sukottokun Can you +1 this so I can merge & deploy? Thanks.

**Comment by sukottokun** [comment]
+1 thanks for working on this.

**Comment by nataliejeremy** [comment]
Thanks @sukottokun and @ari-gold for reviewing and helping on this. I'm closing this PR and will reopen another so that it will get auto-deployed.

**Pull request closed without merging**
