### PR TITLE
Linkchecker external check

### PR DESCRIPTION
**Pull request by rachelwhitton**
This PR fixes broken URLs and redirects identified with the following linkchecker command: 
`linkchecker http://localhost:8000/docs --check-extern` which crawls URL's outside of the docs site. 

[f7ef53f](https://github.com/pantheon-systems/documentation/commit/f7ef53f079346d994c5c645c3df8154c98f5a9b0) removes `/` from breadcrumb logic to address broken links generated when rendered. Here's example output [before](https://gist.github.com/rachelwhitton/d6f82589e9b14668cc57) that commit and [after](https://gist.github.com/rachelwhitton/4c72fabc76ecc8617769). This does not affect the look or function of breadcrumbs. 

With external links now being checked, some false positives are generated as a result of timeouts (just a guess..)
**Example:**
```
URL        `https://mariadb.com/kb/en/mariadb/documentation/clients-and-utilities/mysql-client/mysql-command-line-client/'
Name       `MySQL CLI'
Parent URL http://localhost:8000/docs/articles/sites/create/importing-a-large-site, line 190, col 30
Real URL   https://mariadb.com/kb/en/mariadb/documentation/clients-and-utilities/mysql-client/mysql-command-line-client/
Check time 4.471 seconds
Result     Error: ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

Considering the amount of links checked (16566 links in 1622 URLs checked) --- less than 10 false positives is not bad IMO. 

@bmackinney can you review?

### CODE REVIEW

**Comment by ari-gold** [comment]
@rachelwhitton So not sure that's exactly a false positive. Can you try updating the link to https://mariadb.com/kb/en/mariadb/mysql-command-line-client/ and see if that helps?

```
 $ curl -I https://mariadb.com/kb/en/mariadb/documentation/clients-and-utilities/mysql-client/mysql-command-line-client/
HTTP/1.1 301 MOVED PERMANENTLY
Server: nginx/1.1.19
Date: Thu, 09 Jul 2015 20:00:45 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Keep-Alive: timeout=2
Vary: Accept-Language, Cookie
Location: https://mariadb.com/kb/en/mariadb/mysql-command-line-client/
Content-Language: en
X-Frame-Options: SAMEORIGIN
X-Clacks-Overhead: GNU Terry Pratchett
```

**Comment by rachelwhitton** [comment]
```

URL        `https://mariadb.com/kb/en/mariadb/mysql-command-line-client/'
Name       `MySQL CLI'
Parent URL http://localhost:8000/docs/articles/sites/create/importing-a-large-site, line 190, col 30
Real URL   https://mariadb.com/kb/en/mariadb/mysql-command-line-client/
Check time 1.756 seconds
Result     Valid: 200 OK
```

Nice! Thanks @ari-gold! I'll clear out the rest of those and get a hopefully clear output soon

**Comment by rachelwhitton** [comment]
Remaining: 
```
Start checking at 2015-07-10 13:24:32-005

URL        `http://g.recordit.co/vEFYVJq4tM.gif'
Name       `Feature: Editor can post to blog. Behat, Selenium Server running, automating browser'
Parent URL http://localhost:8000/docs/guides/automated-testing-wordpress-behat, line 414, col 4
Real URL   http://g.recordit.co/vEFYVJq4tM.gif
Check time 1.961 seconds
Size       303B
Result     Error: 403 Forbidden

URL        `http://www.wampserver.com/'
Name       `WAMP'
Parent URL http://localhost:8000/docs/articles/local, line 185, col 384
Real URL   http://www.wampserver.com/
Check time 18.163 seconds
Result     Error: ConnectionError: ('Connection aborted.', error(61, 'Connection refused'))

URL        `/article-bounty'
Name       `Write us a tool article and make up to $200'
Parent URL http://localhost:8000/docs/articles/readme, line 178, col 81
Real URL   http://localhost:8000/article-bounty
Check time 2.059 seconds
Result     Error: 404 Not Found

URL        `/article-bounty'
Name       `Write us a guide and make up to $500'
Parent URL http://localhost:8000/docs/articles/readme, line 220, col 64
Real URL   http://localhost:8000/article-bounty
Check time 1.860 seconds
Result     Error: 404 Not Found

URL        `http://g.recordit.co/vEFYVJq4tM.gif'
Name       `Feature: Editor can post to blog. Behat, Selenium Server running, automating browser'
Parent URL http://localhost:8000/docs/guides/automated-testing-wordpress-behat/, line 414, col 4
Real URL   http://g.recordit.co/vEFYVJq4tM.gif
Check time 1.961 seconds
Size       303B
Result     Error: 403 Forbidden

URL        `http://www.yes-www.org/why-use-www/'
Name       `http://www.yes-www.org/why-use-www/'
Parent URL http://localhost:8000/docs/articles/sites/domains/using-pantheon-io-for-better-uptime, line 188, col 238
Real URL   http://www.yes-www.org/why-use-www/
Check time 4.676 seconds
Result     Error: 403 Bad Behavior

URL        `http://www.wampserver.com/'
Name       `WAMP'
Parent URL http://localhost:8000/docs/articles/local/, line 185, col 384
Real URL   http://www.wampserver.com/
Check time 18.163 seconds
Result     Error: ConnectionError: ('Connection aborted.', error(61, 'Connection refused'))

URL        `http://brianmackinney.com'
Parent URL http://localhost:8000/docs/authors/bmackinney, line 161, col 21
Real URL   http://brianmackinney.com
Check time 2.259 seconds
Result     Error: ConnectionError: ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))

Statistics:
Downloaded: 6.00MB.
Content types: 1334 image, 11261 text, 0 video, 0 audio, 4164 application, 0 mail and 3 other.
URL lengths: min=15, max=217, avg=55.

That's it. 16762 links in 1620 URLs checked. 0 warnings found. 8 errors found.
Stopped checking at 2015-07-10 13:29:31-005 (4 minutes, 59 seconds)
```

**Comment by bmackinney** [comment]
:+1:

**Pull request merged**
