### PR TITLE
Pantheon Migration Tool changelog

### PR DESCRIPTION
**Pull request by EdwardAngert**
(Edited by @scottbuscemi )

## Summary

**[Pantheon Migration Tool](https://pantheon.io/guides/pantheon-migration-tool)** - Creates a guide for the Pantheon Migration Tool, which solely houses the changelog for now. Not linked from another docs page yet.

**Release**:
- [x] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6954](https://pr-6954--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `66` | `56.00000000000001` | `-10` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6954` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/32499/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/32499/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6954--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by EdwardAngert** [comment]
[preview](https://pr-6954--pantheon-docs.my.pantheonfrontend.website/docs/guides/pantheon-migration-tool)

**Comment by scottbuscemi** [comment]
Please hold off on merging - ty

**Comment by ari-gold** [comment]
Let's revisit this if/when we get PMT into customer hands.

**Pull request closed without merging**
