### PR TITLE
WebP Expresss AGCDN Image Optimization

### LINKED ISSUE #6696: WebP Express (WP) plugin can use an AGCDN Image Optimization callout
Re: https://pantheon.io/docs/plugins-known-issues

Priority: Medium

## Issue Description
* WebP Express limitation could benefit from AGCDN Image Optimization callout/link.

### How will this impact users?
* It's a popular plugin and users looking to get WebP support out of it won't be able to on our platform.

## Suggested Resolution
* Update the plugin note to link to AGCDN page/docs.

## Additional Information
* Highlighting and linking to Advanced CDN page noting our [Image Optimization] addon has WebP auto-conversion at the edge, and is more performant than a plugin relying on PHP/WP is an appropriate detail.

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #6696 

## Summary

**[WordPress Plugins with Known Issues](https://pantheon.io/docs/plugins-known-issues#webp-express)** - Added  the AGCDN Image Optimization addon as another solution.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7252](https://pr-7252--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `47` | `52` | `5` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7252` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/35824/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/35824/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7252--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7252--pantheon-docs.my.pantheonfrontend.website/docs/plugins-known-issues)

**Review by joa-pan — APPROVED** [review]
@whitneymeredith does this copy edit look okay ?

**Comment by whitneymeredith** [comment]
@joa-pan Looks great!

**Pull request merged**
