### PR TITLE
[UpdateTool - Terminus Information] Update commands and releases.

### PR DESCRIPTION
**Pull request by kporras07**

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6944](https://pr-6944--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `57.99999999999999` | `2` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6944` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/32438/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/32438/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6944--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by kporras07** [comment]
I'm working to automate this with every terminus release. Could someone please take a look and ensure nothing is broken?

I'm conscious that the version updates page has lots of versions that should probably be cleaned up. I'll coordinate that with CMS Ecosystem on early January.

**Comment by EdwardAngert** [comment]
[preview of terminus updates](https://pr-6944--pantheon-docs.my.pantheonfrontend.website/docs/terminus/updates)

**Comment by EdwardAngert** [comment]
@kporras07 it _looks_ like this works in the preview
is there anything else we should try with it or should we try merging it to main and (stage a revert PR and) see what happens again?

**Comment by kporras07** [comment]
Hi @EdwardAngert the official PR is still in the works. Hopefully it will be out today or tomorrow. Now that you tested this (thanks!). Let's close this PR and let's wait for the one that will be (automatically) created soon

**Pull request closed without merging**
