### PR TITLE
Update new-relic.md

### PR DESCRIPTION
**Pull request by bmackinney**
## Remaining Work
- [x] Edit
- [x] approve

Added access rules, activation rules, and better video links

### CODE REVIEW

**Comment by nataliejeremy** [comment]
@sehamilton Can you review Brian's new content? Thanks!

**Comment by rachelwhitton** [comment]
+1

**Comment by sehamilton** [comment]
looks good

**Comment by nataliejeremy** [comment]
Thanks for submitting that @bmackinney

**Pull request merged**
