### PR TITLE
Upstreams other option

### PR DESCRIPTION
**Pull request by jrastaban**
**Note:** Please fill out the PR Template to ensure proper processing.

Closes: #6135

## Summary

**[Create a Custom Upstream](https://pantheon.io/docs/create-custom-upstream)** - Added instruction tabs for setting up custom upstream from other Git hosts like Azure or self-hosted BitBucket.

## We mention supporting 3 git methods: GitHub, Bitbucket or GitLab.

We really support just 2, GitHub & Bitbucket, out of the box and then a large range of other git based providers using a manual setup. The workflow for all these other Git providers is very similar to what we have now for GitLab. It involves creating a user account that gives pantheon access to it, and then contacting support to set it up. The URL validator for creating custom upstreams only accepts GitHub, Bitbucket but we can use just about anything using Git, it just needs a person to validate it.

**Expand the Git-based repository support definition here to include a wide range of other Git based providers.**

## Remaining Work
Review:
- [x] I'm sure the wording could be improved
- [ ] Should we provide less detail and jut say contact support or try and give some direction?

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6163](https://pr-6163--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `61` | `69` | `8` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `88` | `88` | `0` |

Lighthouse Audit Reports:

- [`pr-6163` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/25245/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/25245/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6163--pantheon-docs.my.pantheonfrontend.website/docs)

**Review by alexfornuto — APPROVED** [review]
Thanks @jrastaban! I'm reaching out to @pantheon-systems/cse-admins to get their input on the scope of support for other repo hosts.

**Comment by alexfornuto** [comment]
Waiting now on confirmation of SoS expectation from CSE leadership. Otherwise it's ready to :shipit:.

**Comment by alexfornuto** [comment]
CSE is :+1:, but I'm also gonna get feedback from Product before we push documentation that implicitly supports `*` Git host for Custom Upstreams.

**Pull request merged**
