### PR TITLE
Update core-updates.md

### PR DESCRIPTION
**Pull request by cityofoaksdesign**
## Effect
PR includes the following changes:
- Note that sites managing core with Composer are not compatible with One-click updates in the Site Dashboard

### CODE REVIEW

**Comment by alexfornuto** [comment]
Thanks @cityofoaksdesign! We're going to revisit this after finishing #3598, to review the copy and possible link to that guide and/or [Manage Some Dependencies with Composer](https://pantheon.io/docs/guides/partial-composer/).

**Comment by rachelwhitton** [comment]
I'm refactoring lots of Composer content at the moment, perfect timing! Thanks for the suggestion! Will review this week

**Comment by rachelwhitton** [comment]
@cityofoaksdesign we'd like to attribute your contribution! I can create a profile for you in [app/config/sculpin_site.yml](https://github.com/pantheon-systems/documentation/blob/master/app/config/sculpin_site.yml).

Can you provide the following:
```
#######################################################################################################
# The contributors. Include your info here, under the "contributors" key, using the following template:
#
#  handle:
#      name: Your Name
#      url: http://yourURL.com
#      avatar: http://url.to.a.valid/avatar.jpeg
#      twitter: handle
#      gplus: https://plus.google.com/
#      github: https://github.com/
#      linkedin: https://www.linkedin.com/in/
#      drupal: https://www.drupal.org/u/
#      wordpress: https://profiles.wordpress.org/
#      bio: this is a short bio, it should not be so long, just a quick info that defines you.
#
# Please provide at least "name" and "bio" . The googleplus url is useful to show your contributor info
# on Google search results.
#######################################################################################################
```

This is optional and does not have to block this PR. Thanks again for contributing to the docs!

**Comment by cityofoaksdesign** [comment]
#      name: Christopher Matthews
#      url: https://www.cityofoaksdesign.com
#      avatar:
#      twitter:
#      gplus:
#      github: https://github.com/cityofoaksdesign
#      linkedin:
#      drupal: https://www.drupal.org/u/chris2
#      wordpress:
#      bio:

**Comment by rachelwhitton** [comment]
Thanks again for the PR @cityofoaksdesign! I added your contrib profile in [this commit](https://github.com/pantheon-systems/documentation/commit/b4ccf0a3de6f588ee67d340768b22ad9e9f1b778#diff-51a891976ae5b6b39351a4558a965354). For `avatar` I used your drupal.org profile image. 

https://pantheon.io/docs/core-updates/ now reflects you as a contributor
https://pantheon.io/docs/contributors/ now includes your contrib profile in the list of all contribs
https://pantheon.io/docs/contributors/cityofoaksdesign now available as a direct link to your individual contrib profile 

Feel free to edit your profile directly by submitting a PR to [app/config/sculpin_site.yml](https://github.com/pantheon-systems/documentation/blob/master/app/config/sculpin_site.yml#L317)

**Pull request merged**
