### PR TITLE
Update Frontend Performance Guide

### PR DESCRIPTION
**Pull request by carolyn-shannon**
Closes: #5836 

## Summary

**[Frontend Performance Guide](https://pantheon.io/docs/guides/frontend-performance)** - Updates frontend performance guide to align with Google's Core Web Vitals metrics, expand WordPress tools/techniques, consolidate section on db/query performance.

## Remaining Work
The following changes still need to be completed:

- [ ] Consolidate db-query troubleshooting
- [ ] Expand/WP tools/techniques

## Post Launch
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-5996](https://pr-5996--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `55.00000000000001` | `57.99999999999999` | `3` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `88` | `88` | `0` |

Lighthouse Audit Reports:

- [`pr-5996` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/23719/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/23719/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-5996--pantheon-docs.my.pantheonfrontend.website/docs)

**Review by alexfornuto — COMMENTED** [review]
Frontmatter checks out. Needs a rebase to main, demo'd [here](https://github.com/pantheon-systems/documentation/tree/fe-perf-update-rebase)

**Comment by carolyn-shannon** [comment]
This requires a more thorough re-write.

**Comment by EdwardAngert** [comment]
I tried to resolve the merge conflicts cleanly, but ended up with a local mess, so new PR in #6947

**Pull request closed without merging**
