### PR TITLE
Style Guide Update for Exports

### LINKED ISSUE #3274: Better format for Terminus example commands.
Re: [Style Guide](https://pantheon.io/style-guide)
## Issue Description
A reader reports, with great verbosity, that the use of `<site>.<dev>` can be confusing.

## Suggested Resolution

 - [ ] Define in the style guide a replacement example, preferably one use dummy variables and no extra symbols.
 - [ ] Find & replace throughout the repository to align.

### PR DESCRIPTION
**Pull request by alexfornuto**
Closes #3274 

## Effect
PR includes the following changes:
- Callout for variable exports.
-
-

## Remaining Work
- [x] Fix CSS
- [x] Standardize Callout
- [ ] Standardize Terminus var usage in Style Guide
- [ ] Standardize example exports throughout all docs
- [ ] Weep with Joy when it's finally done.
- [ ] Abandon technology entirely and go live in the woods as a Luddite hermit.

## Post Launch
To be completed by the docs team upon merge: 
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Archive from **Done** in Waffle

### CODE REVIEW

**Comment by alexfornuto** [comment]
@kimby77 this PR creates a new call-out for us to explicitly define any variables needed throughout the guide. I used the Pantheon brand colors, and came up with this:

image

I humbly request your input on making it more awesome.

**Comment by kimby77** [comment]
Can I see this in the context of a real docs page?

**Comment by alexfornuto** [comment]
@kimby77 Here are a few examples. 

https://3274varss-static-docs.pantheonsite.io/docs/backups/
https://3274varss-static-docs.pantheonsite.io/docs/cms-admin/

**Comment by kimby77** [comment]
Thanks!  The yellow background is the equivalent of CAPS LOCKS SHOUTING, and it makes links (like the Terminus example) hard to discern because the yellow background & blue foreground are too close in tone.  To draw some attention to the box without shouting, I suggest something like this:

image

**Comment by alexfornuto** [comment]
@kimby77 I think I've correctly replicated your suggestions.

https://3274varss-static-docs.pantheonsite.io/docs/backups/

**Comment by kimby77** [comment]
👍

**Pull request merged**
