### PR TITLE
Update create-custom-upstream.md

### LINKED ISSUE #3082: Create a Custom Upstream Doc Update
Re: [Create a Custom Upstream](https://pantheon.io/docs/create-custom-upstream/)

Priority (High):

## Issue Description: 
There is no wording/warning about the Scope of Support provided for Custom Upstreams

## Suggested Resolution:
Add a Red warning box or a Blue Note to define the scope of Pantheon Support.

### PR DESCRIPTION
**Pull request by ttrowell**
Closes #3082 

## Effect
PR includes the following changes:
- adds NOTE about Support

## Remaining Work
- [x] Get a +1 from @slashzero @newtoid if needed

### CODE REVIEW

**Comment by ttrowell** [comment]
@slashzero @newtoid Please review - thanks!

**Comment by newtoid** [comment]
@ttrowell looks good to me

**Comment by ttrowell** [comment]
@alexfornuto We can't get the link to format. :(

**Comment by alexfornuto** [comment]
👍  from me, but I'd like @rachelwhitton to review as well.

**Comment by slashzero** [comment]
+1 LGTM

**Comment by rachelwhitton** [comment]
I'd rather have this as an entry in the scope of support. The note's a good idea, but it needs to be easier to skim / less distracting

**Pull request merged**
