### PR TITLE
Update "create script" section with "aggregate logs" option.

### PR DESCRIPTION
**Pull request by hckia**
Closes #

## Summary

**[Log Files on Pantheon](https://pantheon.io/docs/logs#create-a-script)** - Makes aggregating logs easier with a new, enhanced script that can be easily downloaded right from the doc.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [x] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by hckia** [comment]
The main reason for this change is that customers often complain that they have no easy method for combining all nginx access logs into a single file for analysis in GoAccess. Both Penguin Random House and UNC have utilized this script I provided to them. The only difference is I've included it in the existing script, and the user can control whether they use it or not by changing the boolean values

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6880](https://pr-6880--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.99999999999999` | `59` | `2` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6880` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31654/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31654/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6880--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by EdwardAngert** [comment]
[preview](https://pr-6880--pantheon-docs.my.pantheonfrontend.website/docs/logs#create-a-script)

**Review by michellecolon-pantheon — APPROVED** [review]
LGTM

**Pull request merged**
