### PR TITLE
DOCO-776 Reduce Large Repos

### LINKED ISSUE #8029: git filter-branch is no longer recommended
Re: [Reducing Large Repositories](https://pantheon.io/docs/reducing-large-repos)

Priority: Medium

## Issue Description:

When removing a large file from Git's history, the techniques used in the current documentation are out-dated and potentially dangerous. There are easier and faster tools available and recommended now.

Per Git's docs here: https://git-scm.com/docs/git-filter-branch#_warning
> WARNING
> git filter-branch has a plethora of pitfalls that can produce non-obvious manglings of the intended history rewrite (and can leave you with little time to investigate such problems since it has such abysmal performance). These safety and performance issues cannot be backward compatibly fixed and as such, its use is not recommended. Please use an alternative history filtering tool such as [git filter-repo](https://github.com/newren/git-filter-repo/).

## Suggested Resolution
Replace with a guide on installing and using `git filter-repo`

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #8029 

## Summary

**[Git Troubleshooting](https://pantheon.io/docs/guides/git/troubleshooting#reduce-large-repositories))** - Created a new section for reducing large repos.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by whitneymeredith** [comment]
| Redirect from                 | to                                 |
|-------------------------------|-------------------------------------|
|  docs/reducing-large-repos    | docs/guides/git/troubleshooting#reduce-large-repositories)  |

**Comment by whitneymeredith** [comment]
[Preview](https://pr-8030--pantheon-docs.my.pantheonfrontend.website/docs/guides/git/troubleshooting#reduce-large-repositories)

**Comment by whitneymeredith** [comment]
@jms-pantheon I deleted the outdated page and added a new section to the Troubleshooting page in the Git guide referring users to the recommended solution (git-filter-repo).

**Review by jms-pantheon — APPROVED** [review]
Looks great, thanks @whitneymeredith

**Comment by wordsmither** [comment]
lgtm

**Pull request merged**
