### PR TITLE
CAA records are inherited by subdomains.

### PR DESCRIPTION
**Pull request by ari-gold**
## Effect
PR includes the following changes:
- Update partial to include note

## Remaining Work
- [ ] List any outstanding todos
- [ ] If needed

## Post Launch
To be completed by the docs team upon merge: 
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Archive from **Done** in Waffle

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Adding similar content to the Custom Cert doc based on client feedback, hoping it's a friendly addition. Thanks for starting the PR Ari!

+1

**Comment by alexfornuto** [comment]
@rachelwhitton @ari-gold do either of you want to add the work Rachel suggested into this PR, or should I review it as is and move the suggestion to a new issue for later discussion / work?

**Comment by ari-gold** [comment]
@rachelwhitton @alexfornuto I think the dashboard should look differently when custom cert is loaded, so sounds like would be good to move to a new issue, if you'd like

**Comment by rachelwhitton** [comment]
Moved my suggestions to a separate issue (#4486)

Thanks!

**Pull request merged**
