### PR TITLE
D8 Performance & Caching Settings doc updates

### PR DESCRIPTION
**Pull request by nataliejeremy**
connects to #922

### CODE REVIEW

**Comment by nataliejeremy** [comment]
@bmackinney Please review and merge.

**Comment by nataliejeremy** [comment]
@bmackinney @rachelwhitton Please review and merge.

**Comment by rachelwhitton** [comment]
+1 LGTM - Thanks @nataliejeremy and @erik-pantheon!

**Comment by nataliejeremy** [comment]
@bmackinney Please review and +1

**Comment by bmackinney** [comment]
:+1:

**Pull request merged**
