### PR TITLE
1027 landing layout

### LINKED ISSUE #1027: Landing Page Layout
## Issue Description:
Landing pages should have their own layout, similar to articles but without TOC. 
Landing pages should also list child articles. If we can do this without adding content types for every section of the site, that would be ideal, but if not, it's fairly simple to add them. 

List of pages: 

- /sites
 - (sites sub-articles?)
- /users
- /organizations
- /drupal
- /wordpress
- /local
 
## Suggested Resolution 
Create layout, test and gather feedback.

### PR DESCRIPTION
**Pull request by rachelwhitton**
Closes #1027 

@bmackinney @informanddelight  -- demos below are ready for review. 
### Demos: 
- [All Articles](http://docs-files-panther.pantheon.io/docs/articles)
- [Drupal](http://docs-files-panther.pantheon.io/docs/articles/drupal/)
- [Local](http://docs-files-panther.pantheon.io/docs/articles/local/)
- [Organizations](http://docs-files-panther.pantheon.io/docs/articles/organizations/)
- [Sites](http://docs-files-panther.pantheon.io/docs/articles/sites/)
 - [Backups](http://docs-files-panther.pantheon.io/docs/articles/sites/backups)
 - [Code](http://docs-files-panther.pantheon.io/docs/articles/sites/code)
 - [Create](http://docs-files-panther.pantheon.io/docs/articles/sites/create)
 - [Database](http://docs-files-panther.pantheon.io/docs/articles/sites/database)
 - [Domains](http://docs-files-panther.pantheon.io/docs/articles/sites/domains)
 - [Files](http://docs-files-panther.pantheon.io/docs/articles/sites/files)
 - [Logs](http://docs-files-panther.pantheon.io/docs/articles/sites/logs)
 - [New Relic](http://docs-files-panther.pantheon.io/docs/articles/sites/newrelic)
 - [Security](http://docs-files-panther.pantheon.io/docs/articles/sites/security)
 - [Settings](http://docs-files-panther.pantheon.io/docs/articles/sites/settings)
 - [Varnish](http://docs-files-panther.pantheon.io/docs/articles/sites/varnish)
- [Users](http://docs-files-panther.pantheon.io/docs/articles/users)
- [WordPress](http://docs-files-panther.pantheon.io/docs/articles/wordpress)

#### One redirect needed after deployment: source/docs/articles/local/developing-locally.md --> source/docs/articles/local.md

In addition to the new landing page layout, this PR includes the following:

- Delete 8.html which was originally created under the incorrect assumption that distinct layouts were required for custom content types.
- Delete source/docs/articles/local/developing-locally.md and restore content to local.md landing page (redirect needed after deployed)
- Adjust assets_version to 1.8
- Make docs site full width (uses container-fluid class)
- Fix URL's generated on the linked in share button, update the scripts according to new developer instructions (guide layout)
- Delete pagination in changelog landing page, caused a 404 on live site
- Move pagination in changelog post layout so it is centered on the entire page (aligns with full width docs)
- Center text with images in footer, tweak search bar css

### CODE REVIEW

**Comment by informanddelight** [comment]
@rachelwhitton Looking good. Could we make the icon + lists a hanging indent? When the article title returns to the next line, it is directly under the list item. This might require some tweaking, like using <ul> for all the articles. I'm actually fine killing off the 'document' icon and just using plain old bullets. I just want to make it look like discrete/separate items in a list.

**Comment by rachelwhitton** [comment]
Thanks @informanddelight for the suggestions - I updated the demos again, can you review? I couldn't get the div height to extend beyond a single page and with a background color it looked strange, so I changed it to white. Thoughts? Feel free to push commits directly to this PR if you'd like, thanks again for the help!

**Comment by informanddelight** [comment]
Committed my changes. Largely doing some slight tweaks:

-changed the code on the 'pio-landing-sidenav'  - now it's using a bootstrap list item and uses CSS to populate in the glyphicon instead of having to manually insert a glyphicon on each row. Also removed a <br> and used block elements for more even spacing between line items.
-tweaked the footer icons so that the text is middle centered to the icons. also tweaked footer text slightly and gave it a little bit of padding
-put a background on the `.pio-landing-sidenav` . I'm ok with it not fully extending down. I also made sure the header's baseline of this section is aligned with the other headlines
-also tweaked the search bar a bit. the online is a little lighter and the button is now smushed up against the form field so they feel like one discrete action

**Comment by rachelwhitton** [comment]
Thanks for the addition @informanddelight - love it! Can you and @brian review the left side TOC and the right alignment of the directory index lists? I haven't committed yet, but the demo's are updated.

**Comment by informanddelight** [comment]
@bmackinney I reviewed the implementation with Rachel and we felt that the Article Directory on the left side works better for keeping our navigation hierarchy (since we read from left to right). It mirrors the breadcrumbs above and keep the far right rail for the TOC. Let me know if that seems unclear or if you have other thoughts. I'm glad we explored both options so we could better form our decision.

**Comment by bmackinney** [comment]
I'm glad we explored too and defer to you. The only other option I'd like to see is for both to be on the right. I remember discussing but the scroll issue wasn't resolved before it switched to a sandwich. My eye goes to the title first, and I think that should be located far left. thoughts?

**Comment by rachelwhitton** [comment]
Also, future work in a seperate issue should include an audit to move docs listed in the “miscellaneous” sections to appropriate subdirectories. “miscellaneous” shouldn’t really be a thing, its a temporary solution to help handle the lists.

**Comment by bmackinney** [comment]
:+1:

**Comment by informanddelight** [comment]
:+1:

**Pull request merged**
