### PR TITLE
Update getting-support.md

### PR DESCRIPTION
**Pull request by ttrowell**
## Effect
PR includes the following changes:
- clarifies support hours for standard cases (non-Elite)

## Remaining Work

@twooten @newtoid  Thoughts?

### CODE REVIEW

**Comment by ttrowell** [comment]
Tim, I didn't add in PH time just yet.

**Comment by newtoid** [comment]
If this is achievable then +1, and we should update this page https://pantheon.io/pricing-comparison

I would say the 2 hour turnaround on Free/sandbox sites might be ambitious during high volume times, so maybe best effort for sandbox/pro with priority on business, and published/agreed SLAs for Elite and PES, just to manage client expectations.

**Comment by ttrowell** [comment]
@newtoid The page currently lists the 2 hour window for non-SLA sites.  I only added the actual current support hours.  I agree that 2 hours could be ambitious at times, though.

**Comment by ttrowell** [comment]
@nataliejeremy Let's update this so we have some clarification, then we can modify it again if needed.  Sound ok?

I don't think the 2 hour window for is guaranteed at all  - excepting Elite sites.

**Comment by nataliejeremy** [comment]
Thanks! @ttrowell

**Pull request merged**
