### PR TITLE
(WIP, Test) Testing a search page to be embedded in Pendo

### PR DESCRIPTION
**Pull request by mel-miller**
## Summary

This PR is to test the concept of embedding a docs search page in Pendo. 

Kristi Whitman from design is interested in having a way to search docs from within Pendo. I have created a separate version of the search results page that is minimally styled with the header and footer stripped out so that she can test how it would embed in Pendo. 

No action is needed at this time. She can test this via the PR build branch. 

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by stevector** [comment]
FWIW, I see value in potentially intertwining Docs search with pantheon.io search via the Federated Search module for Drupal. See the discussion in https://getpantheon.atlassian.net/browse/BUGS-6666 I'd rather use our own product than a separate SaaS for search.

**Comment by mel-miller** [comment]
> I'd rather use our own product than a separate SaaS for search.

Noted. And agree. 

I think she was mainly testing out the limits of functionality in Pendo. But I'll let her know that long-term the search situation will be different and potentially easier to integrate.

**Comment by mel-miller** [comment]
No longer needed. Only a test.

**Comment by mel-miller** [comment]
No longer needed. Only a test.

**Pull request closed without merging**
