### PR TITLE
Update gandi.md

### LINKED ISSUE #3794: Gandi Domain Configuration Doc Update
Re: [Gandi Domain Configuration](https://pantheon.io/docs/gandi/)

Priority: low

## Issue Description: 

The domain name is appended to the hostname if "." is not specified.
a

Ex. dig www.redbridgefirstworldwar.org.uk +short
live-redbridge-first-world-war.pantheonsite.io.redbridgefirstworldwar.org.uk.

Users can easily overlook this warning -- requested by Customer to add this to our doc.

## Suggested Resolution

Add a troubleshooting section and include this info.

### PR DESCRIPTION
**Pull request by rubelyn**
Closes #3794

## Effect
PR includes the following changes:
- Adding note to include dot (.) at the end of the hostname field.

### CODE REVIEW

**Comment by alexfornuto** [comment]
@rubelyn:

1) In which field is the dot required? 

2)
> A hostname usually ends with a dot(.) **not unless** you want it to be suffixed by the current domain.

Phrasing here is unclear. Do you add the doc is you want it to be suffixed?

**Comment by rubelyn** [comment]
hello @alexfornuto ,

It should be added to the hostname field. See attached screenshot.

a

**Comment by alexfornuto** [comment]
@rubelyn thanks for clarifying. Is this only for `CNAME` records, or are there others that need this note?

**Comment by tinefin** [comment]
@alexfornuto My guess would be it's only needed for domains, not IP's. Unless we get an issue showing otherwise, I think this change is sufficient.

**Comment by alexfornuto** [comment]
Thanks @tinefin!

**Comment by rubelyn** [comment]
hi @alexfornuto, sorry I was out last week. Yes, it is for CNAME records only. Please see -https://wiki.gandi.net/en/dns/zone/cname-record#how_to_add_a_cname_record_in_expert_mode

Sorry for not being clear. Thanks @tinefin for your input!

**Pull request merged**
