### PR TITLE
Document HTTPS warnings for Custom Cert users to ignore.

### LINKED ISSUE #4486: Domain / HTTPS Status after Disabling LE
Re: https://pantheon.io/docs/custom-certificates/#disable-lets-encrypt-with-caa-records-required

Priority: Low or Medium 

## Issue Description:
Content gap on expected state of Domains / HTTPS after disabling Let's Encrypt via CAA records. Originally surfaced in #4433 

## Suggested Resolution
Describe expected HTTPS status in the Site Dashboard for domains that disable Let's Encrypt. 

Domain overview will show an HTTPS Error warning next to the domain: 
screen shot 2019-01-31 at 6 18 51 pm

Domain details will report Authorization failed error with instructions to contact support: 
screencapture-dashboard-pantheon-io-sites-e6a7a68b-bf82-42b8-8771-86da03989e55-2019-01-31-18_16_35

Also, note that a proactive ticket will be created with "Action Required" in the subject. Custom Certificate users should not take action to authorize Let's Encrypt and can ignore the ticket. Example ticket 125893: 
> **Action required: DNS blocking HTTPS for pancaa.com, www.pancaa.com**
> We're reaching out because your DNS configuration must be updated in order to ensure uninterrupted HTTPS. The following problems were found:
> 1. CAA records allow you to authorize which certificate authorities (CAs) can issue certificates for your domain, and right now Let's Encrypt is not authorized for pancaa.com, www.pancaa.com:
> https://www.whatsmydns.net/#CAA/pancaa.com
> https://www.whatsmydns.net/#CAA/www.pancaa.com
> You can use SSL Mate's CAA record generator https://sslmate.com/labs/caa/ to generate a set of CAA records listing the CAs that you would like to allow, and make sure to include Let's Encrypt (letsencrypt.org).
> If you are unable to make the change within the next 10 days, HTTPS will be disabled for this domain.
> Please make this change ASAP and we'll verify everything looks good. Let us know if there's anything we can do to help!
______________________________________________________________________
10 days later, the support ticket is updated with:
> HTTPS has been disabled for pancaa.com, www.pancaa.com because your DNS configuration prevented renewal.
>
> If you’d like to re-enable HTTPS, please correct your DNS configuration and reply to this ticket.

### PR DESCRIPTION
**Pull request by alexfornuto**
Closes #4486

## Effect
PR includes the following changes:
- Adds a style for the alert component to mimic dashboard warning messages
- Documents that custom cert users can ignore the dash warning and proactive ticket.

## Remaining Work
- [x] :+1: from @rachelwhitton
- [ ] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
@ksenour wasn't PS talking about this recently?

**Comment by alexfornuto** [comment]
@EdwardAngert can you confirm with Product that this is still the expected behavior, re warning and proactive ticket when using a custom cert?

**Comment by rachelwhitton** [comment]
Per discussion w/Ari in docs - related issue was closed in favor of BUGS-2874

**Comment by alexfornuto** [comment]
Closing PR in favor of product improvement.

**Pull request closed without merging**
