### PR TITLE
Refine Lighthouse Commenting

### PR DESCRIPTION
**Pull request by alexfornuto**
**Note:** Please fill out the PR Template to ensure proper processing.

## Summary

**[Site Stack Improvement](https://github.com/pantheon-systems/documentation)** - Provides a command to run Lighthouse tests locally (For Docs team members with appropriate Keys.) Mostly a prereq step so I can fix the commenting to not spam.

## Effect

The following changes are already commited:

- inits local lighthouse test

## Remaining Work

The following changes still need to be completed:

- [x] Test PR commenting
- [x] Fix repeat editing
- [ ] maybe do the same thing with the files changed comments.

## Post Launch

- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `60` | `45` | `-15` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19342/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19342/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `0` | `-56` |
| Best Practice Score | `93` | `79` | `-14` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](undefined/lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](undefined/lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `0` | `-56` |
| Best Practice Score | `93` | `79` | `-14` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](undefined/lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](undefined/lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `0` | `-56` |
| Best Practice Score | `93` | `79` | `-14` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](undefined/lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](undefined/lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `0` | `-56` |
| Best Practice Score | `93` | `79` | `-14` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](undefined/lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](undefined/lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `0` | `-56` |
| Best Practice Score | `93` | `79` | `-14` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](undefined/lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](undefined/lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `0` | `-56` |
| Best Practice Score | `93` | `79` | `-14` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](undefined/lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](undefined/lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `0` | `-56` |
| Best Practice Score | `93` | `79` | `-14` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](undefined/lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](undefined/lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `0` | `-56` |
| Best Practice Score | `93` | `79` | `-14` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](undefined/lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](undefined/lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `0` | `-56` |
| Best Practice Score | `93` | `79` | `-14` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](undefined/lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](undefined/lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5604 | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `39` | `-17` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5604` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19439/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19439/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
Tested and confirmed working by adding this code to #5571, which will merge this when merged tomorrow.

**Pull request merged**
