### PR TITLE
Change PHP 7.2 to EOL

### PR DESCRIPTION
**Pull request by allenfear**
**Note:** Please fill out the PR Template to ensure proper processing.

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6175](https://pr-6175--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `44` | `52` | `8` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `88` | `88` | `0` |

Lighthouse Audit Reports:

- [`pr-6175` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/25422/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/25422/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6175--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by alexfornuto** [comment]
Blocked pending discussion and outcome in https://github.com/pantheon-systems/drops-7/pull/164

**Comment by EdwardAngert** [comment]
coming in to update - leaving this as blocked after talking with @greg-1-anderson 
work is coming to this area, but we're not there yet

**Comment by EdwardAngert** [comment]
update: we could make this change since yes, 7.2 is eol, but some upstreams still deploy with 7.2 so some customers would still encounter it
here's the [PHP EoL table](https://endoflife.software/programming-languages/server-side-scripting/php)

open sourcery is hoping to have another update after July

**Comment by greg-1-anderson** [comment]
We haven't bumped the default PHP version up to 7.4 yet.

**Comment by EdwardAngert** [comment]
the table is up to date now
closing

**Pull request closed without merging**
