### PR TITLE
Correct site-level Roles and Permissions table

### LINKED ISSUE #1791: Role-Based Permissions
Re: [Role-Based Permissions & Change Management](https://pantheon.io/docs/change-management/)

## Issue
Some permissions may be incorrect for certain roles.

## Resolution
Test site-level permissions 

Surfaced by @hengkit

### PR DESCRIPTION
**Pull request by rachelwhitton**
Closes #1791 

## Effect
PR includes the following changes:

_Enterprise and Partner Organizations: Roles and Permissions table_ 
- Add EDU+ to Unprivileged tooltip

_Site-Level: Roles and Permissions table:_ 
- Remove Create Sites within an org
- Replace Access the org dashboard with Access the site Dashboard
- Remove Administrator column
- Add titles to tooltips; include User in Charge

cc @hengkit @bensheldon @nataliejeremy

### CODE REVIEW

**Comment by rachelwhitton** [comment]
screen shot 2016-08-08 at 4 19 08 pm

**Comment by hengkit** [comment]
`This helps distinguish who created a site in Enterprise Organizations with unprivileged users (e.g. Universities).` isn't quite right. 

Maybe `This helps distinguish who created a site in Enterprise Organizations. ~ with unprivileged users (e.g. Universities)~`

**Comment by hengkit** [comment]
LGTM +1

**Comment by nataliejeremy** [comment]
LGTM!

**Pull request merged**
