### PR TITLE
Amend -l flag

### PR DESCRIPTION
**Pull request by alexfornuto**
Closes #3429 

## Effect
PR includes the following changes:
- Amends `-l` with `--copy-unsafe-links`

## Remaining Work
- [x] Review from @acobster (optional)
- [ ] Technical Review
- [ ] Copy review.

### CODE REVIEW

**Comment by alexfornuto** [comment]
@acobster thoughts?

**Comment by acobster** [comment]
Looks good! My only nitpick would be to replace the term "reference" with something more explicit, like "symlink target" [here](https://github.com/pantheon-systems/documentation/pull/3535/commits/73cfec87f42653dd1a8c01738fe96a78ff2b2e55#diff-3e0cf9c130f5fad65aa69aa17dbbf683R62), since "reference" could be construed as either the file being pointed to or the file doing the pointing. Whenever possible, I like being able to reason about `rsync` without thinking about [semiotics](https://en.wikipedia.org/wiki/Signified_and_signifier). ;)

**Comment by alexfornuto** [comment]
Done, thanks for the feedback!

**Comment by alexfornuto** [comment]
BTW for anyone interested, [this](https://gist.github.com/alexfornuto/a575b1a2a3492b632dfc94a5336a0af4) is how I confirmed that these flags will work as we expect them to.

**Comment by alexfornuto** [comment]
Assigning to @lauren-kelly to confirm the behavior.

**Pull request merged**
