### PR TITLE
[CMS-924] Move WordPress Composer Managed docs

### LINKED ISSUE #7665: WordPress with Composer on Pantheon Doc Update to its own guide?
Re: [WordPress with Composer on Pantheon](https://pantheon.io/docs/guides/wordpress-composer/wordpress-composer-managed)

Priority: Low

## Discuss

From @CdrMarks 

Consider splitting WP Composer Bedrock-specific guide out of the greater WP Composer guide to help focus feedback and conversation from Bedrock Early Access users

options:
- move doc to its own `/docs/guides/wordpress-composer/wordpress-composer-managed` out of the WP Composer guide and into `/docs/wordpress-composer-managed` ?
- redirect `/docs/wordpress-composer-managed` to existing doc?
- make a new subdirectory under the current guide for EA? so `/docs/guides/wordpress-composer/pre-ga/wordpress-composer-managed` so that the doc maintains its relationship, but isn't in the left-hand nav as if its a GA option?

### PR DESCRIPTION
**Pull request by jspellman814**
Closes #7665 

## Summary

**[Doc Page Title](https://pantheon.io/docs/doc-title)** - <Enter a one sentence summation of the pertinent changes (including not-yet-completed work) provided by this PR.>

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7667](https://pr-7667--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `47` | `53` | `6` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7667` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/41426/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/41426/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7667--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by jspellman814** [comment]
[Preview](https://pr-7667--pantheon-docs.my.pantheonfrontend.website/docs/wordpress-composer-managed). This implements option 1 from #7665.

**Comment by CdrMarks** [comment]
[Preview of the guide](https://pr-7667--pantheon-docs.my.pantheonfrontend.website/docs/guides/wordpress-composer).  This also looks good to me.

**Comment by jspellman814** [comment]
If we move forward with this change, we'll need to redirect https://pantheon.io/docs/guides/wordpress-composer/wordpress-composer-managed to https://pantheon.io/docs/wordpress-composer-managed

**Comment by jspellman814** [comment]
This is being handled in #7860. Closing.

**Pull request closed without merging**
