### PR TITLE
Updates PANTHEON_STRIPPED overview and removes redirect caveat

### PR DESCRIPTION
**Pull request by ajbarry**
I have updated the overview section describing the effects of our varnish configuration. Please review and comment but HOLD for merge until the varnish config is in place.

Related info:
https://sprint.ly/product/24553/item/378
https://getpantheon.atlassian.net/wiki/x/3YDWAw

### CODE REVIEW

**Comment by bmackinney** [comment]
@ajbarry is this ready to go out?

**Comment by ajbarry** [comment]
Hey @bmackinney, as soon as @kibra gives us the signal the code has been deployed we'll release the docs. Should be going out today.

**Comment by ajbarry** [comment]
@suzannealdrich Can I get a blessing from CSE on these doc changes?

**Comment by suzannealdrich** [comment]
I've read through and it looks good to me!

**Comment by bmackinney** [comment]
:rocket: -ed

**Pull request merged**
