### PR TITLE
[OTTO-449] Update documentation to recommend using pantheon-systems/terminus-d9-preview

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Closes: # n/a

## Summary

**[Drupal 9 Early Access](https://pantheon.io/docs/drupal-9#test-upgrade-an-existing-pantheon-drupal-8-site-to-drupal-9)** - Terminus D9 Preview plugin

## Effect
The existing documentation in the section "Test-upgrade an Existing Pantheon Drupal 8 Site to Drupal 9" is out of date and no longer works. This PR rewrites this section to instead use a Terminus plugin to perform the git branch manipulations necessary to create a preview D9 multidev.

## Remaining Work

- [ ] Technical review

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).

### CODE REVIEW

**Review by ari-gold — APPROVED** [review]
Thanks for pushing this forward @greg-1-anderson 

I haven't tested the plugin to confirm it works, but the doc change looks good.

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6017](https://pr-6017--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.00000000000001` | `64` | `8` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `88` | `88` | `0` |

Lighthouse Audit Reports:

- [`pr-6017` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/23846/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/23846/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6017--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by sarahg** [comment]
@greg-1-anderson I tried this out on two sites (one of which was brand-new drops-8) and got some odd output as the multidev spun up: 

https://gist.github.com/sarahg/e91e30477bfa2c3ce663f6d00e531a5f (new site)
https://gist.github.com/sarahg/b3e68b3d3a4d8e34e61b2f6db569dc51 (older site)

Terminus info:

```
└❯ terminus self:info
 ------------------------- --------------------------------------------------------------------------------------------------
  PHP binary                /usr/bin/php
  PHP version               7.3.11
  php.ini used              /etc/php.ini
  Terminus project config
  Terminus root dir         /Users/sarahgerman/vendor/pantheon-systems/terminus
  Terminus version          2.4.1
  Operating system          Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
 ------------------------- --------------------------------------------------------------------------------------------------
```
The D9 env did end up functional though (which is super cool!!). 

I was not able to reproduce the unexpected console messages with a regular `terminus multidev:create` or `terminus multidev:create <env> --no-files --no-db`.

**Comment by greg-1-anderson** [comment]
@sarahg Which output did you find odd?
```
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1367 and retry the command.
```
This just means that git was confused by the extremely large diff that the merge I do produces. The message is innocuous. I could hide it from the user, but then actual errors might be missed.

```
 [error]  Could not find an environment identified by preview-d9.
```
This happens the first time you run the command. I could hide the error message.

Was there anything else that you thought was odd?

**Comment by sarahg** [comment]
@greg-1-anderson I should've been more specific, sorry! The "Creating" step looks different than what I see when creating a multidev with a standard `multidev:create` — it prints many, many lines, like this:

```
[notice] >> terminus multidev:create preview-d9 --no-files --no-db
 0/5 [>---------------------------] Create a Multidev environment
 1/5 [=====>----------------------] Creating Multidev environment "preview-d9"
 3/5 [================>-----------] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 5/5 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 6/6 [============================] Creating Multidev environment "preview-d9"
 9/9 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 10/10 [============================] Creating Multidev environment "preview-d9"
 13/13 [============================] Creating Multidev environment "preview-d9"
 16/16 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 18/18 [============================] Creating Multidev environment "preview-d9"
 19/19 [============================] Creating Multidev environment "preview-d9"
```

But if I create a multidev like this -- `terminus multidev:create preview3-d9 --no-files --no-db` -- the progress bar displays as expected (one progress bar where the numbers on the left increment as tasks complete):

```
⚡️  sarahgerman in 📁  sarahg-drupal-niner on 🌿  master ✓
└❯ terminus multidev:create preview3-d9 --no-files --no-db
10/10 [============================] Creating Multidev environment "preview3-d9"
```

(and ultimately this same progress bar is replaced with `[notice] Created Multidev environment "preview3-d9"`)

This doesn't really feel directly related to this plugin but I don't see it happening outside of it. Maybe not a blocker to publishing it though since it does get the job done.

**Comment by greg-1-anderson** [comment]
It might work better if I used `passthru` for that call.

**Comment by greg-1-anderson** [comment]
I tried passthru and the progress bar disappeared altogether. 🤷

**Review by EdwardAngert — APPROVED** [review]

**Pull request merged**
