### PR TITLE
PHP Guide

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #[DOC-699](https://getpantheon.atlassian.net/jira/software/projects/DOC/boards/186?selectedIssue=DOC-699)

## Summary

**[PHP Guide](https://pantheon.io/docs/guides/php)** - Collected PHP content into a guide. Curated and refreshed all PHP related content for consistency and usability.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7628](https://pr-7628--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `46` | `39` | `-7` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7628` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/41042/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/41042/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7628--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7628--pantheon-docs.my.pantheonfrontend.website/docs/guides/php)

**Comment by whitneymeredith** [comment]
Redirects needed:

docs/supported-php —> /guides/php

docs/php-versions   — >/guides/php/php-versions

docs/settings-php —> /guides/php/settings-php

docs/wp-config-php —> /guides/php/wp-config-php

docs/wordpress-sessions —> /guides/php/wordpress-sessions

docs/php-errors —> /guides/php/php-errors

docs/php-slow-log —> /guides/php/php-slow-log

docs/deprecated-constructor-notices —> /guides/php/deprecated-constructor-notices

**Comment by wordsmither** [comment]
lgtm

**Pull request merged**
