### PR TITLE
Restore New domains doc

### LINKED ISSUE #673: Revise domains articles to create one complete document
Update/combine the following docs to create ONE complete Domains doc:

- Domains: (background/conceptual doc) https://pantheon.io/docs/articles/sites/domains/
- Add Domain: https://pantheon.io/docs/articles/sites/domains/adding-a-domain-to-a-site-environment
- Configure DNS: https://pantheon.io/docs/articles/sites/domains/dns-records-for-directing-your-domain-to-your-pantheon-site/

Outline:

### PR DESCRIPTION
**Pull request by rachelwhitton**
Restore #681 

> This PR closes #673 and:

> - Combines Configuring DNS and Adding a Domain docs into Domains.md so that all info is in one place
> - Deletes /docs/articles/sites/domains/dns-records-for-directing-your-domain-to-your-pantheon-site and /docs/articles/sites/domains/adding-a-domain-to-a-site-environment.md
> - Removes links to the two deleted docs
> - Removes the word "tool" from Domains and SSL references

### CODE REVIEW

**Comment by rachelwhitton** [comment]
@bmackinney - I used git cherry-pick to reapply changes that were reverted. You should be able to resume any edits locally and push to the same branch. Ready for review.

**Comment by nataliejeremy** [comment]
@bmackinney Can you review this?

**Comment by ari-gold** [comment]
+1

**Comment by bmackinney** [comment]
CSE please review.

**Pull request merged**
