### PR TITLE
Add Pancake, Filer, Site Status to Terminus Plugins

### LINKED ISSUE #2069: Terminus Plugin Directory Doc Update
Re: [Terminus Plugin Directory](https://pantheon.io/docs/terminus/plugins/directory)
## Issue Description:
Adding Terminus Filer Plugin
## Suggested Resolution 
Add the following plugin to the page.

https://packagist.org/packages/terminus-plugin-project/terminus-filer-plugin

### LINKED ISSUE #2070: Terminus Site Status Plugin
Re: Pantheon Plugin Directory
## Issue Description
Please add https://github.com/terminus-plugin-project/terminus-site-status-plugin to the Pantheon Plugin Directory at https://pantheon.io/docs/terminus/plugins/directory/.
## Suggested Resolution
Plugin appears on the directory listing.

### LINKED ISSUE #2071: Terminus Pancakes Plugin
Re: Pantheon Plugin Directory
## Issue Description
Please add https://github.com/terminus-plugin-project/terminus-pancakes to the Pantheon Plugin Directory at https://pantheon.io/docs/terminus/plugins/directory/.
## Suggested Resolution
Plugin appears on the directory listing.

### PR DESCRIPTION
**Pull request by derimagia**
Closes #2069
Closes #2070 
Closes #2071

## Effect
PR includes the following changes:
- Add Pancakes to Terminus Plugins
- Add Filer to Terminus Plugins
- Add Site Status to Terminus Plugins

May want to somehow denote them as being third party some other way except removing the badge.

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Hey @derimagia! Thanks for the PR - and the plugins!! We just added Pancakes to the plugin directory in #2098 but we're holding off including more 3rd party plugins until we formalize quality standards. We'll let you know ASAP!

**Comment by joshkoenig** [comment]
@rachelwhitton any chance we can +1 this PR prior to launch? I'd like to reference `filer` in the launch blog post, and while I do want us to figure out quality standards, I also don't want that to necessarily get in the way of a good launch.

**Comment by rachelwhitton** [comment]
+1! Thanks @derimagia and @joshkoenig

**Comment by joshkoenig** [comment]
Thanks rachel!

**Pull request merged**
