### PR TITLE
WordPress API Doc

### PR DESCRIPTION
**Pull request by alexfornuto**
## Effect
PR includes the following changes:
- Imports WP API reference data from the API itself.
- Creates a component to consume and display the data
- Adds a new doc covering basic use of the WordPress API

## Remaining Work
- [ ] Finish writing the doc, including practical example calls to make to the API.
- [ ] Technical review
- [ ] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Include/exclude pages ^ respectively within docs search service provider
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5537 | Difference |
| --- | --- | --- | --- |
| Performance Score | `50` | `50` | `0` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5537` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18635/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18635/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5537 | Difference |
| --- | --- | --- | --- |
| Performance Score | `52` | `40` | `-12` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5537` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18804/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18804/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by carolyn-shannon** [comment]
Low priority; on hold until additional SME is identified and use case is greater.

**Comment by alexfornuto** [comment]
ToDo: identify a WP site that allows CORS requests, then refactor to generate API data within Node instead of a bash step required in environment build.

**Pull request closed without merging**
