### PR TITLE
Switch pantheon check in $_SERVER to $_ENV

### PR DESCRIPTION
**Pull request by wxactly**
For consistency with other PANTHEON_ENVIRONMENT checks in this code and elsewhere

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
I believe that on Pantheon, we prefer `$_SERVER` over `$_ENV`.

On one particular site I checked, `$_ENV` contained 19 different variables, all of which also existed in `$_SERVER`. The `$_SERVER` variable, on the other hand, contains over 70 elements. The main difference here is that not everything in `$_SERVER` is an environment variable; all of the http headers are here, for example. The variables that exist in `$_SERVER` that are not in `$_ENV` are not often needed, so perhaps this could go either way.

If we are going to standardize, though, we should be consistent throughout the documentation. Currently, we have a roughly even usage of `$_ENV` and `$_SERVER` throughout the docs.

**Comment by wxactly** [comment]
Cool, thanks @greg-1-anderson. I was going off of the [documentation](https://pantheon.io/docs/read-environment-config/#using-$_server) that says:

> use `$_ENV` instead of `$_SERVER` wherever possible

But... very possible this page is out of date or inconsistent as well! I'm totally fine using `$_ENV` or `$_SERVER`, but it would be good to know which one is preferred on the platform, and make sure the docs reflect that. Definitely happy to help update other doc pages as well... can you let me know which direction to go?

**Comment by greg-1-anderson** [comment]
Thanks for the reference, @wxactly, looks like I got it backwards. Drush sets `$_SERVER`, so I guess that note is primarily for wp-cli users.

Making the docs consistently use `$_ENV` would be much appreciated; the only care that must be taken is to only convert from `$_SERVER` when the variable in question is also available in `$_ENV`, e.g. for values such as:

```
FRAMEWORK
DOCROOT
FILEMOUNT
DRUPAL_HASH_SALT
php_version
DB_HOST
DB_PORT
DB_USER
DB_PASSWORD
DB_NAME
PANTHEON_SITE
PANTHEON_SITE_NAME
PANTHEON_ENVIRONMENT
PANTHEON_INFRASTRUCTURE_ENVIRONMENT
PATH
HOME
PHPRC
PANTHEON_DEPLOYMENT_IDENTIFIER
PANTHEON_ROLLING_TMP
```

**Comment by alexfornuto** [comment]
@wxactly thanks for the heads up!

**Pull request closed without merging**
