### PR TITLE
New doc: Setting HTTP Headers to Control Downstream Caching

### LINKED ISSUE #414: Document how to send HTTP headers that Varnish will care about
Story: As a website developers I want to understand how to send HTTP headers that Varnish will care about so that I can control my websites cache behavior.

Right now we have people setting cookies as a way to prevent pages from being cached, which is bass-ackwards. We should start teaching people about HTTP headers and how to set them to control downstream caching.

Problem: I want to control cacheability and/or cache-lifetime on a per-page basis
Soution: get smart about how to use the internal page cache, and HTTP headers for downstream (varnish) caching
About HTTP headers
How/why to use both the internal page cache and the downstream page cache
Customizing cache lifetime
Preventing a single page from caching

--submitted by @joshkoenig

### PR DESCRIPTION
**Pull request by nataliejeremy**
@timani I created a basic outline as a starting point. Help please!
Closes #414 
- [ ] Add content to Use HTTP Headers for Downstream Varnish Caching
- [ ] Incorporate David's feedback

### CODE REVIEW

**Comment by nataliejeremy** [comment]
@davidstrauss @joshkoenig Can you take a look at this doc and add content to ##Use HTTP Headers for Downstream Varnish Caching
Thanks.

**Comment by davidstrauss** [comment]
For "Use HTTP Headers for Downstream Varnish Caching," we should document use of `Cache-Control`, `Surrogate-Control`, and `s-maxage` on Pantheon. Specifically, we should test (1) how they affect Pantheon's Varnish edge and (2) whether they survive Pantheon's Varnish edge, get stripped, or otherwise get transformed.

**Comment by davidstrauss** [comment]
We should also consider introducing `Downstream-Surrogate-Control` (VCL change required), which we would ignore but send out of Pantheon's Varnish as `Surrogate-Control`.

**Comment by rachelwhitton** [comment]
@nataliejeremy what do you think about expanding the scope of this doc to include content suggested in #1410 ? Seems like a good place to cover Pantheon's VCL configuration and cache tag support

**Comment by zepner** [comment]
To return no-cache headers for a particular page in Drupal, could add the following into `settings.php`, could do:
```
if (current_path() == 'some-path') {
  $conf['page_cache_maximum_age'] = 0;
}
```

**Comment by zepner** [comment]
+1

**Comment by zepner** [comment]
environment to test headers: http://dev-test20160315.pantheonsite.io/test

**Comment by rachelwhitton** [comment]
Closing in favor of work in #1603

**Pull request closed without merging**
