### PR TITLE
Link to patch, explain errors may persist despite config

### LINKED ISSUE #1449: Composer Manager
Re: <Doc title and/or link>
## Issue Description
Document composer manager 
Consider adding to [Unsupported/Problematic Modules and Plugins](https://pantheon.io/docs/articles/sites/code/unsupported-modules-plugins/)
## Suggested Resolution
- [x] decide if we need to re-work the installation instructions for Amazon S3 CORS, see [related drupal.org issue](https://www.drupal.org/node/2688553)
- [x] link to a doc on the proper use of Composer Manager - if we decide to go forward with it. @dustinleblanc is stumping that out now.

cc @ttrowell @allenfear

### PR DESCRIPTION
**Pull request by rachelwhitton**
Closes #1449 
add patch to composer manager documentation
@dustinleblanc can you review?

### CODE REVIEW

**Comment by dustinleblanc** [comment]
@rachelwhitton yep I think that gives enough information to reproduce my success and get folks running composer manager happy as clams. The only outstanding question I have is about alternate instructions for doing this in git push mode vs sftp mode. Should I add some verbiage around that to this PR or should we do that seperately?

**Comment by rachelwhitton** [comment]
@dustinleblanc via Git doesn't seem to align with the intended use of the module, or maybe I'm misunderstanding that part. I'm in favor of keeping instructions/support as simple as possible, but if you'd like to add some context for connection mode feel free to do it within this PR and we can evaluate

**Comment by dustinleblanc** [comment]
@rachelwhitton if someone were to use composer manager with a site in git mode they would just be essentially using it on their local machine, and then ensuring that it doesn't run any file manipulation tasks on the server. Basically they'd just make sure to switch off auto-generation of files and deps in *all* environments instead of just test/live. Its the way I've used the module in the past. We could keep the instructions simple and say to disable auto-generation on Pantheon all together and instruct them to _always_ generate the files via drush if they chose to do so on dev (with a note that they can only do so in sftp mode). I'm not sure how best to handle it other than I fear a git mode user might read our docs, and then enable a module in dev, and have their site vommit all over them in sad fashion and then this guy shows up 

sad site broken guy

Because composer tried to update the lock file to have that module listed.

I'll do a quick rewrite on this PR to cover this in the safer way

**Comment by rachelwhitton** [comment]
+1 LGTM! thanks @dustinleblanc 

@nataliejeremy can you review for copy edits?

**Pull request merged**
