### PR TITLE
Custom WordPress Login Message

### PR DESCRIPTION
**Pull request by alexfornuto**
Closes: #5791 

## Summary

**[Create a WordPress MU Plugin for Actions and Filters](https://pantheon.io/docs/mu-plugin)** - Documents how to set a custom login message in an MU-plugin. PR [5925](https://github.com/pantheon-systems/documentation/pull/5925)

## Remaining Work

The following changes still need to be completed:

- [x] Identify if a user can also remove the "Return to Pantheon" button while keeping a custom login message.

## Post Launch

- [x] Update Status Report
- [x] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
FYI To whoever reviews this: You'll probably have an easier time if you review by commit.

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-5925](https://pr-5925--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `63` | `72` | `9` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `93` | `93` | `0` |

Lighthouse Audit Reports:

- [`pr-5925` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/22994/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/22994/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-5925--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by alexfornuto** [comment]
Setting this aside for now, pending BUGS-3314

**Comment by alexfornuto** [comment]
@pwtyler You can focus on [this commit](https://github.com/pantheon-systems/documentation/pull/5925/commits/cc205b15c03cda467f661e5101f59e6655ff67d4) for technical review.

**Pull request merged**
