### PR TITLE
Pro Services doc update

### LINKED ISSUE #4425: Pro services doc could better reflect offerings
Re: [Professional Services](https://pantheon.io/docs/professional-services/)

Priority: Low

## Issue Description
[Professional Services](https://pantheon.io/docs/professional-services/) doc is out of sync w/ current offerings.

## Suggested Resolution
Work with PS to update doc and point to non-doc [Professional Services](https://pantheon.io/professional-services/) page where applicable.

### PR DESCRIPTION
**Pull request by EdwardAngert**
Closes #4425 

## Effect
PR includes the following changes:
- better explains available PS services

## Remaining Work
- [ ] confirm removed and leftover tables + replace removed or remove remaining
- [x] review from @bentekwork 
- [x] copy edit

## Post Launch
To be completed by the docs team upon merge: 
- [ ] Update Status Report
- [ ] Archive from **Done** in Waffle

### CODE REVIEW

**Comment by bentekwork** [comment]
Can we add @obicke as a reviewer.  He will be managing this doc's contents from here out.

**Comment by EdwardAngert** [comment]
@obicke: just confirming that we should swap `load testing` with `pre-launch load testing` in this.
I can make the commit for that - there anything else you spot that could use some language-ing?

**Comment by alexfornuto** [comment]
Related: #4440

**Comment by obicke** [comment]
@EdwardAngert Thanks or pinging me in Slack since this was not on my radar. Looks good to me.

**Pull request merged**
