### PR TITLE
Testing TypeScript version of pds-toolkit-react

### PR DESCRIPTION
**Pull request by mel-miller**
Testing TypeScript version of pds-toolkit-react

We have recently updated the PDS toolkit to be compatible with TypeScript. This PR updates to the lastest version and tests that the bundle is working correctly — which it is!

This update also introduces a few new changes to the Tag component including truncation for long tag names, an expanded palette of colors (20 total now), and the tags each now have a title attribute included.

### CODE REVIEW

**Review by rachelwhitton — CHANGES_REQUESTED** [review]
@mel-miller I think the existing colors work better than the colors here in this PR now, for example Action Required should stay red rather than switching to yellow. Can I see the expanded palette of colors somewhere? That would make it easier to review this PR

**Comment by mel-miller** [comment]
@rachelwhitton -- here are all the possible colors. Feel free to edit the code in this PR yourself with new tag colors if you'd like.  https://live-pds-toolkit-react.appa.pantheon.site/?path=/docs/components-tag--docs#tag-group

**Review by rachelwhitton — APPROVED** [review]
Based on [all the possible colors](https://live-pds-toolkit-react.appa.pantheon.site/?path=/docs/components-tag--docs#tag-group), here's what I came up with: 


Left is the new, proposed tag colors [(preview link)](https://pr-9113-documentation.appa.pantheon.site/release-notes/?category=account-management&category=action-required&category=billing&category=deprecated&category=drupal&category=front-end-sites&category=general&category=infrastructure&category=modules&category=new-feature&category=documentation&category=performance&category=plugins&category=policy&category=security&category=tools-apis&category=user-interface&category=wordpress&page=1). Right is current production [(live link)](https://docs.pantheon.io/release-notes/?category=account-management&category=action-required&category=billing&category=deprecated&category=drupal&category=front-end-sites&category=general&category=infrastructure&category=modules&category=new-feature&category=documentation&category=performance&category=plugins&category=policy&category=security&category=tools-apis&category=user-interface&category=wordpress&page=1)

Screenshot 2024-07-31 at 10 48 08 AM


Assigning to @mel-miller and @IngridKwok for final review before we merge

**Comment by IngridKwok** [comment]
@rachelwhitton @mel-miller 

1. The reddish hues for "Action required" and "Security" are effective and appropriate.
2. I have concerns regarding the color contrast for the "Deprecated", "User interface" and "WordPress" tags. The dark background combined with the current text color results in insufficient contrast, which may affect readability and accessibility. Defer to Mel for additional comments.

**Comment by mel-miller** [comment]
@IngridKwok -- all of the color combinations are technically accessible (they pass contrast minimums), but if you feel like it doesn't look contrasty enough maybe pick a different color?

**Pull request closed without merging**
