### PR TITLE
Request for Terminus "newrelic-data" plugin to be added in the plugins directory

### LINKED ISSUE #2927: Request for Terminus "newrelic-data" plugin to be added in the plugins directory
Re: https://pantheon.io/docs/terminus/plugins/directory/
## Suggested Resolution
Name of the Plugin - Newrelic-data
Github repo - https://github.com/fusionx1/terminus-get-newrelic
Project Description - https://github.com/fusionx1/terminus-get-newrelic/blob/master/README.md

### PR DESCRIPTION
**Pull request by fusionx1**
Closes #2927 

## Effect
PR includes the following changes:
- Added newrelic data plugin with description, github repo and author

## Remaining Work
- [ ] List any outstanding todos
- [ ] If needed

### CODE REVIEW

**Comment by alexfornuto** [comment]
@fusionx1 have you added this plugin to the [Terminus Plugin Project](https://github.com/terminus-plugin-project) repo yet?

**Comment by fusionx1** [comment]
Hi Alex, not yet but ill be happy to put it there. I thought i can just use my own repo.

**Comment by fusionx1** [comment]
ow yes sorry for the #closes issue.

**Comment by alexfornuto** [comment]
I've added this PR to the list of Terminus plugins waiting review, pending on AL-794

**Comment by fusionx1** [comment]
Added the plugin in pantheon-systems repo:

https://github.com/pantheon-systems/terminus-newrelic-data-plugin
**Updated Readme** - https://github.com/pantheon-systems/terminus-newrelic-data-plugin/blob/master/README.md

**Comment by rachelwhitton** [comment]
Thanks @fusionx1! Since we're blocked by AL-794 I'm going to close this PR to be tracked in #2895 along with related requests.

**Pull request closed without merging**
