### PR TITLE
Continuation of #4011

### PR DESCRIPTION
**Pull request by alexfornuto**
Recreates #4011, reverted in #4018

### CODE REVIEW

**Comment by ataylorme** [comment]
@baisong can you continue your review of #4011 here?

More specifically I am looking for feedabck on my latest comment there:

> When I followed the instructions earlier today, the only difference I saw from the current screenshot (below) is that in the Changes not staged for commit section, I saw two additional lines after modified: .gitignore:

@baisong that is odd. Did you skip the removing automation pieces step? That is what has you delete `.circleci`, `tests` and items in `scripts`. The `git status` will then show them as deleted (unless you committed those deletions).

Similarly prior to modifying `.gitignore` git is not tracking `vendor`, `drush/contrib`, etc. so the final `git status`, after modifying `.gitignore` so those aren't included, will show them as untracked changes.

Maybe you can run through the guide on the multidev for this branch start to finish and see if it still differs? If there are differences I would love to track them down and get the guide corrected.

The URL is [https://issue4008-static-docs.pantheonsite.io/docs/guides/drupal-8-composer-no-ci/](https://issue4008-static-docs.pantheonsite.io/docs/guides/drupal-8-composer-no-ci/)

**Comment by baisong** [comment]
Yes, I removed the automation pieces the first time, and I just walked through the steps again on the link you shared, here are my `git status` screenshots:

### After "Removing Automation Pieces" steps

screenshot from 2018-08-29 10-33-25

### After running `composer update`

screenshot from 2018-08-29 13-33-10

### After modifying `.gitignore`

screenshot from 2018-08-29 13-34-50

**Comment by ataylorme** [comment]
@baisong bonus points for uploading your own screenshots! I don't see a difference between those and what I uploaded to the revised doc. Do you see a difference between your screenshots and those [on the multidsev for the updated guide](https://issue4008-static-docs.pantheonsite.io/docs/guides/drupal-8-composer-no-ci/)? Perhaps I missed something.

**Comment by baisong** [comment]
Nope, they look identical to me too.

One last thing though -- to make these instructions perfect -- right before the `terminus drush $PANTHEON_SITE_NAME.dev -- site-install -y` command, I had to refresh my terminus authentication with `terminus auth:login`

**Comment by ataylorme** [comment]
@baisong great, glad you were able to get the same result with the updated guide.

Needing to re-authenticate with Terminus happens if you aren't authenticated or if it's been a while (after x days since the last auth). I don't think it is tied to this specific step.

I added a reminder to the beginning of the guide to authenticate with Terminus and linked to the doc walking through machine tokens and `auth:login`. With a fresh authentication early that shouldn't be an issue.

**Comment by ataylorme** [comment]
@alexfornuto I think we are all set now for a copy review and merge from you.

**Comment by alexfornuto** [comment]
Thanks @ataylorme and @baisong!

**Pull request merged**
