### PR TITLE
add users landing page

### PR DESCRIPTION
**Pull request by nataliejeremy**

### CODE REVIEW

**Comment by bmackinney** [comment]
@rachelwhitton and @nataliejeremy I moved the import articles to the `sites/create/`directory from `users` because they don't make sense where they are. We'll need to add redirects to the original paths for each article, if merged.

**Comment by nataliejeremy** [comment]
@bmackinney +1

**Comment by bmackinney** [comment]
Requesting a few additions: 

1. [ ] image of the users dashboard.
2. [ ] description of important functions there 
2. [ ] A sentence on user credit card management, linked to that doc

**Comment by nataliejeremy** [comment]
@bmackinney can you merge this one too?

**Pull request merged**
