### PR TITLE
Added information about configuring PHP version through LocalDev in FAQ

### PR DESCRIPTION
**Pull request by CFin86**
This was mentioned in [the localdev community slack](https://i.imgur.com/QNnSpKj.png) and came up in a customer chat today.

## Summary

**[Use Pantheon Localdev to Develop Sites Locally](https://pantheon.io/docs/localdev)** 

- Added documentation of how to configure PHP version of app in LocalDev 

## Remaining Work
The following changes still need to be completed:

- [ ] Content review 
- [ ] Replace screenshots. Pristine copies of screenshots:
- [Force Rebuild](https://i.imgur.com/dQJOBzK.png)
- [Verify PHP version](https://i.imgur.com/dqLH1lb.jpg)

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6040](https://pr-6040--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `66` | `68` | `2` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `88` | `88` | `0` |

Lighthouse Audit Reports:

- [`pr-6040` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/24132/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/24132/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6040--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by marfillaster** [comment]
Can you also please include a note that rebuild is also required when updating `web_docroot`?

**Comment by alexfornuto** [comment]
I'm going to pick this up after #6064 is merged, which changes the paths for images for this guide.

**Review by alexfornuto — APPROVED** [review]
Thanks @CFin86!

**Pull request merged**
