### PR TITLE
Add new PHP library section

### PR DESCRIPTION
**Pull request by slashzero**
Closes #

## Effect
PR includes the following changes:
-
-
-

## Remaining Work
- [ ] List any outstanding todos
- [ ] If needed

Initially for MSSQL - maybe even GeoIP

### CODE REVIEW

**Comment by nstielau** [comment]
+1

**Comment by slashzero** [comment]
Are we adding GeoIP as well? We get a fair few requests for that.

**Comment by nataliejeremy** [comment]
@slashzero Is this ready to be merged or are you going to be adding more to it?

**Comment by slashzero** [comment]
Let's merge for now, I do want to add more - for example how to see which libraries are available - but that can wait for a few days when I'll have time.

**Comment by nataliejeremy** [comment]
Thanks! @slashzero

**Pull request merged**
