### PR TITLE
Upgrade PHP Versions 

### LINKED ISSUE #1755: Use pantheon.yml to select PHP version
Re: https://pantheon.io/docs/php-versions/

## Issue Description

As a developer
I want to configure the PHP version via pantheon.yml
So it's managed in version control

Add a pantheon.yml file to the root of your codebase that includes a line like the following:

```
php_version: 5.6
```
Available versions: 5.3, 5.5, 5.6, 7

### PR DESCRIPTION
**Pull request by nataliejeremy**
Closes #1755 

## Effect
PR includes the following changes:
- Adds available PHP versions and how to configure via the pantheon.yml file

@rachelwhitton and @ari-gold please review--thanks!

### CODE REVIEW

**Comment by ari-gold** [comment]
@nataliejeremy This looks great. Please also remove any reference to `terminus site set-php-version`, which we will deprecate in favor of setting it in pantheon.yml so it can be managed in version control.

**Comment by rachelwhitton** [comment]
@nataliejeremy looks great! Can we rephrase the last sentence in [Selecting a Plan](https://pantheon.io/docs/select-plan/#manage-site-settings) doc within this PR?
> After you get to your site's Dashboard, click the Settings link in the upper-right corner. This is where you can select add ons and PHP versions.

**Comment by rachelwhitton** [comment]
Should [docs/pantheon-yml](https://pantheon.io/docs/pantheon-yml/) be updated as well?

**Comment by nataliejeremy** [comment]
@ari-gold is this one ready to be merged?

**Comment by ari-gold** [comment]
@nataliejeremy Not quite. Thanks for checking in, though! =)

**Comment by rachelwhitton** [comment]
+1

**Comment by rachelwhitton** [comment]
Deploy early as terminus is already updated. 

```
$ terminus site set-php-version --site=anita-wordpress --env=dev
  1. default
  2. 5.3
  3. 5.5

Select a PHP version: 2

[2016-08-15 23:18:02] [error] Sorry, setting the PHP version has moved to pantheon.yml. You can find out how to change it here: https://pantheon.io/docs/php-versions/
```

**Pull request merged**
