### PR TITLE
Add -all option to upstream:list

### PR DESCRIPTION
**Pull request by jackfoust**
Gets the unfiltered list of all available products.

Closes #

## Effect
PR includes the following changes:
-
-

## Remaining Work
- [ ] List any outstanding work here
- [ ] Technical review
- [x] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Archive from **Done** in [Main Project](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
@jackfoust if you would [allow remote changes](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to this PR, I can update it for the new Gatsby build.

**Comment by alexfornuto** [comment]
CC @greg-1-anderson @stevector - Do you agree with displaying the full list in the docs?

**Comment by jackfoust** [comment]
Hi @alexfornuto “Allow edits from maintainers.” is already selected. Is there another step I’m missing?

**Comment by alexfornuto** [comment]
@jackfoust hmmm, apparently that only lets me edit in GItHub, not push from git. There are too many changes for that. If you have a local copy of that branch, would you mind running:

```
git remote add upstream git@github.com:pantheon-systems/documentation.git
git checkout patch-11
git pull --rebase upstream master -Xtheirs
git push origin patch-11 --force
```

Or, I could just remake this change, which is trivial. I just want to give you the option to keep your commit in history.

**Comment by jackfoust** [comment]
@alexfornuto TBH I'm not sure I'll get to this until Tuesday. You won't hurt my feelings closing this PR and doing your thing so that I don't hold you up!

**Comment by alexfornuto** [comment]
Well I'd like @greg-1-anderson or another's input first anyway, so we have time.

**Comment by allenfear** [comment]
LGTM @alexfornuto

**Comment by alexfornuto** [comment]
Thanks @jackfoust!

**Pull request merged**
