### PR TITLE
create unsupported modules page

### PR DESCRIPTION
**Pull request by nataliejeremy**
@ari-gold @suzannealdrich Please review and update. if you know of any WP plugins that aren't supported, please add them. 

This closes issue #377

### CODE REVIEW

**Comment by ari-gold** [comment]
@nataliejeremy  This is great! I think we should link to this doc from https://pantheon.io/docs/articles/sites/known-limitations/ and move the HTTPRL and Background Process modules from known limitations into this new doc. 

Same with https://pantheon.io/docs/articles/wordpress/wordpress-known-issues/#unsupported-plugins

**Comment by nataliejeremy** [comment]
@ari thanks! I just updated the docs.

**Comment by ari** [comment]
@nataliejeremy  Can you please stop adding me to your discussions. I've got nothing to do with this project.

**Comment by nataliejeremy** [comment]
@ari-gold Thanks--it's updated now.

**Comment by rachelwhitton** [comment]
Can we group the Drupal modules that are not supported due to the use of the `tmp` dir and provide a single issue and resolution explanation? 

Several modules have **/tmp** next to the name but the explanation for why it's not supported is found under another module. 

Also, the WP plugins are linked to the WP Repo - should we link the modules to the project repos?

**Comment by nataliejeremy** [comment]
@rachelwhitton I moved the WP from the WP known issues doc, and they were already linked. I don't see the point in linking any of them since they are not supported and we aren't recommending they use them. 
Can you add the explanation for why they aren't supported? This info wasn't in the issue...awaiting more input from CSE.

**Comment by rachelwhitton** [comment]
@nataliejeremy I combined the `/tmp` modules into a single section:
screen shot 2015-06-18 at 10 47 51 am


+1

**Comment by nataliejeremy** [comment]
+1 thanks @rachelwhitton

**Pull request merged**
