### PR TITLE
Warning re:changing gitignore defaults

### PR DESCRIPTION
**Pull request by sukottokun**
Edit or move as you see fit. Letting users know that commenting out composer-managed directories will lead to failed builds, often without any clear errors surfaced on their side. This started on Zendesk #605083 and continued on Pantheon APAC Slack. I'd like to offer this should be added to the D9 drops .gitignore ~ line 30, LMK if you want me to make a PR there, too. I see at least 20 similar failed jobs with similar error messages in slack, but not sure if they are all the same.

Closes #

## Summary

**[Doc Page Title](https://pantheon.io/docs/doc-title)** -  <Enter a one sentence summation of the pertinent changes (including not-yet-completed work) provided by this PR.>

## Effect

The following changes are already committed:

*
*

## Remaining Work

The following changes still need to be completed:

- [ ] List any outstanding work here

--------------------------------------------------
## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6610](https://pr-6610--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `62` | `57.99999999999999` | `-4` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6610` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/29438/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/29438/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6610--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by sukottokun** [comment]
I discussed this briefly with @alexdicianu , maybe @greg-1-anderson might have thoughts if it belongs somewhere else. I'd recommend pretty strong wording.

**Comment by greg-1-anderson** [comment]
Yeah just saw this and was thinking that stronger wording should be used. It is a requirement that all of your build artifacts be ignored in the .gitignore file. This means that not only is it bad to change the .gitignore to un-ignore existing artifacts, it is also important to add entries to the .gitignore any time you alter the build to place installation files in new locations.

**Review by joa-pan — APPROVED** [review]
LGTM

**Pull request merged**
