### PR TITLE
Use GitHub commit log style Newer/Older paging instead of Previous/Next

### PR DESCRIPTION
**Pull request by ari-gold**
also auto-indenting

### CODE REVIEW

**Comment by ari-gold** [comment]
@rachelwhitton pls review

**Comment by rachelwhitton** [comment]
+1 Thank you @ari-gold! The auto-indenting is slick!
## Example Changelog Post
screen shot 2015-07-17 at 5 05 33 pm

**Comment by rachelwhitton** [comment]
@nataliejeremy can you review?

**Comment by nataliejeremy** [comment]
+1

**Pull request merged**
