### PR TITLE
Add ewww_image_optimizer

### PR DESCRIPTION
**Pull request by slashzero**
Stores absolute image path in db

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
I'm curious what the "container ID" is in the file paths stored here. Is this the site uuid, or is this some internally-created ID value?  Maybe something calculated based on the database credentials?

**Comment by rachelwhitton** [comment]
@greg-1-anderson Refers to the application container's binding ID, which is created internally.


@slashzero If multiple application containers are serving the site, would the resolution here work?

**Comment by greg-1-anderson** [comment]
Ah, I see; the code is using something like `realpath` and writing the full absolute path to the file into the database.  It seems like the proposed description of this situation in this PR is only applicable to sites with a single app server. I believe that @rachelwhitton is correct, and this plugin simply cannot be used if the site has multiple app servers.

**Comment by rachelwhitton** [comment]
+1 I removed the recommended solution and clarified the issue for sites served by multiple app servers. Can you review @slashzero?

**Comment by slashzero** [comment]
+1 plugin won't be able to work on multiple app servers.

**Pull request merged**
