### PR TITLE
[CMSO-1267] Rotate salts and keys documentation.

### PR DESCRIPTION
**Pull request by kporras07**
## Summary

**[Environment-Specific Configurations for Drupal](https://docs.pantheon.io/guides/environment-configuration/environment-specific-config-drupal)** - Add section about rotating salts

**[Environment-Specific Configurations for Wordpress Sites](https://docs.pantheon.io/guides/environment-configuration/environment-specific-config)** - Add section about rotating salts

## Effect

The following changes are already committed:

* Terminus command is now available

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] Terminus release should be created and corresponding docs PRs should be merged

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Review by namespacebrian — APPROVED** [review]

**Comment by whitneymeredith** [comment]
@kporras07 The link to the Terminus command is 404ing. Do you know if there's an example of the command being added to the directory? https://docs.pantheon.io/terminus/commands

**Comment by whitneymeredith** [comment]
[Preview](https://pr-8309-documentation.appa.pantheon.site/guides/environment-configuration/environment-specific-config#rotate-authentication-unique-keys-and-salts)

**Comment by kporras07** [comment]
@whitneymeredith this command is from the newest terminus release. It's 404'ing because the automation PR has not yet been created/merged.

I think it usually gets created around EOD so once it's merged the link will work.

**Comment by kporras07** [comment]
@whitneymeredith this is now ready to merge and link is working: https://docs.pantheon.io/terminus/commands/env-rotate-random-seed

**Pull request merged**
