### PR TITLE
add strpos for specialchar user agents

### PR DESCRIPTION
**Pull request by EdwardAngert**
Closes: #6281 

## Summary

**[Investigate and Remedy Traffic Events](https://pantheon.io/docs/optimize-site-traffic)** - Add `strpos` to examples on how to block user agents.

## Effect

The following changes are already committed:

-
-

## Remaining Work

The following changes still need to be completed:

- [ ] List any outstanding work here

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6286](https://pr-6286--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `60` | `57.99999999999999` | `-2` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6286` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/26232/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/26232/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6286--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by jdpantheon** [comment]
i think it's flawed so going to close it for now

**Comment by EdwardAngert** [comment]
after talking with @jdpantheon, I'm reopening this PR and moving it to blocked while we work out some cleaner php for it
looks like the idea is correct, but the way we're trying to do it needs some love

**Comment by sarahg** [comment]
@EdwardAngert I just pushed a few commits that I think will close this out after a review. I updated:

- code examples (use `strpos` function to compare strings)
- note the difference between DDoS and DoS. A regular DoS is much more common and straightforward to stop; an actual _DDoS_ is more difficult to mitigate at this level because IPs and/or user-agents vary and can be numerous -- realistically our advice is more effective for a DoS.
- don't recommend the wp-ban plugin since it does not function quite right on the platform (and we document this elsewhere)

**Comment by EdwardAngert** [comment]
thanks @sarahg ! Looks like when we say "hey, don't use wp-ban" we also point to this doc :-| so that's an extra good fix here
moving this to copy review 🚀

**Review by joa-pan — APPROVED** [review]
LGTM

**Pull request merged**
