### PR TITLE
Drush limitation with value of ['uri'] in pantheon.aliases.drushrc.php

### PR DESCRIPTION
**Pull request by timani**
Sanitized the info from the commands, the formatting may need some work.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Maybe we should recommend using a policy file here, so the user does not have to re-edit on every download of their Pantheon aliases.

**Comment by timani** [comment]
I am all for that business of adding a policy file too. Initial recommendation in the card was to edit but that is a better option

**Comment by greg-1-anderson** [comment]
Someone wrote a blog post: https://pantheon.io/blog/fix-drush-site-aliases-policy-file  :smile:

**Comment by timani** [comment]
Bloggers!

**Comment by greg-1-anderson** [comment]
The policy file is already discussed (complete with a link to the blog post).  Maybe the link should point to #drush-alias-strict-control?

Also, the existing examples show changing the `drush` script. Maybe it would be helpful to have another example here that says `if alias uri == wrong.example.com then alias uri = example.com`.

**Comment by greg-1-anderson** [comment]
@rachelwhitton: Should I literally use `wrong.example.com` and `example.com`?  Can you give some real-world examples of wrong and right domain names?

**Comment by greg-1-anderson** [comment]
See https://github.com/pantheon-systems/documentation/pull/1188 for proposed policy file documentation change.

**Comment by rachelwhitton** [comment]
+1 thanks @timani and @greg-1-anderson - @nataliejeremy can you review and merge?

**Pull request merged**
