### PR TITLE
Crisis Response Upstream Updates

### PR DESCRIPTION
**Pull request by alexfornuto**
Continues: #5621 

## Summary

**[Crisis Response Upstream](https://pantheon.io/docs/crisis-response-upstream)** - Updated the plugin list based on content in the upstream, updated the instructions based on changes made to the Quicksilver deployment script.

## Effect

The following changes are already committed:

- Removed Autoptimize from the plugins, doesn't provide as much gains for smaller sites.
- Added Contact Form 7 and Essential Addons for Elementor (used in default content).
- Updated launch instructions based on the Quicksilver script that runs (resets the user password via WP CLI).
- Add Kyle Taylor to Contributors file
- Copy Edits

## Remaining Work

The following changes still need to be completed:

- [x] Validate Contributor information.

## Post Launch

- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5622 | Difference |
| --- | --- | --- | --- |
| Performance Score | `57.99999999999999` | `48` | `-10` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5622` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19640/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19640/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by carolyn-shannon** [comment]
@kyletaylored does the updated repo take into account the known issues using [Contact Form 7](https://pantheon.io/docs/plugins-known-issues#contact-form-7) on the Pantheon env?

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5622 | Difference |
| --- | --- | --- | --- |
| Performance Score | `72` | `44` | `-28` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `96` | `-2` |

Lighthouse Audit Reports:

- [`pr-5622` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19656/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19656/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by kyletaylored** [comment]
> @kyletaylored does the updated repo take into account the known issues using [Contact Form 7](https://pantheon.io/docs/plugins-known-issues#contact-form-7) on the Pantheon env?

@carolyn-shannon Yep! I have the patch in wp-config here.

https://github.com/the-scranton-branch/crisis-response-wp/blob/master/wp-config.php#L160

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5622 | Difference |
| --- | --- | --- | --- |
| Performance Score | `50` | `48` | `-2` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5622` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19666/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19666/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5622 | Difference |
| --- | --- | --- | --- |
| Performance Score | `54` | `48` | `-6` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5622` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19671/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19671/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Pull request merged**
