### PR TITLE
[Release Note] Invite to pay experience upgraded 

### PR DESCRIPTION
**Pull request by carly-armstrong**
Adds a new release note for enhanced "Invite to pay" flow in the dashboard 

[Preview link](https://pr-9338-documentation.appa.pantheon.site/release-notes/2024/12/Invite-to-Pay-Upgrade)

### CODE REVIEW

**Comment by carly-armstrong** [comment]
Invite to Pay

**Comment by IngridKwok** [comment]
@carly-armstrong Fixed some of the issues in the release note and file name. I think it's great to include a screenshot to show the changes in user interface.

**Comment by rachelwhitton** [comment]
@carly-armstrong is it possible to get something similar to the [image used here](https://docs.pantheon.io/release-notes/2024/11/new-dashboard-nav)? Where we can see the difference between the old and new flows?

**Comment by IngridKwok** [comment]
@carly-armstrong @rachelwhitton Made another pass at the copy.

**Comment by rachelwhitton** [comment]
Closing per [convo in slack](https://pantheon.slack.com/archives/C02L96HF649/p1733343660254009?thread_ts=1733341305.771639&cid=C02L96HF649)

**Pull request closed without merging**
