### PR TITLE
[CORE-1429] Updated DNS instructions to use A records instead of CNAME

### PR DESCRIPTION
**Pull request by eduardbulai**
Closes #

## Effect
PR includes the following changes:
- Removed references to any external CNAME documentation
- Updated the DNS instructions to use A records whenever CNAME records were instructed/recommended

## Remaining Work
- [ ] Cloudflare instructions need to be reviewed (current instructions are outdated) and then changed to replace the CNAME instructions with A records
- [x] Remove old assets (screenshots)
- [ ] Technical review
- [ ] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Archive from **Done** in [Main Project](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by EdwardAngert** [comment]
closes #4905

**Comment by EdwardAngert** [comment]
closes #4973

**Comment by EdwardAngert** [comment]
not sure why the bot closed this
stay tuned

**Comment by alexfornuto** [comment]
Thanks @eduardbulai!

**Pull request merged**
