### PR TITLE
Account Management Guide-ification: Part 2

### PR DESCRIPTION
**Pull request by EdwardAngert**
Closes #

## Summary

**[Account Management at Pantheon](https://pantheon.io/docs/manage)** - Another round of consolidating Pantheon account management documentation.

## Effect

The following changes are already committed:

* removed placeholder
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] Assess and edit or repoint docs that should be part of account mgmt guide
   - [ ] [New Site Owner FAQs](https://pantheon.io/docs/site-owner-faq)
   - [ ] [Add a Client Site to Your Organization Dashboard](https://pantheon.io/docs/add-client-site)
   - [ ] [Accessing an Account After the Owner Leaves](https://pantheon.io/docs/site-access)
   - [ ] [Role-Based Permissions & Change Management](https://pantheon.io/docs/change-management)
   - [ ] [Managing Sites and Teams with the Pantheon Organization Dashboard](https://pantheon.io/docs/organization-dashboard)
   - [ ] [Manage Plans in the Site Dashboard](https://pantheon.io/docs/site-plan)
   - [ ] [Pantheon Organizations FAQs](https://pantheon.io/docs/organization-faq)
   - [ ] [Account Billing in the User Dashboard](https://pantheon.io/docs/account-billing)
- [ ] Update all links/references

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by EdwardAngert** [comment]
| Redirect from                 | to                                 |
|:------------------------|:---------------------|
| docs/guides/account-mgmt                   | docs/manage                   |

**Comment by wordsmither** [comment]
@EdwardAngert: I continue to be stumped.  Here's what I've tried:

- page level redirects require a plugin so that's a no go
- I removed the contributor tag, which should have taken it off my contributor page, but it didn’t.
- I then changed contributor to whitney, which should have removed it from my page and added it to hers.  it added it to hers. AND it’s still on mine.

**Comment by wordsmither** [comment]
@EdwardAngert in a related note - all the pages you're recommending to add to the guide WERE added to the guide, then deleted, and finally, redirected, [as a part of my PR](https://github.com/pantheon-systems/documentation/pull/7719).  Not sure what's happening but I'm going to open a new job to delete and redirect those files again.

**Comment by EdwardAngert** [comment]
I thought it was the commas in some of the titles, then realized it's looking for a landing page, so I just duplicated the contents making `/manage` to `/account-mgmt`

it's probably not the best solution, but if it works, it's a solution

**Comment by EdwardAngert** [comment]
the regex on the contributors page is still written in a way that's funny about subdirs, but that's for later

this PR adds a landing page where gatsby expects one (account-mgmt) in addition to the existing (manage), so at least the links won't be broken

**Pull request merged**
