### PR TITLE
[fix] Subtopics alignment

### PR DESCRIPTION
**Pull request by digitalhydra**
## Effect
PR includes the following changes:
- subtopic alignment when dividing links in two groups

### CODE REVIEW

**Comment by digitalhydra** [comment]
Screen Shot 2019-09-25 at 8 14 45 PM

**Comment by carolyn-shannon** [comment]
I'm looking at this in FF, Safari, and Chrome (macOS) and the alignment of the second column of items is higher in all three than your screenshot. My concern is that it doesn't visually associate col 2 with the content in col1. What browser were you using?
column-alignment-pr-5154

**Comment by alexfornuto** [comment]
@digitalhydra it looks like this isn't working across the board:

image

**Comment by alexfornuto** [comment]
And if I move the separator up by one: 
image

**Pull request merged**
