### PR TITLE
add note on Pantheon Solr

### LINKED ISSUE #5252: Enabling Solr on Drupal 8 Doc Update
Re: [Enabling Solr on Drupal 8](https://pantheon.io/docs/solr-drupal-8)

Priority: High (choose one, remove the other options)

## Issue Description:
SOLR is not actually supported with Drupal 8 on Pantheon. The docs should be updated to reflect this. The documentation suggests using the `search_api_solr` module version 1.x. 

This module will be unsupported starting December 2019, meaning it's unsafe to use.

Additionally [it already states](https://www.drupal.org/project/search_api_solr/) for that version

> The minimum supported Solr version is Solr 4.5.1.

Which means that it probably doesn't already work with Apache Solr v3.6 which is [what's supported by Pantheon](https://pantheon.io/docs/solr).

## Suggested Resolution

Update the documentation to indicate to users that they can not safely use the SOLR service of Pantheon on Drupal 8 until a newer SOLR version is supported by Pantheon.

### PR DESCRIPTION
**Pull request by carolyn-shannon**
Closes #5252 

## Effect
PR includes the following changes:
- adds note re Pantheon Solr use case

## Remaining Work
- [ ] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5454 | Difference |
| --- | --- | --- | --- |
| Performance Score | `80` | `60` | `-20` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `93` | `-3` |

Lighthouse Audit Reports:

- [`pr-5454` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17871/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17871/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5454 | Difference |
| --- | --- | --- | --- |
| Performance Score | `81` | `59` | `-22` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `93` | `-3` |

Lighthouse Audit Reports:

- [`pr-5454` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17895/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17895/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5454 | Difference |
| --- | --- | --- | --- |
| Performance Score | `81` | `61` | `-20` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `93` | `93` | `0` |

Lighthouse Audit Reports:

- [`pr-5454` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17903/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17903/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by EdwardAngert** [comment]
would it also help to put the same note (or make a partial of it and insert it into) the [IndexDepot](https://pantheon.io/docs/indexdepot) doc?

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5454 | Difference |
| --- | --- | --- | --- |
| Performance Score | `81` | `66` | `-15` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `93` | `-3` |

Lighthouse Audit Reports:

- [`pr-5454` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17940/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17940/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5454 | Difference |
| --- | --- | --- | --- |
| Performance Score | `80` | `75` | `-5` |
| Best Practice Score | `93` | `86` | `-7` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `93` | `-3` |

Lighthouse Audit Reports:

- [`pr-5454` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17948/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/17948/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Pull request merged**
