### PR TITLE
Update the recommended s3 policy in s3 offload media

### LINKED ISSUE #8730: WordPress Developer's Guide Doc Update
Re: [WordPress Developer's Guide](https://docs.pantheon.io/guides/wordpress-developer/wordpress-s3)

Priority: High

## Issue Description:
Reviewed the policy outlined, it seems it is outdated as reported by 2 customers

## Suggested Resolution
update to:

```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "VisualEditor0",
			"Effect": "Allow",
			"Action": [
				"s3:PutObject",
				"s3:GetObject",
				"s3:DeleteObject",
				"s3:PutObjectAcl"
			],
			"Resource": "arn:aws:s3:::bucketname/*"
		},
		{
			"Sid": "BucketLevel",
			"Effect": "Allow",
			"Action": [
				"s3:GetBucketPublicAccessBlock",
				"s3:PutBucketPublicAccessBlock",
				"s3:PutBucketOwnershipControls",
				"s3:GetBucketOwnershipControls",
				"s3:GetBucketLocation"
			],
			"Resource": "arn:aws:s3:::bucketname"
		}
	]
}

### PR DESCRIPTION
**Pull request by carl-alberto**
Closes #8730

## Summary

Reviewed the policy outlined, it seems it is outdated as reported by 2 customers

## Effect

The following changes are already committed:

* updated s3 config in the PR
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by stevector** [comment]
@carl-alberto who else can review the accuracy of the change?

**Comment by miriamgoldman** [comment]
@stevector hi! I have verified that these settings do work. I tested on my sandbox site, and the files are directly offloaded to the S3 bucket. It should be noted that this PR _removes_ access to list the buckets, which is an option with the WP Offload Media plugin. Can we rely on customers to copy/paste their bucket name appropriately for configuration?

If so, I'd say this is a pass. If not, I can play around with the permissions and get the bucket listing going.

**Comment by stevector** [comment]
> Can we rely on customers to copy/paste their bucket name appropriately for configuration?

I've never used this plugin, but I just based on the level of prescriptive detail already in this page of Docs, I think that if we tell the reader that they need to copy/paste the bucket name that it'll be fine.

If you're trying this out on your own S3, can you take updated screenshots?

**Comment by miriamgoldman** [comment]
> > Can we rely on customers to copy/paste their bucket name appropriately for configuration?
> 
> I've never used this plugin, but I just based on the level of prescriptive detail already in this page of Docs, I think that if we tell the reader that they need to copy/paste the bucket name that it'll be fine.

Ok, great! I wasn't sure.

> If you're trying this out on your own S3, can you take updated screenshots?

Absolutely. I'll get that in tomorrow and tag you here/in Slack.

**Comment by miriamgoldman** [comment]
@stevector As I'm not a docs admin, I haven't actually hit the review button, but I've added the updated screenshot - and added a note where it talks about using the full S3 access permission regarding needing that if you want to list buckets. LGTM now. Off to you. 🙂

**Comment by stevector** [comment]
I'm removing the old `.png` and will review more once the preview deployment completes.

**Comment by stevector** [comment]
I'm not sure why deployments are failing here, investigating.

**Comment by stevector** [comment]
Thanks @miriamgoldman!!

**Pull request merged**
