### PR TITLE
DOCO-1004 AGCDN Custom Certs

### LINKED ISSUE #8379: Custom Certificates on Pantheon Advanced and Global CDN Doc Update
Re: [Custom Certificates on Pantheon Advanced and Global CDN](https://docs.pantheon.iocustom-certificates)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Modify the AGCDN section that it is just **about LEGACY AGCDN**

## Suggested Resolution
Remove the AGCDN section and highlight it as for Legacy AGCDN method.

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #8379 

## Summary

**[Custom Certificates](https://docs.pantheon.io/custom-certificates#ccagcdn)** - Added new tab and instructions for self service AGCDN custom certs and updated the legacy AGCDN tab.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by whitneymeredith** [comment]
[Preview](https://pr-8385-documentation.appa.pantheon.site/custom-certificates#add-a-custom-certificate)

**Comment by whitneymeredith** [comment]
@eabquina Let me know your thoughts on these changes.

**Comment by eabquina** [comment]
@whitneymeredith made some changes. Legacy AGCDN is same for that when we use certs.ps-pantheon.com. Streamlined AGCDN uses the same style as GCDN.

**Review by wordsmither — APPROVED** [review]
lgtm

**Pull request merged**
