### PR TITLE
Terminus for Windows 7

### LINKED ISSUE #2327: WIP - Doc on how to install terminus on Windows 7
Priority: Low

## Title
How to install Terminus on Windows 7

## Description
Prepared my draft here - https://docs.google.com/document/d/1pBF6XtZpRTOl2ar7onFlH5aXRkQ70K-e771uksdHl1M/edit

Most customers that I encountered with that are windows  are not so familiar with linux environment the steps or instruction on how to install terminus should be detailed and visually engaging.

## Expected Audience
Windows users

## Path
docs/terminus/windows7

### PR DESCRIPTION
**Pull request by fusionx1**
Closes #2327 

PR includes the following changes:
Markdown file 
Asset files

Remaining Work:
1. Review

### CODE REVIEW

**Comment by alexfornuto** [comment]
@fusionx1 I found a repeated error that fixed most of the images, but many others have incorrect paths and aren't displaying correctly. You can view your work in progress [here](https://paultermin-static-docs.pantheonsite.io/docs/terminus/windows7) and correct them.

Please also adjust your headers. Each step should not be it's own section, sections should be based on specific goals, and numbered within, like this:

```
## First goal.

1. Do this.

2. Then do this.

3. Finally, do this.

## Second goal

Description

### Optional Subsection? YOU BETTER BELIEVE IT!

1. Blah
2. Bleh
3. Blue

### Awww shiz, here comes ANOTHER SUBSECTION DAWG

1. word
2. up.
```

**Comment by rachelwhitton** [comment]
I'm going to work this into my queue for early next week - really appreciate the help, thanks @fusionx1!

**Comment by fusionx1** [comment]
Thanks Rachel and Alex, appreciate it, I will try to do the adjustment
later today.

Paul

**Comment by fusionx1** [comment]
Fixed missing images and updated contents

**Comment by rachelwhitton** [comment]
@fusionx1 really sorry for the long delays on this one, thank you so much for contributing!

After further discussion, I'd like to avoid driving folks towards cygwin in the docs. Recommending bash emulators (specifically git for windows with regards to Windows 7), provides smoother experiences for other methods of interfacing with the product.

**Pull request closed without merging**
