### PR TITLE
add Redirect to force lowercase letters

### PR DESCRIPTION
**Pull request by primerg**

### CODE REVIEW

**Comment by nataliejeremy** [comment]
Thanks for the update @primerg

**Comment by rachelwhitton** [comment]
Thanks @primerg! I spun up a [D8 site to test](http://dev-d8-rachwhits.pantheon.io/) this one but I'm getting a redirect error. Do you have a test site running the snippet I can refer to?

**Comment by alexdicianu** [comment]
@rachelwhitton looks good! +1

**Comment by rachelwhitton** [comment]
@primerg, thanks for the PR! @alexdicianu and I tested and decided to use to regex in favor of `ctype_lower()` 
 
:ship:

**Pull request merged**
