### PR TITLE
Serve traffic from your preferred domain (www or non-www)

### PR DESCRIPTION
**Pull request by ari-gold**
* Add "Serve traffic from your preferred domain (www or non-www)" section
  - Method 1: Add redirect from WordPress or Drupal
* Switch order of FAQ and Troubleshooting
* Add links to https://mxtoolbox.com/ and https://www.whatsmydns.net/
* Minor edits

Relates to BUGS-1040

### CODE REVIEW

**Comment by ari-gold** [comment]
@lauren-kelly  Can you please review?

**Comment by rachelwhitton** [comment]
@ari-gold @lauren-kelly are there any objections to removing the www-redirection service entirely from this doc and encouraging all users to redirect to a common domain within their sites configuration? I think new users would find the methods confusing (especially for the www section). It's hard to tell which one applies to HTTP

**Comment by allenfear** [comment]
@ari-gold it makes sense to me that we would stop surfacing the www-redirection service as an option at this point if it will not work with the Global Edge. Does that sound right to you?

**Comment by lauren-kelly** [comment]
Yeah - I think everyone I've sent the info to opted to just go ahead and add the redirect snippet. It makes more sense to keep all that logic together, I think - should someone take over a site or whatever.

**Comment by rachelwhitton** [comment]
@lauren-kelly can you review? Updated to remove the www-redirection service.

**Comment by ari-gold** [comment]
Haven't had a chance to review the changes, but **the www-redirection service will work for any site that is not using HTTPS**. It's still being recommended on some site dashboards, so might be good to keep it in. I'm also okay with removing it.

**Pull request merged**
