### PR TITLE
Lock Environment Doc New CI Scripting Section

### LINKED ISSUE #5853: Lock Environments - Add section on passing credentials to CI tools
Re: [Lock Environments with the Dashboard Security Tool](https://pantheon.io/docs/security)

Priority: Low

## Issue Description:
- For CI script users, when a site environment is locked using the dashboard security tool, you must configure your CI tool to pass the username and password on every request, or tests will not run. See this [Community thread](https://pantheon-community.slack.com/archives/C5EM55T0X/p1594140217382100) for details.

## Suggested Resolution
- Add a section on CI scripting authentication needs with example, eg 
'{"base_url" : "https://username:password@'$TERMINUS_ENV'-'$TERMINUS_SITE'.pantheonsite.io/"}'

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #5853 

## Summary

**[Lock Environments with the Dashboard Security Tool](https://pantheon.io/docs/security)** - I added a section for CI scripting considerations.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by whitneymeredith** [comment]
@EdwardAngert lighthouse / a11y comments weren't tested or included in the changes made to the doc.

**Comment by joa-pan** [comment]
@jane-gravityworks We created this PR to address this [issue](https://github.com/pantheon-systems/documentation/issues/5853). Does this work or resolve the issue you mentioned?

**Comment by joa-pan** [comment]
Hey @greg-1-anderson! Can you review and let us know if this is correct. Thanks a million

**Review by joa-pan — APPROVED** [review]
LGTM

**Pull request merged**
