### PR TITLE
Remove reference to Dashboard Credentials

### PR DESCRIPTION
**Pull request by kelly-mcgonnigle**
Remove reference to Dashboard Credentials on 4/30 when this workflow is deprecated.

## Summary

**[SFTP Connection Info](https://docs.pantheon.io/guides/sftp/sftp-connection-info#dashboard-credentials)** - Removing reference to the dashboard credentials authentication method for SFTP on April 30 when we deprecate this option.

### Dependencies and Timing

- [ ] Merge this PR near EOD April 30th after approval from Kelly O'Donnell (exact timing and coordinating with the removal of this feature is not necessary)

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)

### CODE REVIEW

**Comment by stevector** [comment]
@kelly-mcgonnigle how will old versions of Terminus handle this change? For instance, what will return for people who run 

```
terminus connection:info sitename.dev  --field=sftp_username
```

**Comment by stevector** [comment]
That field is still in https://docs.pantheon.io/terminus/commands/connection-info (which, to my knowledge, is generated off of the Terminus codebase/help text)

**Comment by stevector** [comment]
@kelly-mcgonnigle do we need a more thorough audit of potential references to passwords? I see some in these pages and there are probably more:

* https://docs.pantheon.io/guides/sftp/sftp-connection-info#sftp-connection-info
* https://docs.pantheon.io/guides/wordpress-git/
* https://docs.pantheon.io/guides/wordpress-git/themes/

Is it just SFTP that's ending password auth? What about Drush/wp-cli and rsync?

**Comment by kelly-mcgonnigle** [comment]
@stevector thanks for flagging those pages. I'm gathering all of the references to this verification method [here](https://docs.google.com/spreadsheets/d/1Rj3f2hwYPJX2URqgQaw2VFglx0WMag2gkyoqbIx_WCg/edit?usp=sharing)

**Review by kelly-mcgonnigle — COMMENTED** [review]
approved

**Review by kelly-mcgonnigle — COMMENTED** [review]
approved

**Pull request merged**
