### PR TITLE
Issue 4008 incorrect screenshot

### LINKED ISSUE #4008: Ignore composer.lock and composer.json? (No CI)
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description:

In the image below "Now let’s run git status again to make sure everything is included." on these docs, the only modified file is .gitignore, but when I follow the instructions, I also see composer.json and composer.lock as modified. Should those files be ignored?

### PR DESCRIPTION
**Pull request by ataylorme**
Closes #4008

## Effect
PR includes the following changes:
- Updates existing screenshot installing Drupal 8 with Composer
- Adds a new screenshot showing `git status` before `.gitignore` is edited
- Adds the `-A` flag to the `git add` command to include deleted items

## Post Launch
To be completed by the docs team upon merge: 
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Archive from **Done** in Waffle

### CODE REVIEW

**Comment by ataylorme** [comment]
@baisong mind reviewing the updated screenshots and guide tweaks? I want to make sure I clarified your concern for future users of the guide

**Comment by baisong** [comment]
Hmm... Not what I saw.

drops-8-composer-git-status-after-installing-d8
When I followed the instructions earlier today, the only difference I saw from the current screenshot (below) is that in the `Changes not staged for commit` section, I saw two additional lines after `modified: .gitignore`:

```
modified: composer.json
modified: composer.lock
```

**Comment by baisong** [comment]
Hmm... Not what I saw.

drops-8-composer-git-status-after-installing-d8
When I followed the instructions earlier today, the only difference I saw from the current screenshot (below) is that in the `Changes not staged for commit` section, I saw two additional lines after `modified: .gitignore`:

```
modified: composer.json
modified: composer.lock
```

drops-8-composer-git-status-after-installing-d8

**Comment by alexfornuto** [comment]
Thanks for taking care of this @ataylorme!

**Comment by ataylorme** [comment]
@alexfornuto can you revert this merge? Based on @baisong feedback we are seeing different things and I want to ensure we have the correct screenshot before merging.

**Pull request merged**
