### PR TITLE
Using PHPMyAdmin doc- simplify download/install instructions

### LINKED ISSUE #1127: Using PHPMyAdmin to Locally Administer a Database Doc Update
Re: [Using PHPMyAdmin to Locally Administer a Database](https://pantheon.io/docs/articles/local/using-phpmyadmin-to-locally-administer-a-database)

1. Link within the **Download PHPMyAdmin** section leads to tangental Pantheon doc: [Accessing MySQL Databases](https://pantheon.io/docs/articles/local/accessing-mysql-databases/), but the preceding statement suggests it will lead to the GitHub repository for PHPMyAdmin or documentation for the recommended installation method:

 > The recommended way to get a copy of PHPMyAdmin is to download it via GitHub. For instructions, see [Accessing MySQL database](https://pantheon.io/docs/articles/local/accessing-mysql-databases/).

 **Suggested Resolution**: Revise last sentence content, and link new text to PHPMyAdmin docs http://docs.phpmyadmin.net/ 

2. Missing Pantheon specific installation instructions. Where do users unpack the zip archive downloaded from GitHub? [PHPMyAdmin docs](http://docs.phpmyadmin.net/en/latest/setup.html#quick-install) say: 

 > Untar or unzip the distribution (be sure to unzip the subdirectories): `tar -xzvf phpMyAdmin_x.x.x-all-languages.tar.gz` in your webserver’s document root. If you don’t have direct access to your document root, put the files in a directory on your local machine, and, after step 4, transfer the directory on your web server using, for example, ftp.

 **Suggested Resolution**: Test installation, document any instructions that are not aligned with PHPMyAdmin Quickinstall doc, review with CSE. Test it yourself.

PHPMyAdmin is a commonly used and familiar tool for WP developers, the **entire doc** should be revised so it's painfully obvious how to download and install this tool on a local machine and ultimately leave the user with an easily established connection to any one of their remote environment databases.

### PR DESCRIPTION
**Pull request by nataliejeremy**
Closes #1127 
This PR is to simplify the download instructions for PHPMyAdmin. The preferred download method is through the link I added. I also added a link to their docs for help with installation, etc. 

@slashzero  Please review the changes.

### CODE REVIEW

**Comment by rachelwhitton** [comment]
It may be a bit early for the PR stage on this issue, I was hoping to confirm the installation steps by testing in triage. The doc should tell users where to place the archive. The *Connect to the Database* section is also vague, we should clarify the steps to verify a successful connection. I was hoping for the entire doc to get revised so it could be valuable. @nataliejeremy @bmackinney let me know what you think.

**Comment by nataliejeremy** [comment]
I just updated the download section to be accurate. Their Github repo doesn't mention a zip file and states the preferred download method is at the link I added. 
As for the Connect to the Database section, I think the header could be revised. We aren't providing instructions on that, but just informing them where to find the icon to connect. Do we need further instructions? Deferring to @bmackinney

**Comment by ari-gold** [comment]
It might also be worth directing people to something like Sequel Pro, which is much easier to install and offers comparable features to PHPMyAdmin. 

We link to Sequel Pro, MySQL Workbench, and Navicat on https://pantheon.io/docs/articles/local/accessing-mysql-databases/  (maybe they should be moved to a subsection that can be link to directly)

**Comment by rachelwhitton** [comment]
@ari-gold Sequel Pro is easy to install and connect, but it's only for Mac OS X correct? 

Is PHPMyAdmin compatible on the platform? [Requirements page](http://docs.phpmyadmin.net/en/latest/require.html) says PHP 5.5 with `sessions` support. Just tested on a Pantheon WP site (default PHP 5.3), I get: 
```
Fatal error: session_start(): Failed to initialize storage module: user (path: ) in /srv/bindings/SITE_UUID/code/phpMyAdmin/libraries/session.inc.php on line 83
```
I haven't tried creating a config file, I was trying to use the [setup script](http://docs.phpmyadmin.net/en/latest/setup.html#using-setup-script).

**Comment by ari-gold** [comment]
@rachelwhitton  The instructions are to install PHPMyAdmin locally so you can remotely access your Pantheon database, like you would do with SequelPro, Workbench, or Navicat (all which would be easier to install because they are just apps and they don't require a webserver like PHPMyAdmin does)

**Comment by rachelwhitton** [comment]
Awesome, thanks @ari-gold! I'm able to connect using all three we mention in the existing doc: [SequelPro](http://www.sequelpro.com/download), [Navicat](http://www.navicat.com/download/navicat-for-mysql), and [Workbench](http://dev.mysql.com/downloads/workbench/). Is anyone in favor of just deleting [this doc](https://pantheon.io/docs/articles/local/using-phpmyadmin-to-locally-administer-a-database/) and redirecting to [Accessing MySQL Databases](https://pantheon.io/docs/articles/local/accessing-mysql-databases/)? @bmackinney @nataliejeremy

**Comment by bmackinney** [comment]
Agree - delete it. Possibly reference it as a possibility and link out to phpmyadmin docs.

**Comment by nataliejeremy** [comment]
Agree @bmackinney and @rachelwhitton I'll submit a new PR and close this one.

**Comment by nataliejeremy** [comment]
Closing this PR in favor of issue #1161

**Pull request closed without merging**
