### PR TITLE
Add warning about migration duration

### PR DESCRIPTION
**Pull request by slashzero**
Closes #

## Effect
PR includes the following changes:
-
-
-

## Remaining Work
- [ ] List any outstanding todos
- [ ] If needed

### CODE REVIEW

**Comment by ari-gold** [comment]
@slashzero How about adding this as a FAQ at the bottom instead of a big warning on the top?

**Comment by slashzero** [comment]
@ari-gold Sounds good, there will be other issues that'll come up

**Comment by ari-gold** [comment]
I'll pull data on min/max/avg transfer time. Maybe we can look at that and update to say something like "Time to migrate your site depends on the site size. Most transfers are completed within X time, but if your site has a very large footprint it can take X time."

**Comment by nataliejeremy** [comment]
@ari-gold Were you able to pull the data? We'd like to get this one merged. Thanks!

**Comment by ari-gold** [comment]
Avg transfer time is just over an hour. This is the email sent out to folks when their migration is started:

> Most migrations to Pantheon are completed within 2 hours. Migration times depend fully on the size of your site, so be aware that it may take more or less time than estimated. Expect another email from us once your migration is complete. On the off-chance there are hiccups along the way, we will notify you by email.

**Comment by nataliejeremy** [comment]
Thanks! @slashzero and @ari-gold

**Pull request merged**
