### PR TITLE
Update Cloudflare domain configuration

### PR DESCRIPTION
**Pull request by ari-gold**
No need to redirect in PHP if doing via CF.

### CODE REVIEW

**Comment by davidstrauss** [comment]
I'd prefer that we encourage people to enable the Cloudflare "Action" to redirect to HTTPS, but we definitely should not be advising people to redirect in PHP when Cloudflare is in "orange cloud" mode.

**Comment by rachelwhitton** [comment]
@davidstrauss can you clarify how to enable the Action? I can't find seem to find it

Also, I haven't been able to stack Cloudflare so that multiple redirects happen in one response. Then again, single response may not be a blocker but defer to you and @ari-gold

**Comment by davidstrauss** [comment]
Here's the action to redirect to HTTPS:

screenshot from 2017-07-26 13-47-48

> Also, I haven't been able to stack Cloudflare so that multiple redirects happen in one response. Then again, single response may not be a blocker but defer to you and @ari-gold

There isn't really such a thing. It's more of a "can we get everything done in one redirect" question. For example, if I go to `http://example.com`, do I first get a redirect to `https://example.com` and then to `https://www.example.com`, or do I directly get the final URL as the redirect?

**Comment by rachelwhitton** [comment]
+1

**Pull request merged**
