### PR TITLE
Built-in maintenance mode works for WordPress too

### PR DESCRIPTION
**Pull request by ari-gold**
http://codex.wordpress.org/Function_Reference/wp_maintenance

Tested and confirmed working on http://dev-ari-wp.pantheon.io/  

Screenshot:
screenshot 2015-10-05 13 03 02

followed http://www.stevendobbelaere.be/how-to-enable-the-wordpress-maintenance-mode/

### CODE REVIEW

**Comment by ari-gold** [comment]
@nataliejeremy  Please review and merge

**Comment by nataliejeremy** [comment]
Thanks! @ari-gold

**Comment by rachelwhitton** [comment]
Thanks @ari-gold!

@nataliejeremy - I moved the content around a bit to clarify the exact limitation we are communicating, which is that platform errors can't be customized. Can you review again and give a +1 if you agree with the changes?

**Comment by nataliejeremy** [comment]
+1

**Pull request merged**
