### PR TITLE
Update change-management.md to show developer site role is Enterprise only

### PR DESCRIPTION
**Pull request by lauren-kelly**
Closes #

## Effect
PR includes the following changes:
- Clarification that only Enterprise Orgs can assign Developer Roles on Sites

## Remaining Work
- [ ] Check with @1dwaynemcdaniel to make sure this is accurate

### CODE REVIEW

**Comment by lauren-kelly** [comment]
@rachelwhitton I just C&P'd that in from above and edited the message

**Comment by rachelwhitton** [comment]
Nice!! Thanks for the PR @lauren-kelly! Much appreciated 

+1

**Comment by rachelwhitton** [comment]
Actually, I checked with @1dwaynemcdaniel on this and we decided to revert. Seems as if that's not accurate @lauren-kelly

**Comment by 1dwaynemcdaniel** [comment]
This seems right to me.  Org level is correct above it and the individual site permissions is not available outside of an Enterprise org I believe

**Comment by rachelwhitton** [comment]
Thanks @1dwaynemcdaniel! I added this directly on master within commit 2715a583cadf7620bd2c27fa8ca949086cf04c8a

**Pull request merged**
