### PR TITLE
Object Cache Flush Cache Update

### LINKED ISSUE #7697: Object Cache (formerly Redis) Doc Update
Re: [Object Cache (formerly Redis)](https://pantheon.io/docs/object-cache)

Priority: Medium

## Issue Description:
On https://pantheon.io/docs/object-cache#clear-cache-in-pantheon-dashboard, it explicitly says:

> You can clear the Object Cache through the [Pantheon Dashboard](https://pantheon.io/docs/clear-caches#pantheon-dashboard)...

This may lead customers (even me) that it was referring to the **Clear Cache** button on every environment which is misleading. From what I have confirmed, along with some seniors of the CSE team, the **Clear Cache** button doesn't cover flushing Redis cache and hence needs to be done manually on Redis-CLI.

I was under the impression, even before, that the **Clear Cache** button doesn't really flush Redis cache until I stumbled back into this section of the documentation and confused my impressions.

## Suggested Resolution

Remove the first sentence since the succeeding one appears to be enough of an explanation for flushing the Redis cache.
or
Replace the first sentence mentioned making sure there will be no confusion in this section of the doc.

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #7697 

## Summary

**[Object Cache](https://pantheon.io/docs/object-cache#clear-cache-in-pantheon-dashboard)** - Removed steps to flush cache from the Pantheon dashboard.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7698](https://pr-7698--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `48` | `47` | `-1` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7698` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/41795/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/41795/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7698--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by whitneymeredith** [comment]
Preview

**Comment by whitneymeredith** [comment]
@jms-pantheon Can you please review this update and make sure it is accurate?

**Review by jms-pantheon — CHANGES_REQUESTED** [review]
I think the intent of the removed text here is correct, to say that hitting the clear cache button in the dash or via Terminus does in fact invalidate all the Redis-stored object caching and causes them to not be used, but it doesn't in fact _delete_ theme as a `flushall` command would. I generally like to think of the `flushall` as a last resort when things are not behaving as expected through the usual clear cache, for instance if a cached item is preventing Drush or WP CLI from working.

**Comment by whitneymeredith** [comment]
@jms-pantheon Do you have any ideas on how we can keep this information but update it to address the comments here: https://github.com/pantheon-systems/documentation/issues/7697 ?

**Review by jms-pantheon — APPROVED** [review]

**Comment by whitneymeredith** [comment]
LGTM

**Pull request merged**
