### PR TITLE
WECS-95 implement multi category filtering on release notes

### PR DESCRIPTION
**Pull request by mel-miller**
This PR updates the PDS toolkit to the latest version and implements updates to the site's release notes section, including adding a multi-category filtering mechanism and minor style updates.

Some highlights include:
- A dropdown with checkboxes to allow multiple filters to be selected.
- The ability to remove filters by removing a tag with its "x" button.
- Args in the URL to be able to link directly to the page with multiple category filters applied.

@IngridKwok -- has already approved this work for language and functionality. 
@mel-miller  -- has approved from a code standpoint.

### CODE REVIEW

**Review by stevector — CHANGES_REQUESTED** [review]
With the addition of https://pr-9001-documentation.appa.pantheon.site/release-notes?category=policy as a URL pattern, should we remove the pattern of https://pr-9001-documentation.appa.pantheon.site/release-notes/policy which uses the old style selector?

**Comment by mel-miller** [comment]
> With the addition of https://pr-9001-documentation.appa.pantheon.site/release-notes?category=policy as a URL pattern, should we remove the pattern of https://pr-9001-documentation.appa.pantheon.site/release-notes/policy which uses the old style selector?

@stevector -- Yeah, it would be cleaner. I asked Gustavo to leave it for now, because I wasn't sure if those links were being published/used anywhere. But if you're not concerned, we could certainly remove them.

**Comment by mel-miller** [comment]
@gfbollingerHakuna -- Please see the comment above about removing the old single-page filter pattern. They are okay with removal now that we have the new one.

**Comment by mel-miller** [comment]
@stevector -- The requested changes have been made. This should be good to go.

**Review by stevector — APPROVED** [review]

**Pull request merged**
