### PR TITLE
add warning for image breakages

### PR DESCRIPTION
**Pull request by nataliejeremy**
This closes issue #479 @timani please review--thanks,

### CODE REVIEW

**Comment by timani** [comment]
+1

**Comment by ari-gold** [comment]
@timani @nataliejeremy I know I'm late to the party here, but I think this should be moved out of distributions section to a new heading, something like:

Importing Automatically Updates Core

We automatically upgrade to the latest version of core during import. It's a best practice to keep core up-to-date to benefit from security and bug fixes, but if you use a site or distribution that relies on an outdated version of core you may experience incompatibilities. If you experience problems during your site upgrade, see the troubleshooting documentation for your upstream ([WordPress](https://codex.wordpress.org/Updating_WordPress#Troubleshooting), [Drupal](https://www.drupal.org/troubleshooting)

**Comment by nataliejeremy** [comment]
@ari-gold Thanks. Can you take one last look?

**Comment by ari-gold** [comment]
:+1:

**Comment by nataliejeremy** [comment]
@rachelwhitton Can you merge this? Thx!

**Pull request merged**
