### PR TITLE
Object Cache (formerly Redis) Doc Update

### LINKED ISSUE #6727: Object Cache (formerly Redis) Doc Update
Re: [Object Cache (formerly Redis)](https://pantheon.io/docs/object-cache)

Priority: Medium

## Issue Description: Drupal 8 (and 9) setup in settings.php has:

  // Include the Redis services.yml file. Adjust the path if you installed to a contrib or other subdirectory.
  $settings['container_yamls'][] = 'modules/redis/example.services.yml';

File is not found at that path.

## Suggested Resolution

This works:
$settings['container_yamls'][] = dirname(DRUPAL_ROOT) . '/modules/redis/example.services.yml';

### PR DESCRIPTION
**Pull request by michellecolon-pantheon**
Closes #6727 

## Summary

**[Enable Object Cache](https://pantheon.io/docs/object-cache#enable-object-cache)** - Adjust the path if you installed to a contrib or other subdirectory.

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6864](https://pr-6864--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `57.99999999999999` | `51` | `-7` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6864` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31499/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31499/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6864--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by greg-1-anderson** [comment]
This looks wrong to me. Is the site where this fix was necessary configured in a nonstandard way? Looks like it has its modules as a sibling of `web` rather than as a child of `web`. This might work for a number of modules, but it's also common for modules to provide css and js files that are expected to be servable from the web server, which won't work if modules is outside of the docroot.

**Comment by michellecolon-pantheon** [comment]
Thanks for the quick reply, @greg-1-anderson ! Do you think this is more of a one-off/the doc should stay the same, in this case?

**Comment by michellecolon-pantheon** [comment]
@greg-1-anderson If there is nothing we should add, should I close this PR/Issue since it is something that isn’t more widely relevant?

**Comment by greg-1-anderson** [comment]
Closing is appropriate.

**Pull request closed without merging**
