### PR TITLE
[DOC-5] guide width

### PR DESCRIPTION
**Pull request by digitalhydra**
## Effect
PR includes the following changes:
- fixes pages with missing container

### CODE REVIEW

**Comment by alexfornuto** [comment]
LGTM! Does @EdwardAngert, @allenfear, or @rachelwhitton want to weigh in?

**Comment by rachelwhitton** [comment]
Spacing looks good, nice! 

If it's reasonable, would be preferred to have the gray background pulled over all the way to left so that there's no whitespace on that side of the nav element.

**Comment by jmolivas** [comment]
@rachelwhitton @alexfornuto After checking this with @digitalhydra we got this

image

**Comment by alexfornuto** [comment]
Sounds like an extra spiffiness that just isn't possible right now. Thanks for checking.

**Pull request merged**
