### PR TITLE
Migrate to Pantheon: Manual Site Import doc update

### LINKED ISSUE #1721: Migrate to Pantheon: Manual Site Import Doc Update
Re: [Migrate to Pantheon: Manual Site Import](https://pantheon.io/docs/manual-import)
## Issue Description:
New "migrate existing site" flow has changed within the dashboard

## Suggested Resolution 
- Make sure language matches between UX and doc
- Order of import steps matches between UX and doc

### PR DESCRIPTION
**Pull request by nataliejeremy**
Closes #1721 

## Effect
PR includes the following changes:
- Updated the text to match the new migration flow

@sehamilton and @bensheldon please review--thanks!

### CODE REVIEW

**Comment by sehamilton** [comment]
For "Choose Migrate Existing Site" - should we give them instructions starting at click the 'Migrate a Site' button on the dashboard, click 'Manually migrate' OR follow wizard (not exact instructions)? It would feel a bit more complete for someone finding the doc outside of the UI flow.

**Comment by nataliejeremy** [comment]
@sehamilton Is there going to be another button here? I only see one for migrating. 
screen shot 2016-07-07 at 11 13 21 am

**Comment by sehamilton** [comment]
Nope, that will be the only button. Sorry, I was unclear. I was thinking the instructions below that may be a bit unclear:
2. Enter your current website URL.
3. Name your new Pantheon site.
4. Select an organization for the site (optional).
5. Once the site is set up, click **I've Successfully Migrated Manually**.

@bensheldon, you have to do steps 2-4 and then click 'manually migrate' or something? Then bring in your code/db/files and then step 5.

**Comment by bensheldon** [comment]
```
2. Enter your current website URL.
3. Name your new Pantheon site.
4. Select an organization for the site (optional).
5. `'Select "Migrate Manually"'`
6. Import your code/db/files
7. Once the site has been imported, click I've Successfully Migrated Manually
```

Generally this is confusing because the change we're making will not be the final migration flow. For the final result, go here and scroll down to the flow diagram: https://getpantheon.atlassian.net/wiki/display/VULCAN/Successful+Site+Migrations+PRD#SuccessfulSiteMigrationsPRD-ProposeddesigntobeimplementedinMilestone3

Unfortunately, that flow diagram describes the final ideal state after all the stories are done. not the intermediary states as each story is completed. That is kinda being made up as we go because the stories are not independent.

**Comment by sehamilton** [comment]
I am having trouble getting to the doc to review, but based on changes, I think the steps may still not be accurate. Can we make the steps as follows:
1. Choose **Migrate Existing Site**.
2. Enter your current website URL.
3. Name your new Pantheon site.
4. Select an organization for the site (optional).
5. Select "Migrate Manually"
6. Import your code, database, and files
7. Once the site has been imported, click I've Successfully Migrated Manually

(where in step #6 the 3 items are links to the places in the doc)

As the doc changes for each story we can make minor tweaks to the doc to reflect the code we push.

**Comment by nataliejeremy** [comment]
@bensheldon Can you take a look at @sehamilton comments and confirm?

**Comment by bensheldon** [comment]
👍  everything is updated in our product change too

**Pull request merged**
