### PR TITLE
Update Landing Page CTAs for Live Workshops

### PR DESCRIPTION
**Pull request by alexfornuto**
**Note:** Please fill out the PR Template to ensure proper processing.

Continues: #5611

## Summary

**[Multiple Landing Pages](https://pantheon.io/docs)** - Updates to CTAs for serveral landing pages, pointing to new Live Workshops and better-aligned docs.

**[Automating and Integrating your Pantheon WebOps Workflow with Quicksilver Platform Hooks](https://pantheon.io/docs/quicksilver)** - Reduces this absolute unit of a title to **Automate and Integrate your WebOps Workflow with Quicksilver**.

## Post Launch

- [ ] Re-Index `/docs/quicksilver` in AddSearch for new title.
- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
GitHub won't let me tag @pantheon-systems/devrel for review.

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5613 | Difference |
| --- | --- | --- | --- |
| Performance Score | `53` | `41` | `-12` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5613` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19532/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19532/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5613 | Difference |
| --- | --- | --- | --- |
| Performance Score | `54` | `44` | `-10` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5613` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19595/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19595/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5613 | Difference |
| --- | --- | --- | --- |
| Performance Score | `48` | `37` | `-11` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5613` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19779/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/19779/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Pull request merged**
