### PR TITLE
DOCO-781 WP Site Networks rsync File Transfer

### LINKED ISSUE #8040: Bash script example is wrong
Re: [Migrate to Pantheon: WordPress Site Networks](https://pantheon.io/docs/migrate-wordpress-site-networks)

Priority: Medium

## Issue Description:
`transfer-files.sh` shows an example of how to download files from Pantheon

## Suggested Resolution

Reverse the source and destination, and also clarify where this file should be placed since it seems to reference a relative `./files` folder which I assume would usually be a `uploads` folder on WordPress

The syntax of a file transfer using rsync is
rsync [option] [source] [destination]

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #8040 

## Summary

**[Migrate WordPress Site Networks](https://pantheon.io/docs/migrate-wordpress-site-networks#files)** - Updated the bash script example to match the correct rsync syntax: sync [option] [source] [destination]

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by whitneymeredith** [comment]
[Preview](https://pr-8042--pantheon-docs.my.pantheonfrontend.website/docs/migrate-wordpress-site-networks#files)

**Comment by whitneymeredith** [comment]
@jms-pantheon Can you please take a look at these changes when you get a chance?

**Review by jms-pantheon — APPROVED** [review]
I've re-written the script and made it require ssh keys, since the old example required installing a 3rd party package to send the password which is less secure. 

Odd that this script has been here since 2019 in a broken state. I've tested this locally and am happy with it now.

**Review by wordsmither — APPROVED** [review]
lgtm

**Pull request merged**
