### PR TITLE
allow to enable redis without module enabled

### PR DESCRIPTION
**Pull request by heddn**
## Effect
PR includes the following changes:
- documents method to add redis without the module enabled.

## Remaining Work
- [ ] Technical review
- [ ] Copy review

## Post Launch
To be completed by the docs team upon merge: 
- [ ] Update Status Report
- [ ] Archive from **Done** in Waffle

### CODE REVIEW

**Comment by sarahg** [comment]
Thanks for the PR, @heddn! What is the use-case for loading Redis module functions like this instead of via Drupal (by enabling the module)?

**Comment by heddn** [comment]
@sarahg if you wire everything up, and push your code, even if you have redis enabled in core.extensions.yml, your site will die. You have to first push/enable redis. Then in a later push you can push the config. This let's you run site install (un-tested but in theory possible) with redis enabled. Even before any modules are wire up.

**Comment by heddn** [comment]
BTW, these examples are copied from the README.txt in memcache from https://www.drupal.org/project/memcache/issues/2934916

**Comment by alexfornuto** [comment]
Assigning @sarahg for technical review.

**Comment by greg-1-anderson** [comment]
This is useful, causes no real harm (at the momen), and other people are doing it. 

I still have some reservations insofar as the custom autoloader isn't necessary after the module is enabled. I suppose we could conditionalize adding the autoloader based on whether the module is enabled, but that would add even more complexity to the example. I guess the rub here is that at this point we haven't gotten far enough in the bootstrap to know that the module is enabled or not. If we could do that, I'd rather go the other way and only add `$settings['container_yamls'][]` when the module is already enabled, rather than monkey-patch to make the services.yml work even when the module is not enabled. This works today, but I'm not sure that this is guaranteed to work e.g. in future versions of the redis module.

Maybe we should wait until this documentation is in the redis module too before putting it in the Pantheon documentation.

See: https://cgit.drupalcode.org/redis/tree/README.md

Since the advice here is not recommended in the Redis README, I think I am slightly -1 on this PR.

**Comment by sarahg** [comment]
Agreed with Greg. This is definitely useful, but I suggest we stick with the recommendations from the module README.

**Comment by alexfornuto** [comment]
I'm closing this issue based on the input above, but thank you for contributing nonetheless! Please feel free to submit new PRs/Issues, or continue the discussion here if you'd like.

**Pull request closed without merging**
