### PR TITLE
DOCO-747 Git Resolve Merge Conflicts Updates

### LINKED ISSUE #7949: Resolve Git Merge Conflicts Doc Update
Re: [Resolve Git Merge Conflicts](https://pantheon.io/docs//guides/git/resolve-merge-conflicts)

Priority: Medium

## Issue Description:
1. Drupal upstream is using `main` but doc still says `master`
Cursor_and_Resolve_Merge_Conflicts___Resolve_Git_Merge_Conflicts___Pantheon_Docs

2. No guide for Drupal composer-managed/with composer

## Suggested Resolution
1. Command above should be changed from `git push origin master` to `git push origin main` (correct me if I'm wrong)
2. Include a guide for resolving merge conflicts for Drupal composer-managed/with composer for non-tech/beginner Pantheon users

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #7949 

## Summary

**[Git Resolve Merge Conflicts](https://pantheon.io/docs/guides/git/resolve-merge-conflicts#resolve-conflicts-when-updating-core)** - Updated Upstream steps to use main instead of master and added  a new section to resolve merge conflicts on Drupal Composer-managed sites.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by whitneymeredith** [comment]
[Preview 1](https://pantheon.io/docs/guides/git/resolve-merge-conflicts#resolve-conflicts-when-updating-core)
[Preview 2](https://pr-7950--pantheon-docs.my.pantheonfrontend.website/docs/guides/git/resolve-merge-conflicts#resolve-conflicts-on-drupal-composer-managed-sites)

**Comment by wordsmither** [comment]
lgtm

**Comment by whitneymeredith** [comment]
@shelleycabarrubias  I was able to confirm with the eco team that the upstream itself uses the main branch (drupal-composer-managed and new wordpress-composer -managed) but the site is still tied to the master branch.

**Comment by wordsmither** [comment]
lgtm again

**Pull request merged**
