### PR TITLE
[LOPS-1952] Recommend PHP 8.3

### LINKED ISSUE #8840: NewRelic supports PHP 8.3
Re: https://docs.pantheon.io/guides/php#supported-php-versions

Priority: Medium

## Issue Description
NewRelic supports PHP 8.3 as of v10.15.04 on December 20th, 2023:
* https://github.com/newrelic/newrelic-php-agent/releases/tag/v10.15.0.4

The client on Pantheon's infrastructure needs to be updated, then this docs page can be updated.

### How will this impact users?
* Sites would be able to upgrade to PHP 8.3 and use NewRelic.

## Suggested Resolution
* Update the PHP docs page to remove the warning about NewRelic with PHP 8.3

### PR DESCRIPTION
**Pull request by scottbuscemi**
Closes #8840  

## Summary

**[Introduction - PHP](https://docs.pantheon.io/guides/php)** - Recommend PHP 8.3 once the New Relic php agent is updated on April 23

### Dependencies and Timing

**Release**:
- [ ] When ready
- [x] After New Relic PHP 8.3 compatibility is added

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by scottbuscemi** [comment]
Should be ready to publish this by EOD tomorrow.

**Comment by scottbuscemi** [comment]
@rachelwhitton Ready for merging :)

**Review by stevector — CHANGES_REQUESTED** [review]
@scottbuscemi Can you take a lot at this language tweak

**Comment by scottbuscemi** [comment]
Adjusted per Steve's rec

**Pull request merged**
