### PR TITLE
update redirects page and snippet

### LINKED ISSUE #5096: Update "Redirect for SEO and Security" to reflect new HSTS process
Re: https://pantheon.io/docs/guides/launch/redirects

Priority: Medium

## Issue Description
Pantheon's current docs recommend setting HTTPS and a canonical domain both in the application layer, but our recommended means of ensuring HTTPS has changed.

## Suggested Resolution
Now that Pantheon offers [a variety of HSTS headers and forced HTTPS at the platform layer](https://pantheon.io/docs/pantheon-yml#enforce-https--hsts), update the launch guide to direct users there for the "security" portion of the page and adjust the code snippet to redirect for canonical domains only.

### PR DESCRIPTION
**Pull request by tmountjr**
Closes #5096 

## Effect
PR includes the following changes:
- Updates the redirect page to point visitors to the HSTS directions
- Updates the code snippet to exclude HTTPS checks

## Remaining Work
- [ ] Technical review
- [x] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Archive from **Done** in [Main Project](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
@tmountjr thanks! I like the copy in the redirect page. My only question concerns the php redirect changes...

Would it hurt anything to leave them as is for those who can't or won't enable HSTS from `pantheon.yml`?

**Comment by tmountjr** [comment]
No, we can make it an optional change. But that redirect block specifically messes with advanced cdn and diy reverse proxying. I'd love to find a way to say those conditions I removed are only necessary if you're NOT doing hsts in `pantheon.yml`...

Let me poke at it a bit in the morning, I may have a solution.

**Comment by tmountjr** [comment]
There...bit more verbose and wouldn't mind another set of eyes on it from a code review standpoint. But it does the same thing and provides a few more options.

**Comment by alexfornuto** [comment]
Excellent solution, thanks!

**Comment by tmountjr** [comment]
gonna ping @nullvariable or @lauren-kelly if he's unavailable. CSE review might be good too.

**Comment by alexfornuto** [comment]
@nullvariable I confirmed that the rest of `wordpress.php` doesn't use strict comparison, so that's good enough for me! Thanks to everyone who contributed.

**Pull request merged**
