### PR TITLE
Update ImageMagick version

### PR DESCRIPTION
**Pull request by rachelwhitton**
Update ImageMagick version from `ImageMagick 6.9.10-86 Q16 x86_64 2020-01-13` to `ImageMagick 6.9.12-93 Q16 x86_64 17898`

### CODE REVIEW

**Review by pwtyler — APPROVED** [review]
Just looked, 6.9.12 matches the latest build on our php runtime.

**Comment by scottbuscemi** [comment]
Could we link to a PHP info page instead of hard-coding the version here? https://v82-php-info.pantheonsite.io/

**Comment by rachelwhitton** [comment]
@scottbuscemi The PHP Info link would need to be maintained similarly as hard-coded so I don't see a strong advantage for one over the other. Either way works for me so I'm happy to defer to you and @pwtyler for this decision

**Comment by scottbuscemi** [comment]
The PHP info pages are updated automatically when any library is updated. It's pulled from the systems.

**Comment by rachelwhitton** [comment]
@scottbuscemi Would we not eventually swap out https://v82-php-info.pantheonsite.io/ for https://v83-php-info.pantheonsite.io/ ?

**Comment by pwtyler** [comment]
> @scottbuscemi Would we not eventually swap out https://v82-php-info.pantheonsite.io/ for https://v83-php-info.pantheonsite.io/ ?

eventually, but realistically only when PHP runtimes EOL, which is ~ yearly while the extension will see more frequent updates, and if we jump more than one version when that happens, it would be some time. We could do 8.3 today and be set until November 2025.

**Comment by rachelwhitton** [comment]
@pwtyler @scottbuscemi this is helpful! thanks! i'll make it so (linking to the PHP 8.3 PHP Info page). 

Do you know the right GH team to specify for this page in the CODEOWNERS file?

**Comment by pwtyler** [comment]
PHP libraries can be CMS Performance (CMS Platform on Github).

**Comment by rachelwhitton** [comment]
@scottbuscemi @pwtyler updated! can i get one more review round on this PR when convenient?

**Review by scottbuscemi — APPROVED** [review]

**Pull request merged**
