### PR TITLE
New Content | Elementor

### PR DESCRIPTION
**Pull request by jahzlariosa**
Added new content, Elementor plugin.
Issues with search-replace.

## Summary

**[WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues)**
- Added new Issue content for Elementor Page Builder Plugin.

## Post Launch

- [ ] Update Status Report
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-5990](https://pr-5990--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `57.99999999999999` | `61` | `3` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `88` | `88` | `0` |

Lighthouse Audit Reports:

- [`pr-5990` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/23660/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/23660/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-5990--pantheon-docs.my.pantheonfrontend.website/docs)

**Review by alexfornuto — CHANGES_REQUESTED** [review]
Thanks @jahzlariosa! Can you expand a little bit on the **Issue** line? How is the URL incorrect, does it relate to dev environment or platform-domain urls? Where/how would the user experience this issue?

**Comment by jahzlariosa** [comment]
> Thanks @jahzlariosa! Can you expand a little bit on the **Issue** line? How is the URL incorrect, does it relate to dev environment or platform-domain urls? Where/how would the user experience this issue?

When a customer develop/designed the site from dev or test environments using elementor, The elementor plugin will use the platform URL for the generated style assets.

Which will result in blank/broken images once the changes have been deployed to the live environment as the style asset is not using the live URL/custom domain.

The solution is to use the built-in search replace tool from Elementor as the wp-cli search replace or other search replace plugin will not.

**Review by alexfornuto — APPROVED** [review]
Thanks @jahzlariosa!

**Pull request merged**
