### PR TITLE
Reference correct branch in merge conflict docs

### PR DESCRIPTION
**Pull request by jspellman814**
## Summary

The [resolving merge conflicts page](https://pantheon.io/docs/git-resolve-merge-conflicts#resolve-conflicts-when-updating-core) is referencing the wrong branch when running `git pull`. If there are other places that the branch referenced was changed from master to default, those should also be addressed.

### Dependencies and Timing

**Release**:
- [x] When ready

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7368](https://pr-7368--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `43` | `56.99999999999999` | `14` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7368` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/37702/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/37702/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7368--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by jspellman814** [comment]
[Preview](https://pr-7368--pantheon-docs.my.pantheonfrontend.website/docs/git-resolve-merge-conflicts#resolve-conflicts-when-updating-core)

**Comment by greg-1-anderson** [comment]
👍  Important fix.

**Review by namespacebrian — APPROVED** [review]

**Comment by whitneymeredith** [comment]
LGTM

**Pull request merged**
