### PR TITLE
Styling alerts

### PR DESCRIPTION
**Pull request by rachelwhitton**
@nataliejeremy please review and provide feedback. 

Screenshots:
screen shot 2015-07-24 at 10 26 41 am
screen shot 2015-07-24 at 10 26 58 am

The style guide has been updated within this PR request.
`assets_version` updated to 1.2 to force CSS reload on all browsers
Going forward alert styling needs to wrap **Warning** or **Note** in H4 tags instead of strong tags.

### CODE REVIEW

**Comment by nataliejeremy** [comment]
@rachelwhitton Awesome!! Let's stick with blue for notes and red for warnings. Yellow is an issue for those who are color blind and it doesn't really convey a "warning" like using red will.

**Comment by rachelwhitton** [comment]
@nataliejeremy updated, good idea to remove yellow!

screen shot 2015-07-24 at 10 38 47 am

**Comment by nataliejeremy** [comment]
@informanddelight As the UX guru, can you +1 if this change improves readability and helps make the content in the notes scannable now? Here's what it currently looks like: 
screen shot 2015-07-24 at 9 48 33 am
screen shot 2015-07-24 at 9 48 06 am

**Comment by informanddelight** [comment]
Notes are a bit more readable with the colored background. Could we actually do styling/use bootstrap alerts?

http://getbootstrap.com/components/#alerts

It'd just be a little easier extending what we're using in the product already.

**Comment by nataliejeremy** [comment]
@informanddelight Aren't those for confirmations and warnings shown at the top of the page? These notes are spread throughout the docs, sometimes 3 or 4 on a page. We're trying to improve readability so they don't get ignored.

**Comment by rachelwhitton** [comment]
Current styling on the live site is implemented with the bootstrap link you posted @informanddelight 
This PR is to replace the bootstrap styling with transparent background and black text. 

As far as aligning with product.. what if we made the notes look similar to what's on the status tab in the dashboard? 

Something like this..
screen shot 2015-07-24 at 12 31 26 pm

Lighter background and black text still accomplishes our objective of increasing readability (removing red text and red background that's currently live). 

@nataliejeremy and @informanddelight thoughts?

**Comment by nataliejeremy** [comment]
+1 @rachelwhitton That looks good.

**Comment by informanddelight** [comment]
True, it is more of a status/system alert rather than a note on article.

+1 Rachel, that balances making the contrast from the text color & background but also makes it a slightly different pattern from the system alerts. Nicely done!

**Comment by rachelwhitton** [comment]
Updated screenshot:
screen shot 2015-07-24 at 12 47 05 pm

Thanks for weighing in @informanddelight! Much appreciated

**Comment by rachelwhitton** [comment]
@informanddelight the black text is exclusively for code snippets, introduced in #262

**Comment by bmackinney** [comment]
:+1: :ship:

**Pull request merged**
