### PR TITLE
Re-add Prettier GitHub workflow #9163

### LINKED ISSUE #9082: Update and automate the running of Prettier
Undo https://github.com/pantheon-systems/documentation/pull/9047/commits/4ba642056d75b77fa5afac890c789638e97e69ab based on convo in Slack

### PR DESCRIPTION
**Pull request by rachelwhitton**
This reverts commit eb86890c3291aaac95530ec5426704c361721ebf.

Fixes #9082 

## Summary

per https://github.com/pantheon-systems/documentation/pull/9163#issuecomment-2286660654 and https://github.com/pantheon-systems/documentation/pull/9163#issuecomment-2287173776:

- Adds/updates ESLint. This was added as part of the [initial implementation](https://github.com/pantheon-systems/documentation/pull/9163#issuecomment-2286497240) which has been removed. ESLint was left because we'll probably use it again in the future.
- Adds a new `npm run lint` script in `package.json`
- Updates the README.md to note how to run ESLint locally or fix all style issues with Prettier (using the existing `npm run format` command)
- Updates the Prettier config to use JS-based configuration and splits the difference between the old/existing config and the new config in https://github.com/pantheon-systems/documentation/commit/4ba642056d75b77fa5afac890c789638e97e69ab
- Adds a new [Prettier GitHub action](https://github.com/pantheon-systems/documentation/blob/9082-re-add-prettier/.github/workflows/prettier.yml) to run the linter when any `*.js` file in `src/` is affected by a pull request and _only_ on the changed files. 
  - Prettier-formatted files affected by this are then committed back to the repository by the robot and a comment is left in the PR that files were changed (see https://github.com/pantheon-systems/documentation/pull/9180#issuecomment-2292403319 for an example)

### CODE REVIEW

**Comment by stevector** [comment]
I expect this PR will be mergable soon since I have drastically reduced the amount of change. #9163 updated prettier and add a few ESLint related packages. It also updated thousands of lines of `package-lock.json`.

In this PR went back to the `package.json` and `package-lock.json` of `main` and then ran `npm install "prettier@^3.0.0" --save-exact`.

**Comment by stevector** [comment]
And it built successfully! @jazzsequence @rachelwhitton can you review?

**Review by jazzsequence — APPROVED** [review]
lgtm

**Comment by stevector** [comment]
@jazzsequence Can you review/merge this PR?

**Pull request merged**
