### PR TITLE
Added changes in wp rocket installation

### PR DESCRIPTION
**Pull request by carl-alberto**
**Note:** Please fill out the PR Template to ensure proper processing.

Closes: #

## Summary
**[WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/plugins-known-issues/#wp-rocket)** - Added additional steps to create required folders for wp-rocket installation.

## Effect
Added additional steps for wp-rocket installation

## Post Launch
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-5951](https://pr-5951--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `65` | `64` | `-1` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `93` | `93` | `0` |

Lighthouse Audit Reports:

- [`pr-5951` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/23267/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/23267/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-5951--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by alexfornuto** [comment]
Thanks @carl-alberto! Why would folks need to create directories in `code` if that path should be symlinked to files?

**Comment by carl-alberto** [comment]
> Thanks @carl-alberto! Why would folks need to create directories in `code` if that path should be symlinked to files?

@alexfornuto afaik 

```files/cache/wp-rocket
files/cache/busting
```

will be also the same as

```code/wp-content/uploads/cache/wp-rocket
code/wp-content/uploads/cache/busting
```

when they are properly symlinked so user will have options on how to set them up as we encountered people having a hard time navigating to the `files` folder and more familiar on the wp directory structure

also, if they are not doing this step, specially on a newly installed wp-rocket installation, they will be getting a file permission issue and it seems those folders are note being automatically generated by the plugin maybe because of the file permission check if they are on git mode or in dev or test

**Review by alexfornuto — APPROVED** [review]
Thanks @carl-alberto!

**Pull request merged**
