### PR TITLE
Revise Toggling Between PHP Versions

### PR DESCRIPTION
**Pull request by ari-gold**
* Add intro sentence with link to blog post
* Style note as warning
* Revise steps to upgrade, move image to step 2
* Add section on Resolving PHP Version Compatibility Issues
* Add See Also links
  - PHP Supported Versions
  - Drupal and WordPress requirements
  - Debugging Sites with Log Files
  - PHP Errors and Exceptions

### CODE REVIEW

**Comment by ari-gold** [comment]
@bmackinney @timani

**Comment by nataliejeremy** [comment]
@ari-gold is this ready to be edited?

**Comment by bmackinney** [comment]
:+1: @rachelwhitton will need to change some urls after this merges, into #737

**Comment by ari-gold** [comment]
@nataliejeremy yes, please!

**Comment by nataliejeremy** [comment]
@ari-gold So should it just be a generic "see the backward incompatible changes documentation for your version" statement without a link (except to the php manual)?

**Pull request merged**
