### PR TITLE
Object Cache Command Line Example

### LINKED ISSUE #7688: Object Cache (formerly Redis) Doc Update
Re: [Object Cache (formerly Redis)](https://pantheon.io/docs/object-cache)

Priority: Medium

## Issue Description:

Instructions on [Command Line](https://pantheon.io/docs/object-cache#use-the-redis-command-line-client) give an example of `keys *`

Redis' documentation states: 

> Warning: consider `KEYS` as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout.

I think this advice goes doubly for using a wildcard key lookup there as well. 

## Suggested Resolution

While it gives a good show of data in the system, it should probably not be our first example. An easier one is `DBSIZE` which will show 0 if there is no data.

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #7688 

## Summary

**[Object Cache](https://pantheon.io/docs/object-cache#use-the-redis-command-line-client)** - Updated the command example to DBSIZE.
## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7691](https://pr-7691--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `46` | `54` | `8` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7691` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/41726/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/41726/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7691--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7691--pantheon-docs.my.pantheonfrontend.website/docs/object-cache#use-the-redis-command-line-client)

**Comment by whitneymeredith** [comment]
@jms-pantheon Can you please review this?

**Review by jms-pantheon — APPROVED** [review]
Looks great, thanks!

**Comment by wordsmither** [comment]
lgtm

**Pull request merged**
