### PR TITLE
[LOPS-2270] New Relic agent update release note.

### PR DESCRIPTION
**Pull request by kporras07**
Closes #

## Summary

**[New Relic PHP agent v10.22.0.12 now available](https://pr-9077-documentation.appa.pantheon.site/release-notes/2024/07/new-relic-agent-update-released)** - Adds release note for updated New Relic agent.

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] Merge the actual agent update PRs.

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)

### CODE REVIEW

**Review by namespacebrian — APPROVED** [review]

**Comment by rachelwhitton** [comment]
hey @kporras07 thanks for opening this PR! Are you still drafting or ready for finaly copy review and publishing?

**Comment by kporras07** [comment]
Hi @rachelwhitton it's mostly ready but keeping it in draft until we do the actual deployment, then I will update the date and will be ready to merge. Thanks for checking :)

**Comment by rachelwhitton** [comment]
great, thanks @kporras07! Tagging @IngridKwok for final copy review in the meantime. From there, I'll hold to merge on your signal

**Comment by IngridKwok** [comment]
@rachelwhitton @stevector @namespacebrian Made some edits to the release note.

**Comment by kporras07** [comment]
@rachelwhitton @IngridKwok this is now ready to revew

**Pull request merged**
