### PR TITLE
Integrated Composer with private GitHub package

### PR DESCRIPTION
**Pull request by jms-pantheon**
## Summary

**[Integrated Composer](https://pantheon.io/docs/integrated-composer)** - Provide a simple path and links to relevant Composer documentation for using private repositories for packages with Integrated Composer

### Dependencies and Timing

**Release**:
- [x] When ready

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7143](https://pr-7143--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.99999999999999` | `63` | `6` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-7143` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/34321/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/34321/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7143--pantheon-docs.my.pantheonfrontend.website/docs)

**Review by greg-1-anderson — CHANGES_REQUESTED** [review]
Maybe we should recommend the customer use https://getcomposer.org/doc/articles/authentication-for-private-packages.md#manual-inline-http-basic instead of auth.json to avoid friction with up-coming changes for the Customer Secrets service.

**Comment by joa-pan** [comment]
Hi @jms-pantheon. Is this still be worked on?

**Comment by jms-pantheon** [comment]
Hi @joa-pan I did need to make a few edits here, I've done that now.

**Pull request merged**
