### PR TITLE
New Article: /docs/articles/sites/code/dynamic-outgoing-ip-addresses

### LINKED ISSUE #786: Centralized location for gateways and/or extensions that sends outgoing requests via IP
Some information exists in [Known Limitations](https://pantheon.io/docs/articles/sites/known-limitations/#ip-address-based-security-schemes) and in [SSO and Identity Federation on Pantheon](https://pantheon.io/docs/articles/sites/code/sso-and-identity-federation/#ip-based-security-considerations) about external services that rely on static IP's for outgoing requests. We should have this in a more centralized location, as the problem is not just for authentication, but with code of any kind. 

If a payment gateway, or code of any kind, requires the use of a static outgoing IP address the only recommended solution is the Pantheon Enterprise Gateway. Alternatively, they can change gateways/modules to something that works in a dynamic, cloud based infrastructure.

- [x] Create a new doc in `docs/articles/sites/code` proposed title: Dynamic Outgoing IP Addresses
 - [x] Include related information from **Known Limitations** and **SSO and Identity Federation on Pantheon** docs
 - [x] Create a list of recommended payment gateway providers that **do not** rely on static IP requests
  - [x] Verify that the following providers do not rely on outgoing requests from a static IP:  Recurly, Braintree, Square and any found here: http://eseller.net/top-five-alternative-payment-channels/
 - [x] Create a list of known payment gateway providers that **do** rely on static IP requests and state they must be used with Pantheon Enterprise Gateway, or payment gateway must be used. 
- [x] Add link to new doc in **Unsupported/Problematic Modules and Plugins** with a note that any module or plugin that relies on outgoing requests to a static IP address will not work without The Pantheon Gateway

### PR DESCRIPTION
**Pull request by rachelwhitton**
**Dynamic Outgoing IP Addresses**

Closes #786 

This PR creates a centralized location concerning outbound requests made by a site on Pantheon. It recommends that if a dedicated outgoing IP is required, PEG must be used. Otherwise an alternative service must be used instead. This doc also provides recommended payment gateways and lists know services that are problematic on cloud-based infrastructures. 

This is a WIP and not yet ready for final review. See issue for up to date todo list.

### CODE REVIEW

**Comment by rachelwhitton** [comment]
CSE - Needs review

@nataliejeremy can you review as well? Thanks!

**Comment by ari-gold** [comment]
Can we cut the copy in Known Limitations to a sentence or so with link to new article?

**Comment by rachelwhitton** [comment]
Thanks for the suggestion @ari-gold - updated!

**Comment by ari-gold** [comment]
:+1:

**Comment by nataliejeremy** [comment]
+1 @rachelwhitton This looks ready to merge!

**Pull request merged**
