### PR TITLE
Docs 3.0

### PR DESCRIPTION
**Pull request by rachelwhitton**
# Docs 3.0 
## Effect
PR includes the following changes:
- Remove source files that are not currently in use, such as: source/docs/assets/css/jquery.tocify.css, source/_partials/landing-index.html, etc.

- Replace social media share buttons with more efficient javascript provided here: http://www.aaronpeters.nl/blog/why-loading-third-party-scripts-async-is-not-good-enough

- Adjust guide content type, and move guides into the _docs dir for shared taxonomies. This means docs and guides alike are populated within tags, categories, and contributor boxes while remaining separate content types and preserving URLs

- Remove sub-nav's drop down links in favor of buttons on the home page for taxon links. Menu includes: Docs, Guides, Contributors, and Changelog

- Adjust circle's config so that docs channel is only notified when master fails. Otherwise, failed builds will be indicated within PRs and on circle (to reduce noise in docs slack channel)

## Todo
- [x] Fix guide links within GH comment below ( links to docs path, update the bash logic)
- [x] Fix builds, failing sitespeed budgets

### CODE REVIEW

**Comment by bmackinney** [comment]
@rachelwhitton please add screenshots of before and after.

**Comment by rachelwhitton** [comment]
## Improved Sub-Nav (No more drop down links)
We had to put taxonomies under drop down links before this because of the way sculpin generates taxonomy index pages. Most of this PR includes changes to Sculpin so that the taxons are shared between the two content types (docs and guides)
### Before
screen shot 2016-04-18 at 4 05 17 pm

### After
Three buttons added to docs homepage so users can browse docs by taxonomies, or browse all docs. Live currently does not link to the all docs list anywhere on the site. Now that taxonomies are shared, we don't need the subnav drop down menus 
screen shot 2016-04-18 at 4 05 28 pm


## Common Taxonomies
Docs and guides each have three taxonomies that are commonly generated by Sculpin. This allows us to add Contributors to the doc content type. We can now include guides in our taxonomy index pages
### Updated 
For example, "Adding HTTPS For Free With CloudFlare" can now be seen on the domains tag page:
screen shot 2016-04-18 at 4 08 00 pm
Contributor taxonomy has been extended to the doc content type, so regular articles can attribute our contributors: 
screen shot 2016-04-18 at 4 06 43 pm
Contributor boxes now list both docs and guides, so all of their contributions are listed:
screen shot 2016-04-18 at 4 07 08 pm

**Comment by bmackinney** [comment]
LGTM, but I think @informanddelight should weigh in on the black buttons on the homepage.

**Comment by rachelwhitton** [comment]
+1 from @informanddelight via slack. 🚢 🚢

**Pull request merged**
