### PR TITLE
Considerations for Google Analytics and PANTHEON_STRIPPED

### LINKED ISSUE #1150: Considerations for Google Analytics and PANTHEON_STRIPPED Doc Update
Re: [Considerations for Google Analytics and PANTHEON_STRIPPED](https://pantheon.io/docs/articles/sites/varnish/pantheon_stripped-get-parameter-values)
## Issue Description:
Doc is vague and doesn't give instructions on exactly what to look for and how to fix issues.

## Suggested Resolution 
[ ] Add examples and a diagram of what happens to a web request that does and doesn’t get stripped
[ ] Add instructions on how to find and fix the issue.

### PR DESCRIPTION
**Pull request by nataliejeremy**
Closes #1150 
This PR add more information on why this occurs and how to fix it; adds Google Analytics image

@newtoid  @timani Please review--thanks.

### CODE REVIEW

**Comment by timani** [comment]
I think users should also be able to self diagnose if the look in the nginx log and see this but I couldn't format it as a block for readability like the markdown vs the long line.

```
nginx-access.log:10.223.193.24 - - [26/Jun/2015:17:12:52 +0000]  "GET /features?utm_source=PANTHEON_STRIPPED&utm_medium=PANTHEON_STRIPPED&utm_term=PANTHEON_STRIPPED&utm_campaign=PANTHEON_STRIPPED&utm_content=PANTHEON_STRIPPED HTTP/1.1" 301 5 "http://www.google.com/aclk?sa=l&&ctype=4&clui=3&rct=j&q=&ved=0CB4QwgUoAg&adurl=http://example.com/features%3Futm_source%3Dgoogle_adwords%26utm_medium%3Dcpc%26utm_term%3Dmam%26utm_campaign%3Drlsa_mam%26utm_content%3Drlsa_mam_broad" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4" 0.002 "108.87.108.187, 184.106.100.21, 10.189.246.4"
```

The images are an improvement.

**Comment by bmackinney** [comment]
@timani I assume you meant `nginx-access.log`, not `nginx-error.log`, correct?

**Comment by bmackinney** [comment]
Added. @timani +1?

**Comment by timani** [comment]
:rocket: :shipit:

**Pull request merged**
