### PR TITLE
Update unsupported-modules-plugins.md

### PR DESCRIPTION
**Pull request by dustinleblanc**
related to #1449 

## Effect
PR includes the following changes:
- Give instructions to use composer manager on the platform

## Remaining Work
- [x] Confirm that using this method allows cron and all other regularly scheduled tasks to run
- [x] Confirm that enabling and disabling modules does not cause Composer Manager to fire any composer tasks (composer update, etc)

@rachelwhitton please test
cc @nataliejeremy for copy edit

### CODE REVIEW

**Comment by rachelwhitton** [comment]
@dustinleblanc tested the snippet on a D7 spin up, looks good! Thanks for the PR. Are you taking on the remaining work? 

cc @ttrowell

**Comment by dustinleblanc** [comment]
@rachelwhitton Lets sync up early next week to make sure I understand what is still needed.

**Comment by dustinleblanc** [comment]
@rachelwhitton I think the only follow ups on this were to ensure cron runs fine and that enabling/disabling modules works with no issues. It looks like you already confirmed both, If that is the case, I think this is good to merge.

**Comment by dustinleblanc** [comment]
@rachelwhitton I'm testing the entire amazon s3 issue from tip to tail and one thing I've noticed is that the instructions we give are for SFTP, if a person is using git and is commiting their vendor deps locally and *then* pushing them up to the server, we should probably have the docs tell them to disable the auto-build in all Pantheon environments, and possible set their vendor dir completely outside an env switch like this:
```php
# Set appropriate paths for Composer Manager
$conf['composer_manager_file_dir'] = $_SERVER["HOME"] . '/code';
$conf['composer_manager_vendor_dir'] = $_SERVER["HOME"] . '/code/vendor';
if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
  # Disable autobuild on Pantheon.
  $conf['composer_manager_autobuild_file'] = 0;
  $conf['composer_manager_autobuild_packages'] = 0;
}
```

**Pull request merged**
