### PR TITLE
add db directive to pantheon.yml

### PR DESCRIPTION
**Pull request by EdwardAngert**
Closes: #DOC-339

## Summary

**[Pantheon.yml](https://pantheon.io/docs/pantheon-yml)** - Add information about how to choose a MariaDB version from `pantheon.yml` along with a table of CMS-specific version requirements.

## Effect

The following changes are already committed:

-
-

## Remaining Work

The following changes still need to be completed:

- [x] clarify what "eligible for upgrade" means and if that useful information in this section
- [ ] ~include info about COS? might not be needed if the platform change can be synched to the release of this PR~
- [ ] ~put table in accordion?~

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6323](https://pr-6323--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `56.99999999999999` | `64` | `7` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6323` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/26544/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/26544/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6323--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by victorpiper-pantheon** [comment]
-  clarify what "eligible for upgrade" means and if that useful information in this section
[VP] Here 'eligible for upgrade' is referring to proposed text within a table that helps the user to know what value of DB version is best for their site.  [https://docs.google.com/document/d/1j_37UQ7LVBU5kzShBgt6gw2AQyX85dZMaz05EwLNENk/edit?ts=605cbe15]
-  include info about COS? might not be needed if the platform change can be synched to the release of this PR 
[VP] I don't think customers need to know particulars about the infrastructure and so I don't think we talk about COS. 
-  put table in accordion?
[VP] The table should be visible along with the format of the db directive.  We want it to be clear that there are recommended values for each CMS version.

**Comment by victorpiper-pantheon** [comment]
@EdwardAngert Jesse can confirm, but I have updated the table in the google doc based on input from the team. 
https://docs.google.com/document/d/1j_37UQ7LVBU5kzShBgt6gw2AQyX85dZMaz05EwLNENk/edit

**Comment by spheromak** [comment]
LGTM

**Comment by CSdread** [comment]
This looks good to me, verified the table is correct, the yaml also looks good to me

**Review by CSdread — APPROVED** [review]

**Review by carolyn-shannon — APPROVED** [review]
Made some clarifying changes, lgtm. Nice work.

**Pull request merged**
