### PR TITLE
Revert "Revert "Add a "Maintenance Mode" feature to WordPress Pantheon Cache""

### PR DESCRIPTION
**Pull request by michellecolon-pantheon**
Reverts pantheon-systems/documentation#6683

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6687](https://pr-6687--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `51` | `56.99999999999999` | `6` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6687` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/30184/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/30184/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6687--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by EdwardAngert** [comment]
track [WP 5.8.2 progress](https://core.trac.wordpress.org/milestone/5.8.2)

**Comment by CdrMarks** [comment]
This change was committed along with WP 5.8.2.
https://github.com/pantheon-systems/WordPress/compare/9bf17ba449c3...07293ed6df7d

**Review by joa-pan — APPROVED** [review]
LGTM

**Pull request merged**
