### PR TITLE
WIP: CMS-291 - Convert non-composer D8 custom upstream to Integrated Composer

### PR DESCRIPTION
**Pull request by namespacebrian**
Closes #DOC-356

## Summary

**[Migrate to Drupal 9 on Pantheon](https://pantheon.io/docs/guides/drupal-9-migration)** - Add section on how to convert a Custom Upstream to Integrated Composer

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] Bug fixes: [BUGS-3760](https://getpantheon.atlassian.net/browse/BUGS-3760) and [BUGS-3935](https://getpantheon.atlassian.net/browse/BUGS-3935)

**Release**:
- [ ] Once workaround is documented

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by namespacebrian** [comment]
> Converted to draft because this is blocked on other things. c.f. https://pantheon.slack.com/archives/C03SU7UCJ/p1634932813020500

@greg-1-anderson Can you confirm that, per our conversation yesterday, we are clear to publish this document with the inclusion of the push-edit-to-pantheon.yml enable-IC work-around?

**Comment by namespacebrian** [comment]
For process-documentation purposes, we received product owner approval to publish this document with the work-around for BUGS-3935: pushing a change to the `pantheon.yml` file on each site tied to the upstream in order to enable Integrated Composer:
https://pantheon.slack.com/archives/C03SU7UCJ/p1638485407205900?thread_ts=1638478454.201000&cid=C03SU7UCJ
So this PR is no longer blocked by BUGS-3935.  We will circle back and update the document after a fix for BUGS-3935 is deployed.

**Comment by EdwardAngert** [comment]
doing a little copy review to speed things up once it's time to 🚀 🚀 🚀

**Review by joa-pan — APPROVED** [review]
LGTM

**Comment by namespacebrian** [comment]
https://pantheon.io/docs/guides/drupal-9-migration/integrated-composer-convert-custom

**Pull request merged**
