### PR TITLE
[WIP] OCP GA + Diataxis First Pass

### PR DESCRIPTION
**Pull request by rachelwhitton**
# Summary 
### Do not promote WP Redis
* Relocate how-to enable WP Redis from `/guides/object-cache/enable-object-cache` to [`/object-cache/wp-deprecated`](https://pr-8647-documentation.appa.pantheon.site/object-cache/wp-deprecated)
  * Add a warning to the top of the page alerting folks that while still maintained, WP Redis is no longer the preferred method and to use OCP instead  
* Replace mentions of WP Redis with OCP from across the docs, for example:
  * [source/content/crisis-response-upstream.md](https://github.com/pantheon-systems/documentation/pull/8647/files#diff-a75ab00851c3f18b0aff03d5fbee86351c3a94ed8446d8de3ae4561ce435cf12)
### Reconcile OCP docs with existing
* **Performance Addons**: Landing page first pass for organizing object cache docs outside of guides at [`/addons`](https://pr-8647-documentation.appa.pantheon.site/addons)
* **Object Cache Overview**: Consolidate content from `/guides/object-cache`  with `/guides/object-cache-pro` relocated to [`/object-cache` ](https://pr-8647-documentation.appa.pantheon.site/object-cache)
* **Enable Object Cache Pro for WordPress**:  Relocate content from`/guides/object-cache-pro/installing-configuring` to [`/object-cache/wp`](https://pr-8647-documentation.appa.pantheon.site/object-cache/wp)
  * [x] TODO: PDE to confirm suggested URLs can be finalized - specifically consider `/object-cache/wp` vs `/object-cache-pro` in context of other URL patterns established in the Diataxis portion of this PR like `/object-cache/drupal` and `/object-cache/cli` etc.
* Remove Object Cache sandbox eligibility references throughout docs, standardize on language like "All paid plans, except for the Basic plan, can use Object Cache."  
  * [x] TODO: PDE to confirm removal of object cache entitlement for sandboxes 
  
## Clean up "formerly Redis" throughout 
* Standardize on "Object Cache" and "Object Cache, which uses Redis," instead of "Object Cache (formerly Redis)" 

## Iterative Diataxis Adoption
First pass effort to adopt [Diataxis](https://diataxis.fr) iteratively across Pantheon Docs, starting with Object Cache content. 

Restructure multipage Object Cache guides `/guides/object-cache-pro` and `/guides/object-cache` into appropriate documentation modes based on user needs (Study vs Work) 

#### Concepts - AKA Explanatory (User Need: Study)
* Combine `/guides/object-cache-pro` introduction with `/guides/object-cache` introduction into a single overview page:   * 
   * Title: `Object Cache Overview`  URL: `/object-cache`

#### How-to Guides (User Need: Work)
Keeping in mind: https://diataxis.fr/complex-hierarchies/#two-dimensional-problems  we should opt for framework specific how-tos instead of consolidating them into tabs 

* Relocate how-to content out of `/guides/object-cache/enable-object-cache` tabs into separate doc pages based on framework 
  * Title: `Enable Object Cache Pro for WordPress`  URL: `/object-cache/wp`
  * Title: `Enable Object Cache for Drupal`  URL: `/object-cache/drupal`
  * Title: `Enable WP-Redis [Deprecated]`  URL: `/object-cache/wp-deprecated` (Intentionally not crosslinked)
  
* Relocate `guides/object-cache/redis-command-line` 
    * Title: `Use the Redis CLI`  URL: `/object-cache/cli`
* Relocate `/guides/object-cache/remove-object-cache` 
    * Title: `Remove Object Cache`  URL: `/object-cache/remove`
    
#### References  (User Need: Work)
* Relocate `/guides/object-cache/troubleshoot-object-cache` 
    * Title: `Object Cache Errors`  URL: `/object-cache/errors`
* Relocate `/guides/object-cache/faq-object-cache` 
    * Title: `Object Cache FAQs`  URL: `/object-cache/faq`

### Performance Addons Landing Page
Organize docs similar to the product (Addons > Object Cache), and explore a landing page hierarchy that better serves the Diataxis IA framework:

https://pr-8647-documentation.appa.pantheon.site/addons vs the addons section in this existing landing page: https://pr-8647-documentation.appa.pantheon.site/develop 

### Improve "More Resources" Sections throughout
Reinforce documentation modes and visibility with structured "More Resources" at the bottom of each doc, for example see this screenshot from the bottom of the object-cache overview doc: 

https://pr-8647-documentation.appa.pantheon.site/object-cache#more-resources
 
## Redirects Required:
| Redirect from | to |
|---|---|
| docs.pantheon.io/guides/object-cache-pro  | sc=301\|t=https://docs.pantheon.io/object-cache  |
| docs.pantheon.io/guides/object-cache-pro/installing-configuring  | sc=301\|t=https://docs.pantheon.io/object-cache/wordpress  |
| docs.pantheon.io/guides/object-cache      | sc=301\|t=https://docs.pantheon.io/object-cache  |
| docs.pantheon.io/guides/object-cache/enable-object-cache      | sc=301\|t=https://docs.pantheon.io/object-cache  |
| docs.pantheon.io/guides/object-cache/redis-command-line      | sc=301\|t=https://docs.pantheon.io/object-cache/cli  |
| docs.pantheon.io/guides/object-cache/remove-object-cache      | sc=301\|t=https://docs.pantheon.io/object-cache/remove  |
| docs.pantheon.io/guides/object-cache/troubleshoot-object-cache      | sc=301\|t=https://docs.pantheon.io/object-cache/errors  |
| docs.pantheon.io/guides/object-cache/faq-object-cache       | sc=301\|t=https://docs.pantheon.io/object-cache/faq  |

### Dependencies and Timing

- [x] Hold for and coordinate with OCP GA release schedule 

--------------------------------------------------

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Not quite ready for PDE review 

- [ ] Planning to revisit the changes around naming conventions:
"Pantheon's Object Cache, which uses Redis," over "Object Cache" and "Redis object cache[ing]" as well as CMS context for Drupal as summarized above in PR description 

- [ ]  URL structure will be updated to `/object-cache` over `/redis`

**Comment by scottbuscemi** [comment]
What's the url where I can view the object cache guide?

**Comment by rachelwhitton** [comment]
@scottbuscemi check out this landing page: https://pr-8647-documentation.appa.pantheon.site/addons

**Comment by rachelwhitton** [comment]
- [ ] `object-cache/wp` => `object-cache/wordpress`

**Comment by rachelwhitton** [comment]
- [ ] Add sandbox back into requirements table, explain in paragraph OCP entitlements

**Pull request merged**
