### PR TITLE
Corrected an incorrect command

### PR DESCRIPTION
**Pull request by UltraBob**
terminus site clear-caches should be terminus site clear-cache

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Thanks for the PR @UltraBob! Much appreciated! 

`terminus site clear-caches` was removed in https://github.com/pantheon-systems/cli/issues/353 - Terminus 0.8.0 now uses `terminus site clear-cache`

**Comment by UltraBob** [comment]
…which is exactly the correction I made to the documentation, so I'm not sure why you closed without merging?  Additionally that whole page needs to be reviewed, I tried to follow it in order to get a local version of my pantheon dev site working, but the instructions on that page don't get you there.  Obviously enough has changed since that was written that it is no longer valid, but I don't know what so I can't submit a pull request with the full fix.

**Comment by rachelwhitton** [comment]
@UltraBob - I should have given more info in my original comment, my apologies. Only [bleeding edge installations](https://github.com/pantheon-systems/cli/wiki/Installation#bleeding-edge--development) will use the new command argument, until the next Terminus pre-release. Otherwise the documented command is correct for Terminus 0.8.0 users.

Can you [use this link](https://github.com/pantheon-systems/documentation/issues/new?title=Local%20Development%20Setup%20and%20Operation%20Doc%20Update%20&body=Re%3A%20%5BLocal%20Development%20Setup%20and%20Operation%5D(https%3A%2F%2Fpantheon.io/docs/articles/local)%0A%23%23%20Issue%20Description%3A%0A%0A%23%23%20Suggested%20Resolution%20&labels=type%3A%20doc%20update) to open an issue for the **Local Development Setup and Operation** doc and include any steps are are no longer valid?

**Comment by UltraBob** [comment]
OK, I understand, I thought I just followed the basic instructions to install terminus, not any bleeding edge ones, but I am running 0.8.1.  Who knows.  Anyway, I'll see if I can get to opening an issue about that page, but to be honest, I'm not sure I have a lot more time to give trying to get pantheon up and running with a workflow that agrees with me, and if I could have easily figured out what was wrong with the instructions on that page, I would already have submitted a pull request.  I would suggest someone on your team try following the instructions and see what happens.  Anyway, thanks for the reply, it was appreciated.  I'll stop reopening this thread now.

**Comment by rachelwhitton** [comment]
@UltraBob no worries on reopening this thread! We really appreciate your feedback - I opened issue #1003 to evaluate the entire doc mentioned here. Thanks for surfacing this issue and communicating your concerns! 

Also, here's a [thread](https://groups.google.com/a/pantheon.io/forum/#!topic/power-users/TjfZ-hkt8J4) from our [Power Users](https://pantheon.io/docs/articles/power-users/) group regarding local workflows. While that group is not a support resource, it is a great way to learn more about common workflows from our most active users and developers.

**Comment by rachelwhitton** [comment]
Closes #1029 

@UltraBob - reopening and merging now that Terminus pre-release version is 0.8.1 

Thanks again for your contribution!

**Pull request merged**
