### PR TITLE
Autopilot email alerts

### PR DESCRIPTION
**Pull request by EdwardAngert**
Closes #

## Summary

**[Autopilot Setup and Configuration](https://pantheon.io/docs/guides/autopilot/enable-autopilot/)** -  Configure Autopilot to send email alerts weekly or when tests fail.

## Effect

The following changes are already committed:

*
*

## Remaining Work

The following changes still need to be completed:

- [ ] List any outstanding work here

--------------------------------------------------
## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6436](https://pr-6436--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `55.00000000000001` | `62` | `7` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6436` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/27646/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/27646/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6436--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by EdwardAngert** [comment]
[preview the section](https://pr-6436--pantheon-docs.my.pantheonfrontend.website/docs/guides/autopilot/enable-autopilot/#enable-autopilot-email-alerts)

**Review by dornamehrkish — CHANGES_REQUESTED** [review]
Hey @EdwardAngert  this looks great! Just a few things:
1. We are actually calling these "Email Notifications" officially, instead of alerts. Theres a task in the backlog to update the copy in the UI as well. We should probably keep docs consistent too. Here is a screenshot of how it will look like once that copy change is complete. https://cln.sh/bx1KWx
2. For the weekly activity digest, it might be helpful to add that the email is sent on Mondays, and includes data for the 7 days leading up to the email delivery date.
3. I think we should update the screenshot since the styles of the toggle UI have been updated https://cln.sh/bx1KWx

**Comment by EdwardAngert** [comment]
updated the screenshot and aligned the two spots the info is being referenced
[preview](https://pr-6436--pantheon-docs.my.pantheonfrontend.website/docs/guides/autopilot/enable-autopilot/#enable-autopilot-email-notifications)

moving to copy edit

**Review by joa-pan — APPROVED** [review]
LGTM

**Pull request merged**
