### PR TITLE
How Pantheon Prevents Plan Abuse: Title & Tone

### PR DESCRIPTION
**Pull request by allenfear**
## Effect
PR includes the following changes:
Shifts emphasis slightly from abuse, which suggests an intent that may not be there, toward how customers can better understand how we measure and enforce limits.

### CODE REVIEW

**Comment by alexfornuto** [comment]
👀 👍

**Comment by alexfornuto** [comment]
@joshkoenig would you like to review before we merge?

**Comment by lauren-kelly** [comment]
@joshkoenig based on the questions we've seen coming in from people, I think understanding how we count page views before selecting a plan will help prevent issues going forward.
I think this bit here is absolutely critical for people to understand:

> This includes not only HTML pages, but also responses in formats such as JSON and XML that are sometimes not tracked by standard analytics suites. API calls count as traffic, and are considered part of a site's plan limit.

The rest is really FAQ related to ^^

Also, I feel REALLY weird sending a doc recommendation to people about plan level _abuse_ when they are just asking about page views and plans, etc.

**Comment by allenfear** [comment]
Good point @joshkoenig. I adjusted the subhead to "Information on how Pantheon measures site traffic". 

Happy to discuss whenever you have a free moment.

**Comment by joshkoenig** [comment]
Updated with some additional intro verbage. If you all think this is ok then lets go ahead and publish!

**Comment by allenfear** [comment]
Looks great to me! Thanks for the excellent additions @joshkoenig and for the helpful input @lauren-kelly .

**Pull request merged**
