### PR TITLE
Add known issue regarding merge conflict with WP 6.0 twentytwentytwo theme

### PR DESCRIPTION
**Pull request by jspellman814**
## Summary

Add known issue regarding merge conflict with WP 6.0 and twentytwentytwo theme. See [Slack discussion](https://pantheon.slack.com/archives/C024NA0Q1TJ/p1653509236092539) for additional context.

**Release**:
- [x] When ready

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7364](https://pr-7364--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `52` | `50` | `-2` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7364` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/37661/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/37661/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7364--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by jspellman814** [comment]
[Preview](https://pr-7364--pantheon-docs.my.pantheonfrontend.website/docs/wordpress-known-issues#updating-to-wordpress-60)

**Review by CdrMarks — APPROVED** [review]

**Comment by jspellman814** [comment]
Those changes look good @EdwardAngert. Thank you!

@pantheon-systems/cms-ecosystem is working to addressing this issue now FWIW, as it has been [escalated](https://pantheon.slack.com/archives/C024NA0Q1TJ/p1653574089922779?thread_ts=1653509236.092539&cid=C024NA0Q1TJ).

**Comment by whitneymeredith** [comment]
LGTM

**Pull request merged**
