### PR TITLE
autopilot: update steps and screenshots for new exclude location

### PR DESCRIPTION
**Pull request by EdwardAngert**
DOC-292?

## Summary

**[Autopilot](https://pantheon.io/docs/guides/autopilot/enable-autopilot/#enable-autopilot)** - Autopilot has a new setup workflow that includes checking for and excluding elements earlier in the process.

## Effect

The following changes are already committed:

*
*

## Remaining Work

The following changes still need to be completed:

- [ ] List any outstanding work here

--------------------------------------------------
## Post Launch

**Do not remove** - To be completed by the docs team upon merge:
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by EdwardAngert** [comment]
[preview](https://pr-6661--pantheon-docs.my.pantheonfrontend.website/docs/guides/autopilot/enable-autopilot/#enable-autopilot)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6661](https://pr-6661--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `51` | `59` | `8` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6661` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/29963/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/29963/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6661--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by kelly-mcgonnigle** [comment]
Looks good!

**Review by michellecolon-pantheon — APPROVED** [review]
LGTM

**Pull request merged**
