### PR TITLE
WP S3 plugin needs full package with vendor folder

### PR DESCRIPTION
**Pull request by jms-pantheon**
## Summary

**[AWS S3 Setup for WordPress](https://docs.pantheon.io/guides/wordpress-developer/wordpress-s3#install-and-deploy-s3-uploads-plugin)** - Download instructions were unclear.

### CODE REVIEW

**Comment by rachelwhitton** [comment]
assigning to @jazzsequence to consider testing with the latest version of the plugin and updating docs

**Comment by jms-pantheon** [comment]
Reviewing this now, it looks like that plugin is removing the manual install. Perhaps we should just refer people to that project's readme for install instructions

**Comment by jazzsequence** [comment]
Looking at the HM repo now, and in particular the line:

> [Composer's autoloader](https://getcomposer.org/doc/01-basic-usage.md#autoloading) must be loaded before S3 Uploads is loaded.

I'm thinking that it's not possible to install S3 Uploads _without_ composer. We should call that out specifically in the [opening paragraph](https://docs.pantheon.io/guides/wordpress-developer/wordpress-s3#integrate-s3-with-wordpress) as a requirement. I also don't think that WP Offload Media _requires_ a license (I am using it on my personal site without one), but it's required if you want the urls to match your domain (rather than the S3 bucket or DO space or whatever). So maybe we can lean heavier into using that plugin instead.

Given we just [link out to WP Offload Media for docs/instruction there](https://docs.pantheon.io/guides/wordpress-developer/wordpress-s3#multisite-compatibility), I think we should probably do the same for S3 Uploads (maybe with a note that WP-CLI commands in HM's docs must be wrapped in Terminus syntax for use on a Pantheon site.

**Comment by jms-pantheon** [comment]
Thanks @jazzsequence that looks like a good move

**Comment by jazzsequence** [comment]
Merging!

**Pull request merged**
