### PR TITLE
Update PHP Version Upgrade

### LINKED ISSUE #7513: Upgrade PHP Versions Doc Update
Re: [Upgrade PHP Versions](https://pantheon.io/docs/php-versions)

Priority: Medium

## Issue Description:
Instructions for upgrading the PHP version are confusing, seem to mix SFTP and Git and indicate that there is an issue with altering the `pantheon.yml` file via Git which is not the case.

## Suggested Resolution
Work with authors to determine original intent and test out steps, split into one path for Git, one for SFTP, and one for resolving issues if they arise. 

I don't usually see any issues with altering `pantheon.yml` being rejected. Happy to assist if I can.

image

### PR DESCRIPTION
**Pull request by whitneymeredith**
Closes #7513 

## Summary

**[Upgrade PHP Versions](https://pantheon.io/docs/php-versions)** - Created tabs with separate steps for SFTP and Git.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7515](https://pr-7515--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `51` | `53` | `2` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7515` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/39629/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/39629/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7515--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by whitneymeredith** [comment]
[Preview](https://pr-7515--pantheon-docs.my.pantheonfrontend.website/docs/php-versions)

**Comment by whitneymeredith** [comment]
@jms-pantheon I created tabs with separate steps for SFTP and Git. Can you please review it?

**Comment by jms-pantheon** [comment]
Hey @whitneymeredith I just made a few changes and believe this is ready to go. 

1. The instructions incorrectly stated that a local repository would have a `/code` directory, that is only in SFTP
2. Steps for cloning using Git were slightly wrong, I opted to link to our existing docs as it isn't specific to this change
3. There was a mention of a pre-receive hook error that didn't belong there, that only happens if there is indeed an error

**Comment by wordsmither** [comment]
lgtm

**Pull request merged**
