### PR TITLE
New Doc: Basic Troubleshooting

### PR DESCRIPTION
**Pull request by alexfornuto**
## Effect
PR includes the following changes:
- A new doc, wherein we can list the common troubleshooting steps customers WordPress and Drupal users should know to take when they have an issue.

## Remaining Work
- [x] Add content
- [x] Technical review
- [x] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Archive from **Done** in [Main Project](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by umandalroald** [comment]
Usually, this error message can be fixed by the customer by removing and re-adding their domain to restart HTTPS provisioning again.

> Unable to provision HTTPS. DNS for this domain was incorrectly configured for more than seven (7) days. To trigger HTTPS provisioning ensure your DNS configuration is correct, then contact Pantheon support with error code 0006.

**Comment by alexfornuto** [comment]
@umandalroald Definitely something we should document more clearly. Do you think we should also add it to [Errors and Server Responses](https://pantheon.io/docs/errors-and-server-responses/)?

**Comment by umandalroald** [comment]
I think so @alexfornuto would be great if we could add it too in Errors and Server Responses doc. 

We re-trigger HTTPS provisioning when the domain has failed to provision HTTPS or is stuck provisioning HTTPS.

**Comment by alexfornuto** [comment]
Copied from #5461

Re: See [UnmetDependenciesException when installing Drupal 8](https://www.drupal.org/project/drupal/issues/2594351) on drupal.org

Priority: Low

## Issue Description

Sometimes, users get errors when installing Drupal:

Screen Shot 2020-01-16 at 10 32 05 AM

(Also see screenshots in message linked above)

## Suggested Resolution

It appears that this can be caused by a dirty cookie cache in the web browser. The easiest workaround is to re-install in incognito mode. It might be helpful to document this somewhere on a troubleshooting page.

**Comment by carolyn-shannon** [comment]
Additional reference may be made to:

- [PhP Errors](https://pantheon.io/docs/php-errors)

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-4865](https://pr-4865--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `63` | `70` | `7` |
| Best Practice Score | `93` | `93` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `93` | `93` | `0` |

Lighthouse Audit Reports:

- [`pr-4865` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/23359/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/23359/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-4865--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by sarahg** [comment]
@alexfornuto I just added some very general troubleshooting tips to the doc. Fwiw, I don't think we should get too CMS-specific with this or document specific errors from Drupal/WP — these things eventually get resolved by Drupal/WP maintainers and are going to become outdated fast. I know some folks still run outdated code, of course, but I don't think we need to maintain a history of application-level errors that aren't platform-specific (that's what drupal.org or the WP forums are for).

Similarly I'd recommend removing content around specific product defects (e.g, a frozen Dashboard) that are on the roadmap to be updated/fixed/replaced.

This is a tough doc to write! I'm finding it tricky to strike the right balance between too general and too specific. I'd like us to avoid documenting things that are covered better elsewhere (e.g, how to [turn on twig debugging](https://www.drupal.org/docs/theming-drupal/twig-in-drupal/debugging-twig-templates#s-enable-debugging)).... but maybe that really is useful in Pantheon docs as well? 🤷‍♀️

**Review by carolyn-shannon — APPROVED** [review]
Would be helpful to 

- flesh out the Drupal troubleshooting sections, and to 

- add links to Additional Information section for other troubleshooting sections in other docs.

**Pull request merged**
