### PR TITLE
Billing Clarifications

### PR DESCRIPTION
**Pull request by wordsmither**
Closes #DOCO-911

## Summary

**[Billing Guide](https://docs.pantheon.io/doc-title)** - Clarifications around managing billing options.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by wordsmither** [comment]
[Account Types](https://pr-8557-documentation.appa.pantheon.site/guides/account-mgmt/account)
[Self Serve Billing Payment Methods](https://pr-8557-documentation.appa.pantheon.site/guides/account-mgmt/billing/methods)

**Comment by stevector** [comment]
@rachelwhitton can you review here given the overlap with https://github.com/pantheon-systems/documentation/pull/8911

**Comment by rachelwhitton** [comment]
@stevector i pushed some work to this PR to refresh from `main` and added some minor copy edits. This can be merged as soon as now given no objections. This PR doesn't have strong overlap with #8911 (no overage policy content in this PR - it mostly contains small copy adjustments to various landing pages, for example): 

screencapture-localhost-8000-guides-account-mgmt-2024-03-28-11_50_09
screencapture-localhost-8000-guides-account-mgmt-2024-03-28-11_50_09 (1)

---

It also adds a small page at `/guides/account-mgmt/account/types` to an existing guide which I updated to crosslink to the more specific definitions elsewhere 
screencapture-localhost-8000-guides-account-mgmt-account-types-2024-03-28-12_23_45

**Review by rachelwhitton — APPROVED** [review]

**Comment by stevector** [comment]
@rachelwhitton I just resolved merge conflicts from `main`. But can you double check that I didn't lose any of the structural changes you wanted on the landing pages?

**Comment by rachelwhitton** [comment]
@stevector done! one header change was lost but I just restored it. Ready to merge 🚀

**Review by stevector — APPROVED** [review]

**Pull request merged**
