### PR TITLE
Update site-owner-faq.md about Annual invoicing for sites

### PR DESCRIPTION
**Pull request by twooten**
This question comes up periodically.

### CODE REVIEW

**Comment by lauren-kelly** [comment]
@twooten unfortunately it isn't that easy/straightforward :/
@ccorpus maybe we should meet and see if we can come up with some language that would be helpful to customers and reduce the number of request?

**Comment by lauren-kelly** [comment]
@alexfornuto Take a look and see what you think?

**Comment by alexfornuto** [comment]
LGTM, although I'd like to restructure the entire page so that these questions are in H3s with anchor links instead of H4s. What do you think, @rachelwhitton?

**Comment by rachelwhitton** [comment]
+1

**Pull request merged**
