### PR TITLE
Avoid PHP error associated with missing arguments

### PR DESCRIPTION
**Pull request by danielbachhuber**
Minor code sample tweak

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | Live | pr-5501 | Difference |
| --- | --- | --- | --- |
| Performance Score | `55.00000000000001` | `50` | `-5` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-5501` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18280/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/18280/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)

**Comment by alexfornuto** [comment]
@danielbachhuber can you explain what this change does?

**Comment by danielbachhuber** [comment]
@alexfornuto Sure. The function assigned to the filter is expecting two arguments. Because it's expecting two arguments, you need to use `2` as the fourth argument to `add_filter()`.

Currently, because `2` isn't provided as the fourth argument and `1` is the default argument, only one argument is passed through to the callback function (which means there's a PHP error and it doesn't work).

**Comment by danielbachhuber** [comment]
Closing in favor of #5528

**Pull request closed without merging**
