### PR TITLE
Add Breadcrumbs

### PR DESCRIPTION
**Pull request by ari-gold**
* Create breadcrumbs for articles by parsing page.url with Twig
* Relies on every component of URL to have a valid page

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Screenshot:
screen shot 2015-05-06 at 11 18 32 am

Todo: 
- [ ] Adjust CSS

**Comment by rachelwhitton** [comment]
Updated screenshot:
screen shot 2015-05-06 at 11 37 32 am

**Comment by bmackinney** [comment]
Looks good! final thoughts on the use of `/` vs `>`, and whether we should keep the grey shading and left padding? @ari-gold @rachelwhitton @informanddelight

**Comment by ari-gold** [comment]
I'll defer to @informanddelight, but styling looks great, @rachelwhitton!

**Comment by rachelwhitton** [comment]
Thanks @ari and @bmackinney! 
I don't have a preference of `/` vs `>` - I went with `/` on this revision because it's styled that way in PR #517 and in [bootstrap componets](http://getbootstrap.com/components/#breadcrumbs).

**Comment by bmackinney** [comment]
@rachelwhitton via @informanddelight let's move the breadcrumbs above the doc title, as it's a navigation element. Also change the `/` to  `»`.

**Comment by rachelwhitton** [comment]
@bmackinney awesome! +1 to ship after #530 is merged. 
screen shot 2015-05-06 at 3 39 35 pm

**Comment by rachelwhitton** [comment]
Updated screenshots:

## Articles:
screen shot 2015-05-06 at 4 26 45 pm

## Guides:
screen shot 2015-05-06 at 4 26 45 pm

**Comment by rachelwhitton** [comment]
New guides screenshot:
screen shot 2015-05-06 at 4 58 12 pm

+1

**Pull request merged**
