### PR TITLE
DOC-447: Multidev access update

### PR DESCRIPTION
**Pull request by EdwardAngert**
Closes #6854 

## Summary

**[Multidev FAQ](https://pantheon.io/docs/multidev-faq)** - Updated documentation to reflect clearer Multidev access permissions.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [x] After date: targeted for 29 Nov 21- check Slack for any updates

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6854](https://pr-6854--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `62` | `57.99999999999999` | `-4` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6854` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31333/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/31333/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6854--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by EdwardAngert** [comment]
[preview](https://pr-6854--pantheon-docs.my.pantheonfrontend.website/docs/multidev-faq#who-has-access-to-multidev)

**Comment by EdwardAngert** [comment]
[roles and permissions table](https://pr-6854--pantheon-docs.my.pantheonfrontend.website/docs/change-management#organizations-roles-and-permissions)

**Review by joa-pan — APPROVED** [review]
LGTM

**Pull request merged**
