### PR TITLE
Tweak Change Upstream Permissions Note

### PR DESCRIPTION
**Pull request by dficker**
## Summary

**[Upgrade from Drupal 8](https://pantheon.io/docs/guides/drupal-9-migration/upgrade-to-d9)** -  Actually, a few more users than the User In Charge can change the upstream.

## Effect
The following changes are already committed:

* This is Documented elsewhere correctly in the Docs:
https://pantheon.io/docs/create-custom-upstream#switch-an-existing-site-to-a-custom-upstream

--------------------------------------------------
## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6400](https://pr-6400--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `60` | `55.00000000000001` | `-5` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6400` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/27378/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/27378/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6400--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by EdwardAngert** [comment]
@dficker were you able to test that successfully? I added that line recently because I got denied as a non-UiC and in my testing, this was the result I got

**Comment by dficker** [comment]
@EdwardAngert Looks like your message got cut off?

Yesterday I talked with a customer and they could not run the command. They upgraded their permissions to be an Administrator of a Supporting Org on the site and then was able to run the command. Which seems to align with the data in the Other Docs.

**Comment by dficker** [comment]
Oh, looks like this could also use updating here:
https://pantheon.io/docs/guides/composer-convert#change-upstreams

**Review by joa-pan — APPROVED** [review]
LGTM

**Pull request merged**
