### PR TITLE
Feature/wecs 157  implement pagination for release notes 2

### PR DESCRIPTION
**Pull request by gfbollingerHakuna**
This is a follow-up to the initial pagination feature. 
URLs are now formatted without query strings.

### CODE REVIEW

**Comment by stevector** [comment]
@gfbollingerHakuna can you resolve the merge conflicts here?

**Comment by gfbollingerHakuna** [comment]
Hi @stevector , nice to meet you! This is still a work in progress and not ready for review yet. I am currently adjusting some details that @mel-miller  requested. If this progresses, I can resolve the conflicts with no problem.

Thanks!

**Comment by rachelwhitton** [comment]
@mel-miller @gfbollingerHakuna do we need to update [the Release Notes link](https://github.com/pantheon-systems/documentation/blob/main/src/layout/header/index.js#L84) here in the header layout file from `/release-notes` to `/release-notes/1/`? 

Do we need to update existing redirects that target `/release-notes`? I have a wildcard redirect that sends requests for`/changelog*` to `/release-notes` - wondering if I need to update that existing redirect to `/release-notes/1/` once this PR is merged.

**Comment by mel-miller** [comment]
> Do we need to update existing redirects that target `/release-notes`? I have a wildcard redirect that sends requests for`/changelog*` to `/release-notes` - wondering if I need to update that existing redirect to `/release-notes/1/` once this PR is merged.

@rachelwhitton - I don't think you need to update that redirect. It will automatically resolve from `/release-notes`.

**Review by stevector — APPROVED** [review]
Thanks!

**Review by rachelwhitton — DISMISSED** [review]
I think a bug is introduced here in this PR when refreshing the page in your browser after using the pager feature 


https://github.com/user-attachments/assets/33299d6a-c240-4141-ba55-8852d99e0be5

This same issue is observed when [checking for visual regression locally](https://github.com/pantheon-systems/documentation/tree/main/tests#checking-for-visual-regression) on this page: `/release-notes/1/?category=policy` 

https://github.com/user-attachments/assets/4cd536eb-d576-49cd-9005-25567a00408a

@gfbollingerHakuna @mel-miller @stevector

**Comment by mel-miller** [comment]
@gfbollingerHakuna — can you take a look at this when you get a chance? It is not urgent since the current pagination is working fine.

**Comment by mel-miller** [comment]
@rachelwhitton — @gfbollingerHakuna and I have both tried on several browsers (Mac and Win) and can't reproduce that bug. Is it still happening for you?

**Comment by rachelwhitton** [comment]
assigning to @jazzsequence to double check. I tried again and couldn't reproduce

**Review by jazzsequence — APPROVED** [review]

**Pull request merged**
