### PR TITLE
Update temp-files.md

### LINKED ISSUE #1574: Temporary File Management with Multiple Application Containers Doc Update
Re: [Temporary File Management with Multiple Application Containers](https://pantheon.io/docs/temp-files)
## Issue Description:
Customer reported that the Drupal override did not work (shown here: https://pantheon.io/docs/temp-files/#drupal)
$conf['file_temporary_path'] = 'public://tmp';

Bug report: https://getpantheon.atlassian.net/browse/BUGS-158

## Suggested Resolution 
Confirm if it works or not. If not, update the doc or remove it
Work with @ttrowell

### PR DESCRIPTION
**Pull request by ttrowell**
Closes #1574 

## Effect
PR includes the following changes:
- Remove snippet encouraging people that they can alter the tmp path in Drupal 7.

## Remaining Work
- [x] Review the wording again
- [x] Verify the variables
- [x] Get feedback from Josh

@rachelwhitton please test
cc @nataliejeremy for copy edit

This is the first commit as I work on this document.

### CODE REVIEW

**Comment by ttrowell** [comment]
@joshkoenig Could you provide feedback/edits on this doc, please sir?  The current version is causing people to think they can manipulate the filesystem in ways that are not actually reliable.

**Comment by joshkoenig** [comment]
Not sure what the goal is here. This:

```  $config['system.file']['path']['temporary'] = $_SERVER['HOME'] .'/tmp';```

Is a totally safe config to include. What we want to make clear is that putting the tmp file directory in `sites/default/files` or `$_SERVER['HOME'] .'/files/tmp'` is considered a "warranty voiding" configuration. 

I feel like there's a general lack of understanding around what is going on here that this doc does not address. Maybe we should make this doc good enough to use for internal CSE purposes as well?

**Comment by ttrowell** [comment]
YES - this should be as detailed as possible because it's one of the biggest pain points for people building sites, and one of the hardest things for us to explain.  I think customers would truly appreciate a detailed explanation, as well.  It would additionally take the "burden of proof" so to speak off of CSE when  we convey that a plugin or module may not work for this reason.

Now, I may have recalled the discussion wrong.  I was thinking that in our Bugs discussion that it was advised to remove it - but maybe it was just advised to include a bigger disclaimer around it. https://getpantheon.atlassian.net/browse/BUGS-158

**Comment by nataliejeremy** [comment]
@ttrowell Hi Tara, are you working on completing this?

**Comment by rachelwhitton** [comment]
Closed by #1668

**Pull request closed without merging**
