### PR TITLE
DOC-357 - Upgrade in place - "No CI" workflow

### PR DESCRIPTION
**Pull request by stovak**

### CODE REVIEW

**Comment by stovak** [comment]
@EdwardAngert this is a thing that exists. Hope to finish my part of it tomorrow.

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6455](https://pr-6455--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `45` | `63` | `18` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6455` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/27858/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/27858/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6455--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by greg-1-anderson** [comment]
When this is written up, we should make sure that the site is first converted from D8 + No CI to Integrated Composer still on D8, so the user can test the Integrated Composer conversion before upgrading to Drupal 9.

**Comment by wordsmither** [comment]
Closed in favor of https://github.com/pantheon-systems/documentation/issues/6346

**Pull request closed without merging**
