### PR TITLE
Account Management Guide

### PR DESCRIPTION
**Pull request by wordsmither**
Closes #DOC-706

## Summary

**[Account Management Guide](https://pantheon.io/docs/guide/account-mgmt)** - New guide gathering all account management content (Organizations, roles and billing) into one place.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [x] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by pantheondocs** [comment]
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7719](https://pr-7719--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `52` | `53` | `1` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7719` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/42076/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/42076/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7719--pantheon-docs.my.pantheonfrontend.website/docs)

**Comment by wordsmither** [comment]
[Preview](https://pr-7719--pantheon-docs.my.pantheonfrontend.website/docs/account-mgmt)

**Comment by wordsmither** [comment]
Redirects

/docs/access-management | /docs/guides/account-mgmt/workspace-sites-teams/teams
-- | --
/docs/account-billing | /docs/guides/account-mgmt/billing
/docs/add-client-site | /docs/guides/account-mgmt/billing/transfer
/docs/annual-billing | /docs/guides/account-mgmt/plans/pricing
/docs/change-management | /docs/guides/account-mgmt/workspace-sites-teams/teams
/docs/delete-account | /docs/guides/account-mgmt/account/delete
/docs/delete-site | /docs/guides/account-mgmt/workspace-sites-teams/sites#delete-sites
/docs/guides/new-dashboard/workspace-billing/ | /docs/guides/account-mgmt/billing/invoices
/docs/managing-edu-plus | /docs/guides/account-mgmt/plans/manage
/docs/optimize-site-traffic | /docs/guides/account-mgmt/traffic/remedy
/docs/organization-dashboard | /docs/guides/account-mgmt/workspace-sites-teams
/docs/organization-faq | /docs/guides/account-mgmt/workspace-sites-teams/workspaces
/docs/organizations | /docs/guides/account-mgmt/workspace-sites-teams/workspaces
/docs/overages-site-plan | /docs/guides/account-mgmt/traffic
/docs/overview/accounts | /docs/guides/account-mgmt/account
/docs/site-access | /docs/guides/account-mgmt/account/recover
/docs/site-billing | /docs/guides/account-mgmt/billing
/docs/site-owner-faq | /docs/guides/account-mgmt
/docs/site-plan | /docs/guides/account-mgmt/plans
/docs/site-plans-faq | /docs/guides/account-mgmt/plans
/docs/team-management | /docs/guides/account-mgmt/workspace-sites-teams/teams
/docs/sites | /docs/guides/account-mgmt/workspace-sites-teams/sites
/docs/traffic-limits | /docs/guides/account-mgmt/traffic

**Comment by whitneymeredith** [comment]
LGTM

**Pull request merged**
