### PR TITLE
Add wordpress-social-login session issue

### PR DESCRIPTION
**Pull request by slashzero**
Can be coded around but not recommended.

Closes #

## Effect
PR includes the following changes:
-
-
-

## Remaining Work
- [ ] List any outstanding todos
- [ ] If needed

### CODE REVIEW

**Comment by alexfornuto** [comment]
@slashzero are you OK with my edits?

**Comment by slashzero** [comment]
Type: $PANTHEON_BINDING should be PANTHEON_BINDING

**Comment by alexfornuto** [comment]
@slashzero are you saying we need to remove the `$` in the command excerpt below?

```
if (defined( "$PANTHEON_BINDING" )) { 
  include_once( "/srv/bindings/". $PANTHEON_BINDING ."/code/wp-blog-header.php" ); 
}
```

**Comment by alexfornuto** [comment]
@slashzero can you confirm that the code snippet is now correct?

**Comment by slashzero** [comment]
+1 Ready to rock!

**Pull request merged**
