### PR TITLE
Update Build Tools Guide for Version 2

### LINKED ISSUE #5151: The Build Tools guide is outdated/deprecated
Re: https://pantheon.io/docs/guides/build-tools

Priority: Medium

## Issue Description
The Build Tools guide is outdated and should be updated for version 2 of the package.

### PR DESCRIPTION
**Pull request by ataylorme**
Closes #5151

## Effect
PR includes the following changes:
- Update the guide at `/guides/build-tools` from Build Tools version 1 to version 2

## Remaining Work
- [ ] Rework all guide sections
  - [x] What is Build Tools?
    - [x] Project purpose
    - [x] Build Tools workflow overview
    - [x] When to use Build Tools
    - [x] Build Tools components/related repositories
  - [x] Installing Build Tools
  - [x] Interactive `build:project:create` command generator
  - [ ] Example repo/Continuous Integration breakdown
    - [ ] Differences between providers (GitHub/CircleCI, GitLab, BitBucket)
    - [ ] Differences between CMS (WordPress/Drupal 8)
  - [ ] Drupal 8/WordPress walkthroughs
    - [ ] Install a new package with Composer
    - [ ] PR to multidev
    - [ ] Config change
    - [ ] Export/commit config (Quicksilver pushback)
    - [ ] Automated test?
  - [ ] Recap
- [ ] Technical review
- [ ] Copy Review

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] Update Status Report
- [ ] Archive from **Done** in [Main Project](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by ataylorme** [comment]
> Interactive `build:project:create` command generator

pantheon-docs-interactive-command-builder-rough-demo

**Comment by ataylorme** [comment]
@alexfornuto is a multidev not being created because the PR is from a fork? If so, is it okay if I make a PR from a branch on the main docs repo?

**Comment by alexfornuto** [comment]
Yes, and yes always.

**Comment by ataylorme** [comment]
Closing in favor of #5194

**Pull request closed without merging**
