### PR TITLE
Pantheon SSL/TLS doc update

### LINKED ISSUE #1663: Update TLS docs
## Issue Description

Update docs to indicate v 1.0 is no longer supported. 

Internal project link: https://getpantheon.atlassian.net/wiki/display/VULCAN/Deprecate+TLSv1.0+PRD

### PR DESCRIPTION
**Pull request by nataliejeremy**
Closes #1663 

## Effect
PR includes the following changes:
- Adds that we do not support TLS 1.0, only 1.1 and 1.2.

@garydylina @sehamilton Please review.

### CODE REVIEW

**Comment by sehamilton** [comment]
looks good to me.

**Comment by sehamilton** [comment]
After reviewing with Gary - can we say in the docs what we currently support and that we plan to remove TLS 1.0 around 6/30. That way CSE has something to point customers to when they ask and if someone misses the email notification they have another way of finding out in our docs.

**Comment by nataliejeremy** [comment]
@sehamilton and @garydylina I made some changes--please review. 
https://1663tls-static-docs.pantheonsite.io/docs/ssl-tls/

**Comment by sehamilton** [comment]
Can we update "If you need to continue support for TLS 1.0, you can do so with CloudFlare." to "If you need to continue to support for TLS 1.0, you can do so with [Cloudflare](https://pantheon.io/docs/cloudflare/). Please refer to [Cloudflare's documentation](https://support.cloudflare.com/hc/en-us/articles/205043158-PCI-3-1-and-TLS-1-2)." Play with the wording, but I just want to make sure users know how to enable Cloudflare and use TLS 1.0 in Cloudflare.

**Comment by sehamilton** [comment]
looks good! We can release that now and I will add a link to the email notification.

**Comment by nataliejeremy** [comment]
Thanks for the quick review @sehamilton

**Pull request merged**
