### PR TITLE
Removing "dedicated" messaging from the Support Guide page.

### PR DESCRIPTION
**Pull request by dylanbaumann**
Support Leaders have requested the removal of the term "dedicated" when referring to the Diamond Team, which has caused customer confusion around what our support offerings actually are. This update removes the confusion. More clarity on what Diamond provides will come in a future update.

## Summary

**[Scope of Support](https://docs.pantheon.io/guides/support/)** - Removes the phrase "dedicated" from the scope of our support.
**[Disaster Recovery](https://docs.pantheon.io/guides/disaster-recovery/site-goes-down#escalation-paths)** - Removes the phrase "dedicated" in reference to escalation paths when contacting support.
**[Workspace Plans](https://docs.pantheon.io/guides/account-mgmt/plans/workspace-plans#platinum--diamond-account-plan)** - Removes the phrase "dedicated" from our our workspace plan offerings.

### CODE REVIEW

**Comment by rachelwhitton** [comment]
Thanks for this @dylanbaumann! 

I found a few more mentions of dedicated support: 

* https://docs.pantheon.io/guides/disaster-recovery/site-goes-down#escalation-paths
* https://docs.pantheon.io/guides/account-mgmt/plans/workspace-plans#platinum--diamond-account-plan

Can you review those ^ and add edits to this PR when convenient? 

Is "dedicated CSM" still fine and accurate to say across the docs? For example, [here](https://docs.pantheon.io/guides/disaster-recovery/planning-ahead#monitor-and-optimize-performance). I think so but just double checking

**Comment by dylanbaumann** [comment]
Hey @rachelwhitton thank you so much for catching those!

- I've added two new changes to address the additional documentation you found
- The phrase "dedicated customer support manager" (or "dedicated CSM") is still correct and can remain in place, thanks for checking though!

**Review by stevector — APPROVED** [review]
LGTM

**Comment by stevector** [comment]
Thanks @dylanbaumann! Rachel is out today so I'm merging now.

**Pull request merged**
