### PR TITLE
Update redis.md

### PR DESCRIPTION
**Pull request by twooten**
Added a note to let customers know that adding Redis config to settings.pantheon.php will likely cause Git conflicts if/when upstream changes are made to settings.pantheon.php.

## Remaining Work
- [x] Wordsmithing 

## Post Launch
**Do not remove** - To be completed by the docs team upon merge:
- [ ] Update Status Report
- [ ] Archive from **Done** in [Main Project](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by alexfornuto** [comment]
Thanks @twooten! Do you think we should include this on the D7 tab as well?

**Comment by alexfornuto** [comment]
I added that as a separate commit, in case you agree.

**Comment by twooten** [comment]
@alexfornuto there is no settings.pantheon.php in our upstream, so not needed.

**Comment by alexfornuto** [comment]
removed.

**Pull request merged**
