### PR TITLE
[CMSP-363] Update the doc to add more accurate guidance for OCP on WP Multisite

### PR DESCRIPTION
**Pull request by jazzsequence**
## Summary

**[Install and Configure Object Cache Pro](https://docs.pantheon.io/guides/object-cache-pro/installing-configuring/)** - Updates the existing Object Cache Pro installation instructions to add guidance and usage for installing Object Cache Pro on WordPress multisite installs.

### Dependencies and Timing

**Release**:
- [x] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

### CODE REVIEW

**Comment by jazzsequence** [comment]
@scottbuscemi This updates the guidance that you added in 1b17ab025015045997b4b4be5e2725066628cd3c. Those notes are applicable only if the plugin is installed on a multisite but not installed as a `mu-plugin`. The recommended usage of OCP on multisite is to install it in `mu-plugins`.

**Comment by jazzsequence** [comment]
[Demo](https://pr-8376-documentation.appa.pantheon.site/guides/object-cache-pro/installing-configuring/#installing-object-cache-pro-on-wordpress-multisite)

**Review by jspellman814 — APPROVED** [review]

**Review by whitneymeredith — APPROVED** [review]
LGTM. @scottbuscemi I will hold off on merging until you get a chance to review this.

**Comment by scottbuscemi** [comment]
@whitneymeredith This is ready to go, ty

**Pull request merged**
