### PR TITLE
Notify users that twenty- themes and akismet will not be updated

### PR DESCRIPTION
**Pull request by bmackinney**
@greg-1-anderson please review.

### CODE REVIEW

**Comment by bmackinney** [comment]
@nataliejeremy does my change belong in a `div alert`?

**Comment by nataliejeremy** [comment]
@bmackinney I think body text is fine; no need for an alert.

**Comment by bmackinney** [comment]
@greg-1-anderson :+1: ?

**Comment by greg-1-anderson** [comment]
+1

**Pull request merged**
