### PR TITLE
Penetration/Vulnerability Testing doc

### LINKED ISSUE #1654: Penetration / Vulnerability Testing
Re: Penetration Testing
## Issue Description

We do not have customer-facing documentation regarding penetration or vulnerability testing
## Suggested Resolution

https://docs.google.com/a/getpantheon.com/document/d/1Hylnk8syrFyPLzTDzHaPyqR0y2fGjOm_v5fsRv8D9FU/edit?usp=sharing

### PR DESCRIPTION
**Pull request by nataliejeremy**
Closes #1654 

Thanks for submitting the issue @lauren-kelly Please review and add any additional info.

### CODE REVIEW

**Comment by slashzero** [comment]
+1 looks good to me

**Comment by lauren-kelly** [comment]
+1 thank you Natalie!

**Comment by rachelwhitton** [comment]
+1 Thanks for adding this @nataliejeremy @lauren-kelly @slashzero 

LGTM 🚢

**Comment by nataliejeremy** [comment]
@garydylina Can you take a look and see if anything else should be added? Thanks!

**Comment by garydylina** [comment]
Needs work before deploying.

**Comment by nataliejeremy** [comment]
@garydylina  Can you help with that? If not, who should I ping?

**Comment by lauren-kelly** [comment]
@garydylina let me know what updates are needed, and I'll get them in place

**Comment by allenfear** [comment]
@garydylina were holding off on posting this, pending your input on what you meant by this needing work. Could you please provide info on what work is needed?

**Comment by nataliejeremy** [comment]
@lauren-kelly @allenfear I talked with @garydylina and there is some important information he wants to add, but is busy with another priority right now. He'll update soon. I'll mark this as Hold For Release for now.

**Comment by lauren-kelly** [comment]
I suspect this will need to get updated once we have Fastly implemented as well - right @garydylina ?

**Comment by allenfear** [comment]
@garydylina could you provide input or let us know if we should abandon this doc at this point?

**Comment by allenfear** [comment]
@garydylina following up on our conversation this morning about whether this should be a public facing doc. I think a doc would be useful, but we'll defer to your guidance on whether to move forward with a public facing doc. 

Here is Acquia's doc: 
https://docs.acquia.com/article/preparing-security-penetration-or-load-testing

Let us know what you advise.

**Comment by allenfear** [comment]
@garydylina and @secsal will be at RSA conference next week but expect to have time to wrap this up two weeks from today.

**Comment by allenfear** [comment]
@garydylina @secsal any update?

**Comment by alexfornuto** [comment]
I spoke with @garydylina about this. The changes coming from the Global Edge invalidate a lot of the content written here. Unless there are any objections, I'm going to close this PR. Once Global Edge is complete, Gary and I will work together to make a new doc on penetration and vulnerability testing.

**Pull request closed without merging**
