### PR TITLE
Assessing Alerts Partial File

### LINKED ISSUE #3396: Pingdom Uptime Check Doc Update
Re: [Pingdom Uptime Check](https://pantheon.io/docs/guides/pingdom-uptime-check/)

Priority (Low‚ Medium‚ High):

## Issue Description:

We frequently get tickets from customers that got an alert from New Relic, Pingdom, an internal monitoring system etc.
These often merely state that customer received xx number of alerts, asking if there is an issue.
Pantheon support has very little to go on here. We rarely have the time to spend an hour digging through the site, unless there is an issue.

Please see internal reference:
Ticket 99555

## Goal
It would be great if we could help customers learn how to assess alerts. Ideally monitoring should help gain peace of mind, rather than additional worry.

## Suggested Resolution 

Could we add a section in each for something like:
- What do alerts mean
- What to do when you get an alert

### LINKED ISSUE #3397: Incident Management Doc Update
Re: [Incident Management](https://pantheon.io/docs/guides/pagerduty/monitor/)

Re: [Pingdom Uptime Check](https://pantheon.io/docs/guides/pingdom-uptime-check/)

Priority (Low‚ Medium‚ High):

## Issue Description:

We frequently get tickets from customers that got an alert from New Relic, Pingdom, an internal monitoring system etc.
These often merely state that customer received xx number of alerts, asking if there is an issue.
Pantheon support has very little to go on here. We rarely have the time to spend an hour digging through the site, unless there is an issue.

Please see internal reference:
Ticket 99555

Also see identical ticket for Pingdom: #3396 

## Goal
It would be great if we could help customers learn how to assess alerts. Ideally monitoring should help gain peace of mind, rather than additional worry.

## Suggested Resolution 

Could we add a section in each for something like:
- What do alerts mean
- What to do when you get an alert

### PR DESCRIPTION
**Pull request by alexfornuto**
Closes #3396 
Closes #3397

## Effect
PR includes the following changes:
- Creates partial file on assessing alerts
- Adds said partial to Incident Response and Pingdom guides

## Remaining Work
- [ ] @pantheon-systems/cse review (ie @tinefin )
- [ ] Copy Review

### CODE REVIEW

**Comment by alexfornuto** [comment]
I've reached out to @tinefin to review the latest version of this PR.

**Comment by tinefin** [comment]
Would be good to include the points in the original issue(s).
This is described in internal ticket reference + PM with Alex F.

**Comment by alexfornuto** [comment]
update: @tinefin is writing up some additional info to add to this PR.

**Comment by tinefin** [comment]
# Monitoring alerts
Remember, these are automated alerts. The monitoring tool can't actually know whether the site is up or down. It merely checks if the site responds within xx seconds and if not, sends out an alert.
Some level of false positives should be expected.
The alert could just mean that this once, the site responded a bit slower than the xx seconds time limit. Or it could mean that the site is literally down.

If alerts are too "noisy" and generates many false positives, check if you can adjust the alert threshold or email preferences. Acceptable response time on sites vary and might not fit the default alert threshold.
Some monitoring tools also the option only alert on a number of consequtive failures. This helps false positives caused by a single request being slow.

## What to do when receiving monitoring alerts
Don't panic! This could just be internet winds, a few minutes of heavy load - or something else =)
As these are automated alerts, it is necessary to first verify that there actually is an issue.

All-the-things can be monitored. For websites, 2 popular parameters to monitor are whether the site responds and how quickly the site responds.

### Verify an alert for whether the site responds (uptime):
- Load the site in a browser and check if it loads.
- Login to the site.
If both are ok, the site is up. 

In case the site doesn't load, check whether the site is up outside your local network. Tools like these can be helpful:
https://downforeveryoneorjustme.com
https://geopeeker.com/fetch/?url=pantheon.io

### Verify an alert for site response time:
Application response time can be checked in New Relic. If response time is spiking compared to historically normal response time, dig into New Relic traces and site logs to find out why.
This is where to find the site logs on Pantheon:
https://pantheon.io/docs/logs/

Pantheon support can assist in case there is a verified issue on a site.

**Pull request merged**
